### ISSUE TITLE
Přihlášení na opakující se program

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#10]
Nyní pokud se program opakuje, potom systém umožňuje přihlásit se na všechna opakování. Prosím o úpravu, pokud se uživatel přihlásí na program, potom již na ostatní opakování tohoto programu nemůže.

**Comment by DeetsCZ** [comment]
Omezení je funkční, děkuji.
Prosím ještě o úpravu:
Pokud jsem na jeden blok přihlášena, potom by ty opakující se bloky měly být šedé, jako je to v případě bloku s naplněnou kapacitou, tak aby bylo hned vidět, že se na blok již nedá přihlásit.

**Comment by jan-stanek** [comment]
Stejně tak nejsou šedé ani bloky probíhající ve stejný čas, opravím rovnou i to?

**Comment by DeetsCZ** [comment]
To je dobrý nápad. Děkuji

**Comment by DeetsCZ** [comment]
Děkuji za úpravy.
