### ISSUE TITLE
Změna adresářů log a temp

### ISSUE THREAD

**Issue by sinacek** [skaut/SRS#100]
Doporučuju změnit názvy adresářů log a temp na log-nette a temp-nette, protože po upgradu Lebedy se logy ukládají do souboru log a mohlo by dojít k míchání souborů a kolizím.
Temp bych přejmenoval aby to bylo jednotné.

https://github.com/skaut/SRS/blob/master/app/bootstrap.php#L24
https://github.com/skaut/SRS/blob/master/app/bootstrap.php#L40
https://github.com/skaut/SRS/blob/7b4631b216f9727648bf1b2f36e8c4e842dc454f/deployment.ini.sample#L15-L42

PS: nevím jestli i změna výchozího adresáře o uroven výše nezasahuje do celé instalace srs, ale nová struktura je obecně pro nette výrazně lepší.

**Comment by jan-stanek** [comment]
Teď s tím není problém, protože je celé srs ve složce www. Po aktualizaci bude upraveno.

**Comment by jan-stanek** [comment]
Nakonec jsem vrátil zpět na standardní log a temp, vypadá to, že už se na serveru používají jiné.

**Comment by sinacek** [comment]
Lebeda nakonec pouziva __log, takze s tim kolize neni, ale lze se splest tmp a temp, ale to už možná nemá cenu řešit.

**Comment by DeetsCZ** [comment]
Aktualizováno, uzavírám..
