### ISSUE TITLE
Chyba: chyba po uploadu

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#102]
Po uploadu se zobrazuje chyba:
![snimek obrazovky 2016-10-13 v 13 50 48](https://cloud.githubusercontent.com/assets/19816092/19348057/328f271a-914c-11e6-8ad9-b0b4d6df94d4.png)

**Comment by jan-stanek** [comment]
Byla provedena i ta druhá úprava databáze, co je tam ve starším komentáři?

**Comment by DeetsCZ** [comment]
Moje chyba, přehlédla jsem ten komentář..
