### ISSUE TITLE
Nová stránka Vstupenka

### ISSUE THREAD

**Issue by milanskaut** [skaut/SRS#1023]
V případě, že akce využívá Elektronické vstupenky a je po datu od kdy je možné vstupenky stahovat, objeví se pouze v Profilu uživatele možnost Stáhnout vstupenku:

![e-vstupenka](https://github.com/skaut/SRS/assets/131680899/c6d9b001-cf00-4562-a8b3-05f700fdd357)

Tohle chování bychom chtěli **nahradit novou komponentou vstupenka**.

Nová komponenta **vstupenka** se skládá z následujících prvků:

- Informační box o tom, že pro rychlé ověření pomocí e-vstupenky u vstupu na akci je nutné mít:
  - propojený skautIS účet s reálnou osobou. (Pokud není splněno, nabídnout proklik na stránku "Nemáte propojený účet")
  - Mít ve svém skautIS účtu nahranou fotografii (Pokud není splněno, nabídnout proklik do osobního profilu ve skautISu -> https://is.skaut.cz/Junak/OrganizationUnit/PersonUpdate.aspx?ID=XXXXXX)

- Možnost zobrazit obrázek QR kódu _(případně QR kód zobrazovat rovnou při načtení stránky)_
- Možnost stáhnout QR kód jako obrázek
- Možnost stáhnout PDF s QR kódem

_Tato nová komponenta vstupenka a výše uvedené chování (použité při využití funkce vstupenek) není limitované pouze pro využití na MiQuiku._

**Comment by jan-stanek** [comment]
Má vstupenka tak důležité postavení, aby byla přímo v tomhle menu? Na mobilu už to pak bude dost široké.

Osobně bych udělal komponentu, která bude v profilu v nové sekci "vstupenka" a ta samá komponenta by se zobrazovalo po přihlášení místo přihlašovacího formuláře. Podobně jako je to s tou tabulkou přihlášených podakcí, ta je taky na obou místech.

**Comment by milanskaut** [comment]
Vstupenka nemusí být v horním menu, návrh však vycházel z potřeby si to rychle na telefonu otevřít a vidět vstupenku jako první při stání ve frontě na akci samotné.

Pokud to bude komponenta a před akcí/při aktivaci vstupenek se "zveřejní" stránka Vstupenka, tak by to mělo fungovat. Navíc to zjednoduší úpravy textového bloku na dané stránce. Zda je to dostatečné řešení zjistíme až ze zpětné vazby - pokud tedy pro integritu systému navrhuješ necpat nové tlačítko do "horního" menu, udělejme z toho komponentu.

**Comment by milanskaut** [comment]
Provedeny úpravy v prvním příspěvku na základě feedbacku od Honzy & vedení akce
- Nyní se jedná o komponentu zařaditelnou pomocí redakčního systému (Weby)
- Odstraněny doprovodné texty (ty bude možné vložit pomocí textů nad a pod.
- Vstupenka (QR kód) se generuje i při nesplnění požadavků na rychlé odbavení
- Infobox nyní **pouze upozorňuje** na stav splnění dvou uvedených podmínek (pro rychlé odbavení)

_(zároveň zadána úprava pro mobilní aplikaci SRS vstupenek)_

**Comment by jan-stanek** [comment]
Vstupenka přidána, prosím o test a připomínky
