### ISSUE TITLE
Funkce Rozeslat e-mail nefunguje pro víc než 50 příjemců (při použití AWS)

### ISSUE THREAD

**Issue by milanskaut** [skaut/SRS#1027]
Při pokusu odeslat hromadný e-mail z prostředí administrace, sekce mailing, vyskočí červená chyba (warning) 

![image](https://github.com/skaut/SRS/assets/131680899/cabe34fb-6c4e-4d93-82eb-db63695cf6ca)

a log vypíše: **SMTP server did not accept . with error: 554 Transaction failed: Recipient count exceeds 50.**

Chyba byla poprvé zaznamenána při pokusu obeslat 58 účastníků. 

Dle rychlého googlení může souviset s nově použitím AWS/SES pro mailing, který je [omezen na 50 "příjemců"](https://docs.aws.amazon.com/ses/latest/APIReference/API_SendEmail.html).

**Comment by jan-stanek** [comment]
Vyřešeno frontou e-mailů
