### ISSUE TITLE
Nastavení e-mailu při nasazování via Actions

### ISSUE THREAD

**Issue by milanskaut** [skaut/SRS#1044]
Při instalaci nového prostředí přes Actions je možné využít Secrets pro nastavení SMTP údajů, ovšem jejich nastavení při prvním nasazení znefukční celý systém, protože
- v tu chvíli není možné rozesílat e-maily (na jejichž odeslání je vázána registrace či změna rolí),
- nelze ani změnit e-mailovou adresu pro odesílání zpráv, protože změnu v administraci nelze provést (neodešle se e-mail s potvrzovacím odkazem, protože žádost o změnu vyžaduje SMTP s jiným uživatelským jménem a heslem)

Bylo by skvělé mít v Actions možnost nastavit i výchozí odesílací adresu - i za cenu přesunutí z administrace & databáze do konfiguračního souboru (a v adminu nechat pouze adresu pro zprávy z formuláře).

**Comment by jan-stanek** [comment]
E-mail semináře se bude nastavovat jen v configu (přes secrety v actions), takže mizí celé zasílání potvzovacích kódů apod.

K webům, které se budou nově nasazovat nebo aktualizovat je třeba přidat secret `CONFIG_MAILING_SENDER_EMAIL`, default hodnota je `srs@skaut.cz`

**Comment by milanskaut** [comment]
Skvělé řešení, děkuji mockrát - již vyzkoušeno i přes Actions!
