### ISSUE TITLE
Nelze odesílat maily bez adresáta (skrytá kopie)

### ISSUE THREAD

**Issue by milanskaut** [skaut/SRS#1056]
Mnoho mailingových částí SRS využívá prázdné pole adresáta a skrytou kopii: 
![image](https://github.com/skaut/SRS/assets/131680899/e5006557-d40d-4d50-b265-19a2e2bce4f0)

Po nově nasazených změnách se objevují chyby 500, protože pole příjemce nemůže být prázdné.
![image](https://github.com/skaut/SRS/assets/131680899/766bd642-5719-40dc-a2f9-6517ba9b0b6f)

Zatím vyzkoušeno při změně role & rozesílání mailu pomocí Mailing: Rozeslat e-mail: Příjemci - uživatelé.

_Pozn: Při využití Příjemci - uživatelé (výběr konkrétní osoby) a zároveň možnosti "Zaslat kopii na" se oba e-maily poslali úspěšně_ 
![image](https://github.com/skaut/SRS/assets/131680899/bfa1d468-8e00-4623-9736-9780f65662fe)

**Comment by jan-stanek** [comment]
Opraveno v #1057 a #1070
