### ISSUE TITLE
Modul: Safe from Harm

### ISSUE THREAD

**Issue by milanskaut** [skaut/SRS#1063]
Povinností všech účastníků akce je vyplnění testu v podobě Google formuláře “Safe from Harm”. Součástí formuláře je i políčko pro zadání **unikátního kódu**, který účastníci získají v SRS. Nejedná se o variabilní symbol.

_Google formulář nám poté vyexportuje tabulkový soubor se všemi unikátními kódy, kteří formulář úspěšně splnili. Splnění této podmínky je nutné pro vpuštění do areálu na akci a v případě nesplnění této podmíky budou muset účastníci akce tento formulář vyplňovat pomocí tužky a papíru na místě._

**Potřebujeme mít nový modul, který bude zobrazovat unikátní kód účastníka.**
![image](https://github.com/skaut/SRS/assets/131680899/85e03c54-7404-4e22-8fbc-f8fc18409403)
Texty s informacemi k použití kódu apod. budou doplněny v textových modulech

----

Zároveň potřebujeme mít **možnost v administraci u uživatelů v jejich profilech zobrazovat a nastavovat, zda mají Safe from Harm splněný**, zatímco uživatelé tuto možnost mít nemají. Tato informace se zobrazuje jak na přehledu účastníků, tak na seznamech účastníků ve skupinách.

V administraci se má jednat o překlikávací políčko ve stylu Splněno / Nesplněno, stylově podobné 
![image](https://github.com/skaut/SRS/assets/131680899/ed51b7f4-927f-4604-afdb-55c7d1695494)

Exportování stavu “Splněný / Nesplněný” z google dokumentu budeme dělat před akcí přímo úpravou databáze. Safe from harm by mělo mít samostatnou tabulku, která by obsahovala unikátní kód a Splněno / Nesplněno.

**Comment by jan-stanek** [comment]
Není to Safe FROM harm?
