### ISSUE TITLE
SQL import

### ISSUE THREAD

**Issue by milanskaut** [skaut/SRS#1066]
Úpravy pro Obrok budeme nasazovat na instalaci SRS, kde již bude vytvořený webový obsah a registrovaní organizátoři a členové týmu. Před nasazením nové verze SRS je třeba mít SQL import pro vytvoření příslušných tabulek.

**Comment by jan-stanek** [comment]
To udělá migrace, měla by se vygenerovat automaticky přes: `php www/console.php migrations:diff`

**Comment by jan-stanek** [comment]
Issue asi není třeba, pokud by se vytvořily jen databázove entity a chyběla by migrace, tak neprojdou kontroly v actions, je třeba migraci přidat rovnou v rámci jiného issue.
