### ISSUE TITLE
Úprava instalátoru

### ISSUE THREAD

**Issue by milanskaut** [skaut/SRS#1067]
Podpora registrace skupin není určená pouze pro Obrok, ale má být součástí SRS natrvalo.

V závěru programování bude třeba upravit instalátor, aby automaticky vytvářet požadované položky v databázi (i v případě, že se akce rozhodne nevyužít registraci skupin)

**Comment by jan-stanek** [comment]
Tohle taky udělá migrace, ten instalátor jen spouští migrace, ale při nasazení přes actions se spouští už tam. Tohle issue bych zavřel jako duplicitní k #1066

**Comment by milanskaut** [comment]
Uzavírám jako duplicitní k https://github.com/skaut/SRS/issues/1066, věřím že Honza Staněk může pomoci s migracemi.
