### ISSUE TITLE
Přehled uživatelů

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#11]
Do frontpage přidat okno, které zobrazuje přehled uživatelů. 
V administraci v editoru rolí přidat checkbox "Zobrazit v přehledu uživatelů". Pokud se checkbox zaškrtne, potom se uživatelé v této roli zobrazí v přehledu na frontpage.

**Comment by jan-stanek** [comment]
```
CREATE TABLE `srs`.`userboxcontent` ( `id` INT(11) NOT NULL AUTO_INCREMENT , PRIMARY KEY (`id`)) ENGINE = InnoDB;
ALTER TABLE `role` ADD `displayInList` BOOLEAN NOT NULL DEFAULT FALSE AFTER `syncedWithSkautIS`;
```

**Comment by DeetsCZ** [comment]
Testovala jsem a řešení je funkční, děkuji. 
Jen ještě prosím o drobnou úpravu:

1. odebrat odrážky
2. doplnit nadpisem "Přihlášení uživatelé"

**Comment by jan-stanek** [comment]
Odrážky skryty pomocí css.

Nadpis mi přijde lepší přidat pomocí boxu "text" nad tímto boxem - ostatní boxy také nemají nadpisy a pokud by byla vytvořena samostatná stránka s přehledem uživatelů, nadpis by byl zdvojený.

**Comment by DeetsCZ** [comment]
To skrytí pomocí css způsobilo skrytí i odrážek v modulu Aktualit, tam by ale být měly.
![snimek obrazovky 2016-08-26 v 13 34 03](https://cloud.githubusercontent.com/assets/19816092/18004077/ff6d01e8-6b91-11e6-8158-0dd447e4c3fd.png)

**Comment by jan-stanek** [comment]
opraveno

**Comment by DeetsCZ** [comment]
Děkuji
