### ISSUE TITLE
Registrovatelnost programu

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#110]
Na stránce konfigurace, prosím o přidání datumu od kdy a do kdy je možné přihlašovat se do programových bloků.
Nyní je pouze "Je povoleno přihlašovat se na programové bloky?", prosím o přidání i data.

**Comment by jan-stanek** [comment]
Pouze datum, nebo také datum a čas?

**Comment by DeetsCZ** [comment]
Pro jistotu prosím i s časem. Děkuji

**Comment by jan-stanek** [comment]
`INSERT INTO `Settings` (`id`, `item`, `value`, `description`) VALUES (NULL, 'log_in_programs_from', '18.10.2016 00:00', 'Přihlašování programů otevřeno od'), (NULL, 'log_in_programs_to', '19.10.2016 00:00', 'Přihlašování programů otevřeno do')`

**Comment by DeetsCZ** [comment]
Databáze upravena

**Comment by DeetsCZ** [comment]
Pokud není povolené zapisování, potom se správně zobrazuje varování, že zapisování není možné, ale přitom se lze program zapsat i odepsat:
![snimek obrazovky 2016-10-18 v 11 57 33](https://cloud.githubusercontent.com/assets/19816092/19473095/5831cf36-952a-11e6-883c-307df1116169.png)

Události v kalendáři by měly být všechny šedivé, pokud není zápis povolený..

**Comment by jan-stanek** [comment]
Šedivě jsou všechny, kromě těch, které má již uživatel zapsané, aby viděl, co má zapsané po ukončení přihlašování.

**Comment by DeetsCZ** [comment]
Děkuji
