### ISSUE TITLE
Čas pro registraci do role

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#111]
Ve formuláři role u položky registrovatelná od do přidat i čas. Tak aby se dala registrace do role spustit v určitý čas, ne o půlnoci (jak je tomu nyní).

**Comment by jan-stanek** [comment]
`ALTER TABLE `Role` CHANGE `registerableFrom` `registerableFrom` DATETIME NULL DEFAULT NULL, CHANGE `registerableTo` `registerableTo` DATETIME NULL DEFAULT NULL;`

**Comment by DeetsCZ** [comment]
Databáze upravena

**Comment by DeetsCZ** [comment]
Děkuji za úpravu
