### ISSUE TITLE
Den navíc před odhlášením z důvodu nezaplacení

### ISSUE THREAD

**Issue by milanskaut** [skaut/SRS#1127]
![image](https://github.com/skaut/SRS/assets/131680899/f59c0a56-b39e-43c9-b0ce-8ab8e81244f2)

V případě, že použiji výše zobrazené nastavení a registrace začne v úterý, tak...
- úterý registrace _(den 0)_ 
- čtvrtek připomínkový mail _(den 2)_
- pátek vypršel termín _(den 3)_
- sobota **by mělo dojít** ke zrušení místa _(den 4)_
- **ke zrušení však dojde až v neděli _(den 5)_**

Víme, čím je způsobený extra den a má nějaký význam, případně lze jej odstranit?

**Comment by jan-stanek** [comment]
Ruší se to někdy brzy ráno, ten den po splatnosti chápu jako takovou rezervu (bonus), kdy někdo zaplatí v den splatnosti, tak aby platba stihla ještě prijit (tenkrát nebyly okamžité platby). Takže se tím myslí jeden celý den. Pokud ho nechtějí, dá se nastavit 0.
