### ISSUE TITLE
Zobrazení přihlášených rolí

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#113]
V záhlaví prosím zobrazovat všechny role, do kterých je uživatel přihlášený. Například já mám role administrátor, účastník 100 a účastník 200, ale v záhlaví je pouze administrátor:
![snimek obrazovky 2016-10-17 v 21 31 11](https://cloud.githubusercontent.com/assets/19816092/19452454/63477502-94b1-11e6-8437-f34cff884790.png)

**Comment by DeetsCZ** [comment]
Nevím, čím to je ,ale najednou toto funguje:
![snimek obrazovky 2016-10-17 v 21 41 04](https://cloud.githubusercontent.com/assets/19816092/19452732/7127cc8e-94b2-11e6-8fd7-8e3faafe019e.png)

Prosím tedy o prověření a úpravu, aby se role zobrazovaly vždy.. Děkuji

**Comment by jan-stanek** [comment]
Ty role, se kterými se pracuje, se načítají při přihlášení, takže pokud se změní ručně v administraci, tak je potřeba se odhlásit a přihlásit.

**Comment by DeetsCZ** [comment]
To jsem zkoušela a systém zareagoval až na několikátý pokus :(

**Comment by jan-stanek** [comment]
Nepodařilo se mi zopakovat, po přihlášení tam mám vždy správné role.

**Comment by jan-stanek** [comment]
Nemohlo to nějak souviset s přihlášením pod jinou rolí? Tím se mění právě tyhle role.

**Comment by DeetsCZ** [comment]
Zkoušela jsem a už jsem situaci nenasimulovala, tady nyní uzavírám..
