### ISSUE TITLE
Úprava profil

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#114]
Prosím o úpravu profilu:

1. blok "Seminář - účast, platba, tisk potvrzení" dát jako první, před osobní údaje a rozbalit, aby se tyto informace zvýraznily

2. prosím o prověření položky "Účast na semináři: Neúčastníte se", nepovedlo se mi nasimulovat, jak se tato položka chová, bylo by možné zjistit, co toto znamená? 

3. Cena semináře: pokud je uživatel ve více placených rolích, potom prosím rozepsat jednotlivé částky: 
 - role1: cena
 - role2: cena 
 - ...
 - celkem: cena

Děkuji

**Comment by DeetsCZ** [comment]
Zjistil jsi, jak funguje ta "Účast na semináři"?

**Comment by jan-stanek** [comment]
Zapomněl jsem to napsat, byla tam opačně podmínka, te se zobrazí:

- uživatel v roli Nepřihlášený - neúčastníte se
- uživatel v ostatních rolích - vypíší se role

**Comment by DeetsCZ** [comment]
Profil se zobrazuje na správném místě, ale chybí údaje o účasti a platbě:
![snimek obrazovky 2016-10-18 v 11 49 39](https://cloud.githubusercontent.com/assets/19816092/19472866/508f2e00-9529-11e6-8ba5-c96ff42f86d0.png)

**Comment by jan-stanek** [comment]
Jsou skryté, pokud uživatel neplatí.

**Comment by DeetsCZ** [comment]
Pravda, nevšimla jsem si, že pro účastníka 21, aby nastaveno, že neplatí a lektor měl zaškrtnuto, že platí 0. 
Vše funguje správně. Děkuji
