### ISSUE TITLE
Úprava tvorby variabilního symbolu

### ISSUE THREAD

**Issue by milanskaut** [skaut/SRS#1162]
Pro potřeby ústředních akcí potřebujeme mít možnost **nastavit až pětimístný prefix pro variabilní symbol**.

Pro zamezení problémů s některými bankami, jenž doplňují variabilní symboly na jejich maximální délku (10), prosím o **nastavení statické desetimístné délky**. (vyřeší i https://github.com/skaut/SRS/issues/1126)

---

_Aktuálně se za nastavený prefix vloží šestimístné číslo, takže VS mohou být šestimístné až desetimístné._

Nebráním se variantě vynucování (příp. automatického doplňování) pětimístného prefixu při nastavování plateb v nastavení a poté přidávání pětimístného vygenerovaného (pořadového) čísla.

_Je možné, abych při aktualizacích aktuálně pořádaných akcí (přes zimu běží přihlašování na velmi malém počtu instalací), zajistit úpravu VS ručně a nebude třeba žádných systémových kontrol a doplňování už starších instalací, pokud to proces zjednoduší._

**Comment by jan-stanek** [comment]
Těch 5 míst umožní mít 100 000 přihlášek, asi to bude stačit pro všechny akce, ale Miquik se tomu může celkem blížit. Podíval by ses prosím, jaký měli letos nejvyšší VS?

**Comment by milanskaut** [comment]
Nejvyšší hodnota VS na letošním MiQuiku byla 3400.
