### ISSUE TITLE
Povinná návaznost rolí

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#123]
Tak jako je možné zadat, které role není možné kombinovat spolu, prosím zpracovat i povinnost, které role musí být vybrané současně.
Zadání souvislosti by mělo být stejné jako u "Neregistrovatelná s".
Následně pokud v registraci uživatel vybere roli, která má zadanou souvislost s jinou, potom se související role přidá automaticky.
Pokud platí, že role 1 vyžaduje registraci role 2, potom ale neplatí, že role 2 (pokud to nemá nastaveno) by musela být vybrána spolu s rolí 1.

**Comment by jan-stanek** [comment]
Úprava db:
```
RENAME TABLE role_role TO role_role_incompatible;

CREATE TABLE `role_role_required` (
`role_id` int(11) NOT NULL,
`required_role_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

ALTER TABLE `role_role_required`
  ADD PRIMARY KEY (`role_id`,`required_role_id`),
  ADD KEY `IDX_45B98BABD60322AC` (`role_id`),
  ADD KEY `IDX_45B98BABF7E2056C` (`required_role_id`);

ALTER TABLE `role_role_required`
  ADD CONSTRAINT `FK_45B98BABD60322AC` FOREIGN KEY (`role_id`) REFERENCES `Role` (`id`),
  ADD CONSTRAINT `FK_45B98BABF7E2056C` FOREIGN KEY (`required_role_id`) REFERENCES `Role` (`id`);
```

**Comment by jan-stanek** [comment]
Nahrána úprava datového model - je možné změnit db a bude to fungovat, funkce se může dodělat později.

**Comment by DeetsCZ** [comment]
Databáze upravena

**Comment by jan-stanek** [comment]
Má se to chovat tranzitivně (role A souvisí s rolí B, B souvisí s C, uživatel vybere A a přidá se mu B i C)?

**Comment by jan-stanek** [comment]
Vlastně by mělo, pokud by zvolil A a B ručně, tak by se to pak chovali jinak...

**Comment by DeetsCZ** [comment]
Určitě, pokud má A návaznost na B a B na C, potom se po vybrání A vybere B i C.

**Comment by jan-stanek** [comment]
Je tam poměrně složité ošetření, aby se nemohlo stát, že nelze zapsat současně role, které spolu souvisí (třeba přes více rolí), snažil jsem se otestovat na případu:

účastník souvisí s účastník 2 a účastník 100
účastník 2 souvisí s účastník 200
účastník 100 souvisí s účastník 200
účastník 200 souvisí s účastník 100

Měly by tam být pokryté všechny případy, tak snad se neobjeví žádná chyba...

**Comment by DeetsCZ** [comment]
Vzniká tam konflikt, kdy role A musí mít roli B, ale nesmí mít roli C, dále B musí mít roli D a role D musí mít C. Potom se při přidání A přidá B, C i D. Situace se pravděpodobně v ostrém provozu vyskytovat nebude, předpokládáme spíš situaci, kdy zápis vedlejších seminářů je podmíněn zápisem jednoho hlavního, ale asi by bylo dobré toto v budoucnu ošetřit.

**Comment by DeetsCZ** [comment]
Přidání související role je malinko matoucí, tím že ve formuláři se vyplní role a související se přidá až po potvrzení. Bylo by možné, aby se rovnou při vybrání role přidala povinná do formuláře?
![snimek obrazovky 2016-10-21 v 10 01 18](https://cloud.githubusercontent.com/assets/19816092/19591053/65e2840c-9775-11e6-8525-831108f0bfd0.png)

**Comment by jan-stanek** [comment]
Asi bude nakonec potřeba kontrolovat vztahy mezi všemi rolemi, protože u D nemám informaci o tom, jaké role souvisejí s D.

Automaticky přidat související by mělo jít, pokud by se ale mělo kontrolovat i to, že uživatel pak některou z nich neodebere apod., bylo by to už docela kompilovné. Stačí tedy jen přidat všechny související a pokud by uživatel nějakou odebral, přidá se automaticky při odeslání jako teď?

**Comment by jan-stanek** [comment]
To by šlo a automatické přidání by se dalo případně přidat někdy v budoucnu.

**Comment by DeetsCZ** [comment]
Ok, tak to tak udělejme..

**Comment by jan-stanek** [comment]
- Ošetřen zmíněný případ.
- Přidáno zobrazení hlášky o chybějích souvisejích rolích.
- Automatické přidávání jsem zkoušel, ale nefunguje mi s tím multiselectem, který se tam používá.

**Comment by DeetsCZ** [comment]
Narazila jsem na chybu:

Účastník má povinnou roli účastník povinný 
Účastník povinný má povinnou roli účastník povinný 2

Zadala jsem role účastník a účastník povinný
při uložení mi píše systém, že k Účastník je povinná role účastník povinný, ale tuto podmínku jsem splnila, mělo by tam správně být, že Účastník povinný má povinnou roli účastník povinný 2

![snimek obrazovky 2016-10-23 v 13 40 04](https://cloud.githubusercontent.com/assets/19816092/19625945/a532729a-9926-11e6-9f9c-65efae1b2159.png)

**Comment by DeetsCZ** [comment]
Děkuji za řešení
