### ISSUE TITLE
Odebírání a přidávání rolí uživatelem

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#124]
Umožnit uživateli, aby se sám upravoval své role:
- v profilu v sekci seminář by mohlo být tlačítko "Upravit role", které otevře dialogové okno a tam by si uživatel naklikal role, které chce, nebo nechce, mohla by se použít stejná tabulka jako při registraci
- nebo by ta tabulka mohla být v profilu rovnou v sekci seminář

- pokud by některá nově přidaná role vyžadovala schválení, potom by se v administraci opět schvaloval uživatel jako celek

**Comment by jan-stanek** [comment]
Jaká tam mají platit omezení? Přidávání nových rolí pouze v období, kdy jsou registrovatelné a odebírání rolí pouze do konce odhlašování ze semináře?

**Comment by DeetsCZ** [comment]
Tady je duležitá jedna věc, dokud uživatel není již přihlášený v nějaké roli (přes registraci), potom by němel vidět v profilu formulář pro úpravu rolí. Mohlo by docházet k tomu, že by si zadávali role bez registrace a to je určitě špatně..

**Comment by DeetsCZ** [comment]
Při změně rolí se samozřejmě neaktualizují role, které uživatel má ani jeho profil. Je to trochu matoucí. Přemýšlím, jak toto vyřešit, ale asi bude jediná možnost při úspěšné změně odhlásit uživatele jako při odeslání registrace, tím se vyřeší i přepnutí uživatele do role neschválený, pokud si vybere roli, kterou je potřeba schválit..

**Comment by DeetsCZ** [comment]
Testovala jsem přidat roli, kterou je potřeba schválit, zde se uživatel správně přepne do role neschválený, pokud ale znovu role upravím a ponechám pouze role, které není potřeba schválit, potom by měl být schválený. Nyní zůstává stále v roli neschválený.

**Comment by DeetsCZ** [comment]
Ještě tu mám od Čonkina prosbu o úpravu. 
Pokud je u uživatele vyplněno datum platby, tedy již za seminář zaplatil, potom už nemá mít možnost měnit si role v profilu..

**Comment by DeetsCZ** [comment]
Děkuji za úpravy
