### ISSUE TITLE
Chyba: Nepřihlášenému zůstavají zapsané semináře

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#128]
Uživatele jsem v administraci přepnula do role nepřihlášený a když jsem se pod ním přihlásila, tak ikdyž nemá vyplněnou přihlášku a má jen roli nepřihlášený, tak má zapsané programy, které jsem zapsala před tím. Dokonce se může i na programy přihlašovat.

Chování by mělo být takové, že:

1. Nepřihlášený se nemůže přihlašovat na program
2. Pokud se uživatel v administraci přesune do role nepřihlášený, potom by se u něm měly smazat všechny přihlášené semináře

**Comment by jan-stanek** [comment]
Stejně tak, pokud je mu odstraněna role a přestaně mít přístup k programům v některé kategorii?

**Comment by DeetsCZ** [comment]
Ano, protože se musí uvolnit kapacita programu pro další účastníky..

**Comment by DeetsCZ** [comment]
Pravděpodobně podobný problém se zápisem programu, ač mám roli, která nemá právo si program zapisovat, což mi i systém píše, tak mi zápis povolí:
![snimek obrazovky 2016-10-21 v 9 38 22](https://cloud.githubusercontent.com/assets/19816092/19590457/4aaa61d0-9772-11e6-8480-bc182a87a47d.png)

**Comment by DeetsCZ** [comment]
Děkuji za opravu
