### ISSUE TITLE
Nelze měnit pořadí bloků na stránkách

### ISSUE THREAD

**Issue by milanskaut** [skaut/SRS#1292]
V administraci není možné při editaci stránek **změnit pořadí jednotlivých bloků** (či komponent) pomocí posuvníku ![image](https://github.com/skaut/SRS/assets/131680899/4a1861ab-9561-4ec7-bfd9-ed92628be141). Vizuálně je možné změny provézt, ale ani jedno z tlačítek "Uložit" a "Uložit a pokračovat v úpravách" **nezaznamená změny do databáze**. Administrace však při uložení hlásí "Stránka byla úspěšně uložena."

Vyskytuje se u všech instalací SRS.

Mazání stránek a tvorba bloků funguje správně, při změně pořadí bloků přímo v databázi dojde k úpravě.

**Comment by jan-stanek** [comment]
Opraveno vrácením tinyMCE o 2 verze, už to tam muselo být poměrně dlouho. U nové se mi nepovedlo rychle najít řešení.
