### ISSUE TITLE
Chyba: nejde zapisovat program v povoleném termínu

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#131]
Zapisování do programu jsem povolila v intervalu:
![snimek obrazovky 2016-10-19 v 22 26 00](https://cloud.githubusercontent.com/assets/19816092/19536270/856bbf62-964b-11e6-9341-24c4f1e67ea4.png)

Ale v kalendáři mi stejně svítí varování, že nelze zapisovat:
![snimek obrazovky 2016-10-19 v 22 26 52](https://cloud.githubusercontent.com/assets/19816092/19536279/94e5e5ee-964b-11e6-8d71-4ac023346db0.png)

Jen doplním, že je 19.10.2016 22:30

**Comment by jan-stanek** [comment]
Je zaškrtnuto `Je povoleno přihlašovat se na programové bloky?`?

Kde je to testováno? Na srs.skauting.cz to jde, ale mohl by být problém třeba s časovými pásmy.
