### ISSUE TITLE
Neukládají se "Společně neregistrovatelné" podakce.

### ISSUE THREAD

**Issue by milanskaut** [skaut/SRS#1362]
Při snaze nastavit si podakce, které není možné registrovat společně (například noční hra a noční sledování filmu) pomocí administrace dojde k odeslání formuláře a objeví se zelený box s informací o provedení akce, ale k propsání změn nedojde. Při vložení neregistrovatelnosti přímo v databázi vše funguje.

![image](https://github.com/user-attachments/assets/5c90a20c-9c58-47a2-a70d-3c8917d4132d)
![image](https://github.com/user-attachments/assets/d7c21b5b-bf76-4db9-80c2-1ba43486985c)

**Comment by milanskaut** [comment]
Stejný problém existuje i u "Vyžadované podakce".

**Comment by jan-stanek** [comment]
Kde se to děje? Zkouším to lokálně i na srs.skauting.cz (kde je aktuální verze z gitu) a na obou mi to funguje.
