### ISSUE TITLE
Chyba: nepotvrzený uživatel

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#139]
1. Pokud přihláška uživatele není potvrzena, potom by se neměl zohledňovat v kapacitách rolí:
![snimek obrazovky 2016-10-21 v 10 11 37](https://cloud.githubusercontent.com/assets/19816092/19591402/2951d9aa-9777-11e6-972f-d5f6e43b9d78.png)

2. Pokud při potvzení  administraci je vyčerpaná kapacita, potom by se při pokusu o potvrzení mělo zobrazit varování a potvrzení nepovolit.

3. Pokud uživatel není potvrzení, potom by se v profilu měla zobrazovat hláška:
"Vaše přihláška zatím nebyla schválena"
![snimek obrazovky 2016-10-21 v 10 12 11](https://cloud.githubusercontent.com/assets/19816092/19591451/65a5920c-9777-11e6-80e5-8a7e0c50ecb8.png)

**Comment by jan-stanek** [comment]
Co tedy ještě vytvořit systémovou roli "Nepotvrzený"? Přijde mi to jasnější pro uživatele a možná jednodušší implementačně.

**Comment by DeetsCZ** [comment]
To by vyřešilo bod 3.
Předpoklám, že bod 1 a 2 bude potřeba stejně dořešit.

**Comment by DeetsCZ** [comment]
Ale řešení s rolí "Nepotvrzený" mi přijde jako dobrý nápad. Bude to opravdu jasnější.

**Comment by jan-stanek** [comment]
To bude, ale bude na to speciální role, místo pidmínky na schválení.

**Comment by jan-stanek** [comment]
Ještě bych také u role zrušil `pays`, protože k tomu stačí pole cena. A může se stát, že je zaškrtnuto pays a cena 0 a naopak...

**Comment by jan-stanek** [comment]
Špatně jsem to napsal, schválené zůstane stejně jak je. Role "Neschválený" nepůjde nikomu přidělit ani nebude vidět v administraci (kromě seznamu rolí), bude se používat pouze při přihlášení uživatele, který není schválený místo role "Nepřihlášený" - pro uživatele to bude jasnější, pro hlášky v profilu pak nebude třeba zjišťovat jestli je uživatel schválený, ale bude to poznat z role, také to bude lépe fungovat možnost "přihlásit pod rolí" pro testování.

**Comment by DeetsCZ** [comment]
Takto s tím souhlasím, zní to rozumně..

**Comment by jan-stanek** [comment]
```
ALTER TABLE `Role` DROP `pays`;
INSERT INTO `Role` (`id`, `name`, `system`, `registerable`, `approvedAfterRegistration`, `registerableFrom`, `registerableTo`, `usersLimit`, `fee`, `syncedWithSkautIS`, `displayInList`, `displayArrivalDeparture`, `displayCapacity`) VALUES (NULL, 'Neschválený', '1', '0', '0', NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL);
```

Ručně je třeba roli `Neschválený` přidat přístup ke všem stránkám.

**Comment by DeetsCZ** [comment]
Databáze upravena

**Comment by DeetsCZ** [comment]
Přihlášení neschváleného uživatele zobrazí chybu:
![snimek obrazovky 2016-10-23 v 13 08 23](https://cloud.githubusercontent.com/assets/19816092/19625782/e3fbf596-9921-11e6-980a-4c87e9a5cd93.png)

**Comment by jan-stanek** [comment]
Je třeba roli ručně přidat oprávnění ke všem stránkám - nevěděl jsem jaké bude mít, abych to napsal do SQL, tak jsem to napsal jen pod ten skript.

Na srs.skauting.cz už jsem jí je přidal a mělo by to fungovat.

**Comment by DeetsCZ** [comment]
Prosím ještě roli Neschválený přesunout mezi Nepřihlášený a Účastník v přehledu rolí, aby bylo hned jasné, kam tato role hierarchicky patří. Děkuji
Práva k stránkám jsem změnila i na miquik.skauting.cz a otestuji...

**Comment by DeetsCZ** [comment]
Prosím o prohození, jinak je vše funkční, děkuji.

**Comment by jan-stanek** [comment]
Role jsou řazeny podle id, při nové instalaci na tom místě bude, ale tady už to změnit nepůjde - musely by se proházet id rolí a všechno, co je na to navázané.

**Comment by jan-stanek** [comment]
na srs.skauting.cz, by mělo fungovat tohle, ale lepší by bylo nejdřív databázi zazálohovat

```
SET FOREIGN_KEY_CHECKS=0;

UPDATE Role SET id = id + 1 WHERE id >= 3 ORDER BY id DESC;
UPDATE Role SET id = 3 WHERE id = 20 ORDER BY id DESC;

UPDATE category_role SET role_id = role_id + 1 WHERE role_id >= 3 ORDER BY role_id DESC;
UPDATE category_role SET role_id = 3 WHERE role_id = 20 ORDER BY role_id DESC;

UPDATE page_role SET role_id = role_id + 1 WHERE role_id >= 3 ORDER BY role_id DESC;
UPDATE page_role SET role_id = 3 WHERE role_id = 20 ORDER BY role_id DESC;

UPDATE role_permission SET role_id = role_id + 1 WHERE role_id >= 3 ORDER BY role_id DESC;
UPDATE role_permission SET role_id = 3 WHERE role_id = 20 ORDER BY role_id DESC;

UPDATE user_role SET role_id = role_id + 1 WHERE role_id >= 3 ORDER BY role_id DESC;
UPDATE user_role SET role_id = 3 WHERE role_id = 20 ORDER BY role_id DESC;

UPDATE role_role_incompatible SET role_id = role_id + 1 WHERE role_id >= 3 ORDER BY role_id DESC;
UPDATE role_role_incompatible SET incompatible_role_id = incompatible_role_id + 1 WHERE incompatible_role_id >= 3 ORDER BY incompatible_role_id DESC;
UPDATE role_role_incompatible SET role_id = 3 WHERE role_id = 20 ORDER BY role_id DESC;
UPDATE role_role_incompatible SET incompatible_role_id = 3 WHERE incompatible_role_id = 20 ORDER BY incompatible_role_id DESC;

UPDATE role_role_required SET role_id = role_id + 1 WHERE role_id >= 3 ORDER BY role_id DESC;
UPDATE role_role_required SET required_role_id = required_role_id + 1 WHERE required_role_id >= 3 ORDER BY required_role_id DESC;
UPDATE role_role_required SET role_id = 3 WHERE role_id = 20 ORDER BY role_id DESC;
UPDATE role_role_required SET required_role_id = 3 WHERE required_role_id = 20 ORDER BY required_role_id DESC;

SET FOREIGN_KEY_CHECKS=1;
```

**Comment by jan-stanek** [comment]
jinde bude třeba nahradit číslo 20 id role neschválený + 1

**Comment by DeetsCZ** [comment]
Error
Zobrazí se následující chyba:

SQL query:

UPDATE Role SET id = id + 1 WHERE id >= 3 ORDER BY id DESC

MySQL said: Documentation
#1451 - Cannot delete or update a parent row: a foreign key constraint fails (`testweb`.`page_role`, CONSTRAINT `FK_D0AD96B0D60322AC` FOREIGN KEY (`role_id`) REFERENCES `Role` (`id`) ON DELETE CASCADE)
Open new phpMyAdmin window

**Comment by jan-stanek** [comment]
v phpMyAdminu by měla být možnost "Zapnout kontrolu cizích klíčů", její odškrtnutí by mělo pomoci

**Comment by DeetsCZ** [comment]
Pomohlo děkuji
