### ISSUE TITLE
Generování VS

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#140]
Prosím doplnit generování VS, tak aby nevznikaly duplicity. Napadlo mne, že nejjednodušší by bylo kontrolovat VS a při nalezení shody přičíst 1, potom udělat znovu kontrolu a pokud najde shodu opět přičíst 1 a ve chvíli kdy již nenajde shodu skončit.
Nebo potom generovat úplně náhodně, ale tak asi bude muset být na kontrola také.

**Comment by jan-stanek** [comment]
Přičítání jedničky mi přijde lepší, nebo přidat na konec ještě 1-2 číslice a počítat od 00 do 99.

**Comment by jan-stanek** [comment]
```UPDATE `User` SET `variableSymbol`=NULL```

**Comment by DeetsCZ** [comment]
Databáze upravena

**Comment by jan-stanek** [comment]
Opravena chyba u VS začínajích 0, prosím o znovu upravení db (```UPDATE `User` SET `variableSymbol`=NULL```)

**Comment by DeetsCZ** [comment]
Databáze upravena

**Comment by DeetsCZ** [comment]
Všimla jsem si ještě jedné chyby: variabilní symbol nyní nejde v administraci měnit.

**Comment by DeetsCZ** [comment]
Generování otestováno, prosím tedy jen povolit úpravu v administraci

**Comment by jan-stanek** [comment]
To je schválně, myslel jsem, že to bylo jen kvůli těm kolizím.

Má být možnost měnit i jeho předvolbu, nebo jen tu část odvozenou z datumu?

Pokud by byla možnost měnit i předvolbu nebylo by možné předvolbu později upravit v konfiguraci, protože by se ukládalo k uživatelům číslo celé.

**Comment by DeetsCZ** [comment]
měla by být možnost měnit jak předvolbu, tak i tu odvozenou část, může se stát, že bude za některé platit jednotka a potom by bylo výhodné mít například stejný VS..

Myslím, že změna předvolby v průběhu se neprojeví na již vygenerovaných VS, to podle mne nění problém. Možná aby to bylo jasné, můžeš pod políčko v konfiguraci přidat text: "Změna předvolby se neprojeví na již vygenerovaných VS".
Děkuji

**Comment by DeetsCZ** [comment]
Prosím ještě v evidenci uživatelů povolit vyhledávání podle VS, jako je to například u jména.
Děkuji

**Comment by DeetsCZ** [comment]
Děkuji
