### ISSUE TITLE
Převod vstupenky: Modifikace modulu Platba

### ISSUE THREAD

**Issue by milanskaut** [skaut/SRS#1421]
Při převodu vstupenky z jednoho uživatele na druhého dojde k odstranění záznamu o propojeném uživatelském účtu z menu Platby a zároveň k odstranění VS v "přehledu" na kartě Uživatelé. Není poté možné dohledat platbu (nyní by bylo nutné porovnávat jméno vlastníka účtu či popisek platby, příp. proklikávat detaily všech účtů).

![image](https://github.com/user-attachments/assets/a5a35f62-24c0-468d-8bcd-5a36fe651daa)

Je možné zajistit dohledatelnost operace? Např. využíváním popisku převodu od / na v rámci celé aplikace?

**Comment by jan-stanek** [comment]
tohle je dané tím, že se nezobrazují zrušené přihlášky, ale asi by nemělo být složité aby se zobrazovaly alespoň v modulu platby

**Comment by jan-stanek** [comment]
bude upraveno tak, že pokud se přihláška zruší až po tom, co je zaplacená a má u sebe spárovanou platbu (tohle se děje i pokud registraci zruší třeba administrátor), tak se použije nový stav `PAIRED_CANCELED` místo `NOT_PAIRED_CANCELED` a zůstane tam prolinkování

**Comment by jan-stanek** [comment]
#1425
