### ISSUE TITLE
Převod vstupenek: Výška boxu pro výběr uživatele

### ISSUE THREAD

**Issue by milanskaut** [skaut/SRS#1422]
Prosím o omezení výšky bloku pro výběr uživatele při převodu vstupenky, aby nedocházelo na běžných zařízeních ke schování search baru pod vrchní "fixed" menu. 

![image](https://github.com/user-attachments/assets/ed7bff3a-f8a1-4f57-a82f-ec9ea108f3c9)

**Comment by jan-stanek** [comment]
Dá se omezit počet položek, 10 by snad mělo být ok i na menších zařízeních

**Comment by jan-stanek** [comment]
vyřešeno v #1425
