### ISSUE TITLE
Zobrazit kapacitu role

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#143]
Prosím přidat zobrazení kapacity role do formuláře pro úpravu uživatele v administraci, jako je to při registraci.
![snimek obrazovky 2016-10-22 v 15 36 25](https://cloud.githubusercontent.com/assets/19816092/19619693/91744f94-986d-11e6-8cda-e3779ca296b8.png)

![snimek obrazovky 2016-10-22 v 15 39 31](https://cloud.githubusercontent.com/assets/19816092/19619709/c1123a04-986d-11e6-8a70-b2c1d05cbf37.png)

**Comment by jan-stanek** [comment]
Dáme tam tedy "obsazeno 4/10" případně "Obsazenost: 4/10"?

**Comment by DeetsCZ** [comment]
Děkuji
