### ISSUE TITLE
Export uživatelů jako podklad pro vstupenky

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#144]
Do tabulky evidence účastníků přidat tlačítko pro export uživatelů do excelu jako podklad pro vstupenky:
Ve sloupcích budou jednotlivé role a v řádcích uživatelé, kteří budou mít zašktrnuté své role.

**Comment by jan-stanek** [comment]
Ještě než to začnu upravovat, je tím myšleno něco takového? 
[UsersList.xlsx](https://github.com/skaut/SRS/files/551884/UsersList.xlsx)

Jaké všechny role se tam mají vypsat? Mají se vypsat i uživatelé, kteří nejsou schváleni?

Přidal jsem to do možností pod tabulku, jak je hromadný tisk dokladů apod. - vyexportují se zaškrtnutí uživatelé. Jak tuto možnost nazvat "Vyexportovat seznam účastníků pro vstupenky"?

**Comment by DeetsCZ** [comment]
Soubor nechám schválit od Čonkina. 
Možnost bych nazvala "Vyexportovat účástníky a role", ať to máme trochu víc univerzální.

**Comment by DeetsCZ** [comment]
Po potvrzení exportu se zobrazí chyba:
![snimek obrazovky 2016-10-31 v 20 48 34](https://cloud.githubusercontent.com/assets/19816092/19869190/8bfceb58-9fab-11e6-8b67-ecf866a88257.png)

**Comment by jan-stanek** [comment]
Zaúpomněl jsem, že je třeba zaregistrovat službu - do config.neon dopsat:
`		excelExporter: \SRS\Model\Excel\ExcelExporter`

Někam sem:
```
		printer: \SRS\Model\Printer(@database)
		excelExporter: \SRS\Model\Excel\ExcelExporter
		authenticator: \SRS\Model\Authenticator(@database, @skautIS)
```

Ještě je tam také nová knihovna, tak možná bude potřeba `composer update`

**Comment by DeetsCZ** [comment]
Export vypadá dobře, jen počkám na potvrzení od Čonkina..

**Comment by DeetsCZ** [comment]
Přidávám nové zadání od Čonkina:
Potřebovali bychom proto ze systému vyexportovat jednu tabulku, která bude obsahovat sloupečky:

    variabilní symbol (z uživatele)
    jméno (z uživatele)
    příjmení (z uživatele)
    polibek (příznak Y/N podle toho, jestli má danou roli)
    taneční večer (příznak Y/N podle toho, jestli má danou roli)
    filmová sobota (příznak Y/N podle toho, jestli má danou roli)
    nedělní snídaně (příznak Y/N podle toho, jestli má danou roli)
    mhd (příznak Y/N podle toho, jestli má danou roli)
    1. sekce název přednášky
    1. sekce číslo místnosti
    2. sekce název přednášky
    2. sekce číslo místnosti
    3. sekce název přednášky
    3. sekce číslo místnosti

**Comment by DeetsCZ** [comment]
Nahrála jsem aktualizaci na web miquik, ale po vybrání všech uživatelů, se export nevytvořil. Zkoušela jsem vybrat menší počet účastníků, ale další pokus již končí na chybě:
![snimek obrazovky 2016-11-26 v 14 43 13](https://cloud.githubusercontent.com/assets/19816092/20640724/e3c20806-b3e6-11e6-8af6-77488f3b9f93.png)

Testovala jsem i na textweb, kde se na malém počtu lidí export vytvořil v pořádku.

**Comment by jan-stanek** [comment]
Vypadá to spíš na problém s knihovnou - nefunguje ani export harmonogramu.

Můžeš mi prosím poslat nějaký log z www/log/?

**Comment by DeetsCZ** [comment]
Poslala jsem ti log na e-mail.

**Comment by jan-stanek** [comment]
Děkuju, vypadá to jako by nebyla service v config.neon, byl tam přidán te řádek?

**Comment by DeetsCZ** [comment]
Řádek jsem doplnila, ale export se stejně nevytvořil a zobrazila se prázdná stránka, při malém počtu, při velkém se nestalo nic.
![snimek obrazovky 2016-11-26 v 15 40 14](https://cloud.githubusercontent.com/assets/19816092/20641021/b8ca363e-b3ee-11e6-9280-6bdc5dfe697f.png)

**Comment by jan-stanek** [comment]
Nevytvořil se nějaký nový log?

**Comment by DeetsCZ** [comment]
ted jsem jeste aktualizovala composer a pro "malo" uzivatelu se export vytvori, ale pro vsechny se nestane nic..

**Comment by DeetsCZ** [comment]
Log jsem ti poslala na e-mail...

**Comment by jan-stanek** [comment]
Problém je s odesláním formuláře (zaškrtávacích políček) - odešle se jen prvních 1000 polí, ostatní se ignorují.

**Comment by jan-stanek** [comment]
Omezené je to nastavením serveru.

Ono by bylo lepší mít zvlášť operace, které mají pracovat s označenými záznamy (zaplacení apod.) a se všemi záznamy (exporty), aby se u nich neodesílaly id všech záznamů.

Teď mě napadají 2 možnosti - dát limit na stránku 500 a vyexportovat po částech. Nastavit u této operace, aby exportovala všechny a ne jen označené (nebude to ale odpovídat popisu).

**Comment by jan-stanek** [comment]
Při aktualizaci na Nette 2.4 bude stejně potřeba použít jinou komponentu na tabulky, NiftyGrid není s novou verzí kompatibilní.

**Comment by jan-stanek** [comment]
Podle lebeda.skauting.cz by max_input_vars měl být nastaven na 4096, ne 1000, tak nevím čím to je

**Comment by DeetsCZ** [comment]
Export všichni není dobré řešení, protože se vstupenky budou tisknout pouze pro některé role. Pro 100 uživatelů se export vytvoří bez problému. Mohli bychom vyzkoušet export pro 500 uživatelů (možná 1000 jestli to projde) a pro tento rok to bude muset stačit. Po aktualizaci nette budeme na příští rok hledat lepší řešení..

**Comment by jan-stanek** [comment]
projde něco málo pod 1000, protože se odesílají ještě další parametry, upravím tedy na 500

**Comment by DeetsCZ** [comment]
Po uploadu na web jsem chtěla otestovat, ale po potvrzení exportu se zobrazí prázdná stránka:
![snimek obrazovky 2016-11-29 v 21 53 07](https://cloud.githubusercontent.com/assets/19816092/20728522/6b58bf28-b67e-11e6-8fac-ffe31d885d50.png)

**Comment by jan-stanek** [comment]
Pro 200 to funguje, zkusím zjistit, čím by to mohlo být.

**Comment by DeetsCZ** [comment]
Tak po 200 funguje po 500 nefunguje..

**Comment by jan-stanek** [comment]
Vypadá to na problém s redirectem, asi moc dlouhá url, ve které jsou všechna id. Není k tomu něco v logu?

**Comment by jan-stanek** [comment]
Apache server má limit pro url 8192 znaků, pro 200 záznamů je to něco přes 3 200, takže pro 500 se limit překročí.

**Comment by jan-stanek** [comment]
Lepší bude ty data přenášet přes session, ale dostal bych se k tomu asi až zítra odpoledne. Stačí to, nebo mám radši zkusit nastavit limit třeba na 400, jestli to ještě projde?

**Comment by DeetsCZ** [comment]
Bude lepší když to bude fungovat správně. Prosím zitra se na to podívej. Děkuji

**Comment by jan-stanek** [comment]
Opraveno

**Comment by DeetsCZ** [comment]
Pro 500 export funguje výborně. Jen mne napadlo, jestli by nebylo nyní možné, že by fungoval i ten export pro 2000 (aby se exportovalo vše)?

**Comment by jan-stanek** [comment]
To způsobuje zase jiný limit, teď by šlo maximálně cca 990.

**Comment by DeetsCZ** [comment]
Tak to pro letošní rok necháme na 500, stejně jsi psal, že budeme muset přejít na jinou komponentu po aktualizaci nette.
Děkuji

**Comment by jan-stanek** [comment]
Už jsem se na jednu díval a neměla by s tím mít problém. [](http://ublaboo.org/datagrid/group-action?groupActionsGrid-per_page=all)
