### ISSUE TITLE
Informace o kapacitě

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#146]
Ve frontend v kalendáři pro přihlašování se zobrazuje kapacita:
![snimek obrazovky 2016-10-23 v 13 23 53](https://cloud.githubusercontent.com/assets/19816092/19625855/62454c70-9924-11e6-842a-5c86aafc97be.png)

Na obrázku ale kapacita: 2/2 neznamená, že program má volnou kapacitu, ale že jsou přihlášení dva uživatelé a je plno, je to matoucí, mělo by to být buď:
kapacita 0/2
nebo
obsazenost 2/2

Prosím o úpravu

**Comment by jan-stanek** [comment]
Nebylo by dobré to rovnou sjednotit úplně všude, včetně zápisu 1 z 10 nebo 1/10?

**Comment by DeetsCZ** [comment]
To by bylo určitě nejlepší..

**Comment by jan-stanek** [comment]
Dáme tam tedy "obsazeno 4/10", případně "Obsazenost: 4/10"?

**Comment by DeetsCZ** [comment]
Obsazenost: 4/10 vypadá dobře a je to tak jasné, děkuji.

**Comment by DeetsCZ** [comment]
Děkuji za zpracování
