### ISSUE TITLE
Úpravy textů

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#165]
1. Zmenšit mezeru za nadpisem u modulu Kapacita semináře
2. Oprava textu " Pro přihlášení na seminář se musíte neprve přihlásit přes skautIS"
3. Ve formuláři registrace změnit text tlačítka "Přihlásit na seminář" na "Registrovat"
4. Úprava souhlas se zpracováním údajů: _Bude doplněno_
5. Sjednotit hlášení po registraci, nechat pouze jedno hlášení: "Registrace odeslána. Pro další informace o stavu registrace, platbě a semináři se musíte znovu přihlásit"
6. Text " Vaše přihláška zatím nebyla potvrzena. " změnit na " Vaše registrace zatím nebyla potvrzena. "

**Comment by jan-stanek** [comment]
1. je problém jen u Miquiku - zkontroloval bych, jestli není za nadpisem vložený enter, případně jestli nebylo upraveno někde v css

**Comment by DeetsCZ** [comment]
1. díky, podívám se na to

**Comment by DeetsCZ** [comment]
1. upraveno

**Comment by jan-stanek** [comment]
upraveno 2, 3, 5, 6

**Comment by DeetsCZ** [comment]
Konečně mám správnou formulaci bodu 4:

Souhlasím se zpracováním mých osobních údajů pro potřeby účasti na této akci v rozsahu a dle pravidel daných přihláškou člena do organizace.
Souhlasím s pořizování foto, audio a video záznamů z akce a souhlasím s jejich využítím pro potřeby Junáka - českého skauta. Tím není dotčeno mé právo pro konkrétní situaci souhlas omezit nebo vyloučit, a to sdělením vedoucímu programu předem.
Osobní údaje jsou zpracovávány v souladu se zákonem č. 101/2000 Sb. na ochranu osobních údajů.

**Comment by jan-stanek** [comment]
Jak by to mělo vypadat
- celé u jednoho checkboxu,
- checkbox pro každé "souhlasím",
- nebo něco jako "souhlasím s podmínkami", kde "podmínkami" by byl odkaz, který by otevřel dialog s celým textem?

**Comment by DeetsCZ** [comment]
Probírali jsme s Jerrym, jakým způsobem nejlépe souhlas vyřešit. 
Prosím pro celý souhlas použít jeden checkbox a pokud je to možné do administrace do nastavení do sekce Přihláška přidat textové pole, kde souhlas předvyplněn a bude možné ho upravit.

Děkuji

**Comment by jan-stanek** [comment]
```INSERT INTO `settings` (`item`, `value`) VALUES ('application_agreement', 'Souhlasím se zpracováním mých osobních údajů pro potřeby účasti na této akci v rozsahu a dle pravidel daných přihláškou člena do organizace. Souhlasím s pořizování foto, audio a video záznamů z akce a souhlasím s jejich využítím pro potřeby Junáka - českého skauta. Tím není dotčeno mé právo pro konkrétní situaci souhlas omezit nebo vyloučit, a to sdělením vedoucímu programu předem. Osobní údaje jsou zpracovávány v souladu se zákonem č. 101/2000 Sb. na ochranu osobních údajů.');```

**Comment by DeetsCZ** [comment]
Děkuji
