### ISSUE TITLE
Jazykový soubor pro Miquik

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#166]
1. Upravit text "Pro přihlášení na seminář se musíte nejprve přihlásit přes skautIS" na " Pro registraci na Miquik se musíte nejprve přihlásit přes skautIS"
2. "Přihlášen jako: Deets (v roli Administrátor) Odhlásit Administrace", skrýt text v závorce "(v roli Administrátor)"
3. Ve formuláři registrace změnit "Přihlásit jako" na "Registrovat na"
4. Upravit text "K roli Polibek Múzy / Komponovaný večer musíte mít vybrané role: Mikulášský seminář." na "K akci Polibek Múzy / Komponovaný večer musíte mít vybranou akci: Mikulášský seminář."
5. "Na seminář jste se již přihlásili jako Mikulášský seminář, Polibek Múzy / Komponovaný večer" změnit na "Jste registrováni na Mikulášský seminář, Polibek Múzy / Komponovaný večer "
6. Za text " Vaše registrace zatím nebyla potvrzena." přidat "Pro potvrzení registrace je třeba včas uhradit registrační poplatek dle údajů, které naleznete v uživatelském profilu"
7. V profilu nahradit nadpis oddělení "Seminář" na "Miquik"
8. V profilu změnit text "Účast na semináři    Vaše přihláška zatím nebyla schválena" na "Účast na Miquiku:    Vaše registrace zatím nebyla potvrzena"
9. V profilu změnit text "Cena semináře" změnit na "registrační poplatek"
10. Text "Vaše role nemá právo zapisovat si programy" změnit na "Programy lze zapisovat až po potvrzení registrace".
11. Upravit text "Vaše přihláška byla již potvrzena" na "Vaše registrace byla již potvrzena"

**Comment by jan-stanek** [comment]
2. nejde vyřešit jazykovým souborem - přidal bych do konfigurace možnost "Zobrazovat role přihlášeného uživatele"

**Comment by jan-stanek** [comment]
Lokalizační soubor pro Miquik: 
[front.cs_CZ.neon.txt](https://github.com/skaut/SRS/files/555952/front.cs_CZ.neon.txt) (je třeba odstranit příponu ".txt" [.neon vadí githubu] a nahradit jím soubor v app/lang)

**Comment by jan-stanek** [comment]
Do config.neon je třeba přidat:
```
	translation:
		default: cs
```

Třeba sem:
```
	doctrine:
		connection: %database%
		console: true
		proxy:
			namespace: SRS\Model\Proxies
			autogenerate: true
			dir: %tempDir%/proxies

	**translation:
		default: cs**
		
	migrations:
		connection: @doctrine.connection
		namespace: SRS
```

**Comment by jan-stanek** [comment]
Přibyla tam také další závislost v `composer.json`, možná bude třeba ručně spustit `composer update`

**Comment by jan-stanek** [comment]
Úprava db:
```
INSERT INTO `Settings` (`id`, `item`, `value`, `description`) VALUES (NULL, 'display_users_roles', '1', 'Zobrazovat uživatelské role?');
```

**Comment by DeetsCZ** [comment]
Databáze upravena

**Comment by DeetsCZ** [comment]
Děkuji za úpravy, jazykový soubor funguje bez problému.

**Comment by jan-stanek** [comment]
Zatím jsou tam jen ty texty pro Miquik, nepodařilo se mi to v nette 2.0 úplně rozchodit, až bude hotovo všechno k miquiku, tak bych jestě zkusil tu aktualizaci...

**Comment by DeetsCZ** [comment]
Prosím doplnit do jazykového souboru miquiku:
1. nahradit "Role byly upraveny.." za "Akce byly upraveny.."
![image](https://cloud.githubusercontent.com/assets/19816092/19804580/7d5075c8-9d0f-11e6-8d59-4be4e7ec74c6.png)
2. nahradit "Není možné kombinovat roli..." za "Není možné kombinovat akci..."
![image 1](https://cloud.githubusercontent.com/assets/19816092/19804581/7f55099c-9d0f-11e6-878a-c286cf71dfd8.png)

**Comment by DeetsCZ** [comment]
Zaměnit text "Vaše registrace byla již potvrzena" za "Vaše přihláška byla přijata, zkontrolujte stav své platby ve vašem profilu."

**Comment by jan-stanek** [comment]
[front.cs_CZ.neon.txt](https://github.com/skaut/SRS/files/558705/front.cs_CZ.neon.txt)

**Comment by DeetsCZ** [comment]
Děkuji
