### ISSUE TITLE
Chyba: duplicitní VS

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#168]
V systému je možné zadat duplicitní VS, pokud se přihlásí druhý uživatel se stejným datem narození, potom se správně přičte 1, pokud se přihlásí další uživatel se stejným datem narození, potom se k jeho VS opět přičte 1, ale již se nekontroluje další duplicita. 
Ideální by bylo přidat do kontroly cyklus, který bude stále procházet VS a pokud nalezne duplicitu přičte 1 a poté bude dále probíhat a zastaví se až ve chvíli, kdy projde všechna data a nebude nutná změna.
![snimek obrazovky 2016-10-26 v 22 31 20](https://cloud.githubusercontent.com/assets/19816092/19744162/91982146-9bcc-11e6-9f55-e1772cec851d.png)

**Comment by jan-stanek** [comment]
Kontrola v cyklu probíhá, problém byl s počátečními nulami, které se při převodu na číslo odstranily a docházelo ke špatnému porovnávání.

**Comment by jan-stanek** [comment]
Nemám povolit předvolbu dlouhou 0-2 číslice místo 2?

**Comment by jan-stanek** [comment]
Pak by ale nesměla začínat nulou.

**Comment by DeetsCZ** [comment]
Předpokládám, že předčíslí je tam například kvůli odlišení roku akce, to by tedy asi mělo zůstat..

**Comment by DeetsCZ** [comment]
Děkuji
