### ISSUE TITLE
Povolit zápis programu po zaplacení

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#174]
V konfiguraci přidat volbu "Povolit zápis programu až po uhrazení poplatku".
Při zaškrtnutí volby budou moct uživatelé zapisovat se na programy až po vyplnění data platby.

**Comment by jan-stanek** [comment]
`INSERT INTO `Settings` (`id`, `item`, `value`, `description`) VALUES (NULL, 'log_in_programs_after_payment', '1', 'Lze se přihlašovat na programy až po zaplacení?');`

**Comment by DeetsCZ** [comment]
Databáze upravena

**Comment by DeetsCZ** [comment]
Děkuji za zpracování
