### ISSUE TITLE
Chyba: neaktualizované displayName

### ISSUE THREAD

**Issue by jan-stanek** [skaut/SRS#179]

**Comment by jan-stanek** [comment]
Opravena aktualizace jména ve formátu Příjmení Jméno (Přezdívka) při registraci. Z databáze jsem tuto položku neodstraňoval, pokud se jen generuje, není podle ní možné vyhledávat a řadit v tabulce.

Stávající údaje ale zůstanou beze změny - je nutné to u Miquku nějak řešit - vyhledává se tam podle jména v evidenci uživatelů? Dalo by se to vyřešit pomocí SQL.

**Comment by DeetsCZ** [comment]
Děkuji za opravu.
