### ISSUE TITLE
Kontrola zadaných údajů

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#182]
Prosím o přidání kontroly zadaných údajů:
1. kontrola formátu ulice a číslo popisné: ulice plus číslo
2. kontrola formátu pčs: pouze 5 číslic

**Comment by jan-stanek** [comment]
PSČ vezme XXX XX i XXXXX (stejně jako skautIS)

**Comment by DeetsCZ** [comment]
vyzkoušeno, děkuji
