### ISSUE TITLE
Chyba: chyba po uploadu

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#19]
Po posledním uploadu web srs.skauting.cz vypisuje chybu:
![snimek obrazovky 2016-08-25 v 13 37 46](https://cloud.githubusercontent.com/assets/19816092/17967719/46f6e0d4-6ac9-11e6-8c9f-5b3d3fddea0b.png)

**Comment by jan-stanek** [comment]
Na jaké stránce dochází k chybě?

**Comment by DeetsCZ** [comment]
Vyřešeno..
