### ISSUE TITLE
Chyba: nejde zobrazit profil

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#190]
Po posledním uploadu nefunguje odkaz na profil ve frontpage:
Na testweb.skauting.cz:
![snimek obrazovky 2016-12-09 v 22 16 08](https://cloud.githubusercontent.com/assets/19816092/21065025/89675208-be5e-11e6-8880-772eb224415b.png)

Na srs.skauting.cz:
zde se nestane nic a odkaz pod jménem je: "https://srs.skauting.cz/#" místo "http://srs.skauting.cz/front.profile/"

**Comment by jan-stanek** [comment]
Vrátil jsem zpátky route `$container->router[] = new Route('<presenter>/<action>[/<id>]', 'Front:Homepage:default');` a zdá se, že to funguje. Byla odstraněna kvůli nějakému problému?

**Comment by DeetsCZ** [comment]
Děkuji
