### ISSUE TITLE
Přepnutí na ostrý skautIS

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#192]
Prosím v systému o změnu odkazu na ostrý skautIS místo odkazu na testovací skautIS

**Comment by jan-stanek** [comment]
změna se teď řeší v config.local.neon - přepíše se `test: true` na `test: false`

**Comment by DeetsCZ** [comment]
Přepnutí je nyní vyřešeno, ale do budoucna by to asi chtělo vymyslet jednodušší systém zadání údajů, protože se zásahem do souboru budou mít nezkušení uživatelé velký problém..
