### ISSUE TITLE
Úprava bloku Program semináře

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#193]
Pokud není vybrát žádný programový blok, potom by se na stránce měl zobrazovat jednoduchý přehled všech bloků: kategorie, název bloku, lektor.
Ideálně tak, aby kategorie a název bloku byly odkazy: 
1. kliknutí na název se zobrazí detail bloku
2. kliknutím na kategorii se vlevo rozbalí daná kategorie a v hlavní části se zobrazí přehled bloků ve vybrané kategorii

![snimek obrazovky 2016-12-19 v 13 10 14](https://cloud.githubusercontent.com/assets/19816092/21312468/839e0cf0-c5ec-11e6-97d9-b9e184e0b95d.png)

**Comment by jan-stanek** [comment]
Zatím není zapracovaná 2
- muselo by se asi řešit přes ajax
- přijde mi, že to nemá moc význam - zobrazily by se tam ty samé údaje jako na boku, nebo by tam mělo být něco víc?

**Comment by DeetsCZ** [comment]
Nynější řešení je podle mne dostatečné. Necháme to, tak jak to je nyní. Děkuji

**Comment by DeetsCZ** [comment]
Nyní uzavírám. Děkuji
