### ISSUE TITLE
Chyba: nefukční malé menu

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#196]
Pokud se stránka administrace zmenší, potom se menu stáhne, ale také v tu chvíli přestane fungovat a není možné ho rozkliknout:
![snimek obrazovky 2016-12-21 v 20 53 29](https://cloud.githubusercontent.com/assets/19816092/21404093/dfb1e186-c7bf-11e6-9ab9-19379ffac2ee.png)

**Comment by jan-stanek** [comment]
- [ ]

**Comment by DeetsCZ** [comment]
Děkuji
