### ISSUE TITLE
Databáze místností

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#2]
V administraci přidejte do menu "Program semináře" položku "Místnosti". Zde bude administrátor vytvářet seznam místností. 
Při zadávání programového bloku, přejmenujte položku "Lokalita" na "Místnost" a pro výběr přidejte selectbox s vytvořeným seznamem místností.

**Comment by jan-stanek** [comment]
Oprávnění na editaci místností by mělo být nějak takhle?
- Vytvářet místnosti smí lektoři a administrátoři.
- Administráži mohou upravovat a mazat všechny místnosti. Lektoři smí mazat a upravovat jen místnosti, které nejsou použity u jiných bloků než u jejich.

**Comment by jan-stanek** [comment]
úprava stávající databáze:

ALTER TABLE `block` ADD `room_id` INT(11) NULL AFTER `location`;
CREATE TABLE `srs`.`room` ( `id` INT(11) NOT NULL AUTO_INCREMENT , `name` VARCHAR(255) COLLATE utf8_unicode_ci NOT NULL , PRIMARY KEY (`id`), UNIQUE (`name`)) ENGINE = InnoDB;
INSERT INTO `room` (`name`) SELECT `location` FROM `block` WHERE `location` <> "";
UPDATE `block` b, (SELECT * FROM `room`) r SET b.room_id = r.id WHERE b.location = r.name;
ALTER TABLE `block` DROP `location`

**Comment by DeetsCZ** [comment]
Ideální bude řešení, které jsi psal:
Přidat oprávnění "Spravovat místnosti" a jako výchozí nastavit pro administrátory a organizátory.

**Comment by DeetsCZ** [comment]
Databáze upravena..

**Comment by DeetsCZ** [comment]
Po úpravě databáze web vypisuje v administraci v programu (http://srs.skauting.cz/admin/program/) chybu:
![snimek obrazovky 2016-08-29 v 13 56 45](https://cloud.githubusercontent.com/assets/19816092/18050794/0025afa2-6df1-11e6-8a8f-93ae82cf2a01.png)

**Comment by jan-stanek** [comment]
Úprava ještě není zmergovaná do hlavní větve, doplním nové oprávnění a nahraju.

**Comment by jan-stanek** [comment]
Nahráno na git.

Ještě je potřeba provést:
```
INSERT INTO `resource` (`id`, `name`) VALUES (NULL, 'Místnosti');
INSERT INTO `permission` (`id`, `resource_id`, `name`) VALUES (NULL, '8', 'Spravovat');

ALTER TABLE `block` ADD CONSTRAINT `FK_42DAB82654177093` FOREIGN KEY (`room_id`) REFERENCES `srs`.`room`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;
```

**Comment by DeetsCZ** [comment]
Databáze upravena..

**Comment by DeetsCZ** [comment]
Odkaz "Program semináře" (http://srs.skauting.cz/admin/program/) v administraci vyhazuje chybu:
![snimek obrazovky 2016-08-29 v 21 36 43](https://cloud.githubusercontent.com/assets/19816092/18064754/16a216d6-6e31-11e6-9b7e-a8f416c095cb.png)

**Comment by jan-stanek** [comment]
Vyřešeno promazáním cache

**Comment by DeetsCZ** [comment]
Odkaz pro program je nyní dostupný, ale odkaz na místnosti (http://srs.skauting.cz/admin/program/room/) vyhazuje chybu:
![snimek obrazovky 2016-08-29 v 22 24 04](https://cloud.githubusercontent.com/assets/19816092/18066168/7872bec8-6e37-11e6-96a1-66bee2d7afc5.png)

**Comment by jan-stanek** [comment]
tabulka "room" přejmenována na "Room"

**Comment by DeetsCZ** [comment]
Nyní to vypadá v pořádku..

**Comment by DeetsCZ** [comment]
Ve frontendu, kde si uživatel vybírá program se v náhledu zobrazuje, v jaké místnosti program probíhá:
![snimek obrazovky 2016-09-04 v 13 58 49](https://cloud.githubusercontent.com/assets/19816092/18230849/f6cb3f7e-72a7-11e6-8c46-e204218f0dcd.png)
, ale při rozkliknutí se zobrazuje místnost: nezadána:
![snimek obrazovky 2016-09-04 v 13 58 59](https://cloud.githubusercontent.com/assets/19816092/18230851/fb2f03ac-72a7-11e6-9a35-a7b336c24a49.png)

Prosím o úpravu, aby se i v detailu zobrazovala zadaná místnost. Děkuji

**Comment by DeetsCZ** [comment]
Děkuji za zpracování.
