### ISSUE TITLE
Sjednocení detail a upravit v editaci uživatelů

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#205]
Prosím o sjednocení detailu a úprav uživatele, viz emailová komunikace. 
Předpokládám, že zadání bude ještě potřeba dopilovat, ale cílem je mít pouze jeden formulář s detailem uživatele, který je možné editovat (případně editovat "v blocích", jako je to u nastevení).

**Comment by jan-stanek** [comment]
Co tam potom ještě přidat validaci, že pokud je vybrána platební metoda, musí se vyplnit datum platby a naopak?

**Comment by jan-stanek** [comment]
Validaci jsem zatím nepřidával, nevím jestli je vždy nutné mít pole vyplněné zároveň.

**Comment by DeetsCZ** [comment]
Děkuji, vypadá to dobře :)
