### ISSUE TITLE
Chyba: zdvojení programu

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#221]
Pokud přidám program do harmonogramu přetažení do kalendáře a následně program posunu, kliknu jinam a vrátím se, potom jsou v kalendáři programy dva: posunutý i neposunutý.
![snimek obrazovky 2017-02-27 v 21 18 44](https://cloud.githubusercontent.com/assets/19816092/23378068/5c35e8f4-fd32-11e6-9670-e9ccfb321d30.png)

Program jsem vložila na 7:15 a posunula na 7:00 a nyní jsou v kalendáři místo jednoho dva..

Prosím o opravu

**Comment by jan-stanek** [comment]
Opraveno, doufám, že se tím nerozbilo něco jiného...

Ještě jsem opravil kontrolu kolizí - když mezi programy nebyla přestávka, uživatel si nemohl zapsat následující ani předchozí.

**Comment by DeetsCZ** [comment]
Děkuji za opravu
