### ISSUE TITLE
Sjednotit administraci uživatelů

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#23]
V administraci sjednotit tabulky pro výběr role s evidencí účastníků.
Odkaz "Evidence účastníků" přejmenovat na "Evidence uživatelů" a v této tabulce umožnit výběr "Role" a "Schválený". 
Odkaz "Práva a role" zůstene, ale bude zde jen "Role".

**Comment by jan-stanek** [comment]
Sjednocením dojde k převedení oprávnění na schvalování a změnu rolí uživatelů z "Spravovat ACL" na "Spravovat Evidence"

**Comment by DeetsCZ** [comment]
Bylo by lepší nazvat oprávnění "Správa uživatelů". 
Pokud nyní "Spravovat ACL" není potřeba, prosím o odstranění oprávnění, aby to nebylo matoucí..

**Comment by jan-stanek** [comment]
ACL zůstává pro správu rolí, úpravu oprávnění

**Comment by DeetsCZ** [comment]
Prosím tedy upravit i "ACL" na "Spravovat práva a role", aby to bylo jasnější. Děkuji

**Comment by jan-stanek** [comment]
Ještě je třeba provést:
```
UPDATE `Resource` SET `name` = 'Práva a role' WHERE `resource`.`id` = 3;
UPDATE `Resource` SET `name` = 'Uživatelé' WHERE `resource`.`id` = 6;
```

**Comment by DeetsCZ** [comment]
Databáze upravena

**Comment by DeetsCZ** [comment]
Děkuji za zpracování.

Ještě prosím o přejmenování "Evidence účastníků" na "Evidence uživatelů". Děkuji

**Comment by DeetsCZ** [comment]
Děkuji za zpracování..
