### ISSUE TITLE
Více rolí pro jednoho uživatele

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#24]
Umožnit výběr více rolí pro jednoho uživatele. 

Možné konflikty: 

Zobrazit v přehledu uživatelů: 
- pokud má jedna z rolí staveno zobrazování, potom se v seznamu uživatel zobrazí

Platí za účast?: 
- pokud má jedna role nastaveno, že neplatí, potom dotyčný za účast neplatí

Práva:
- platí vždy ty vyšší
- například pokud má jedna role Spravovat vlastní programy a druhá Spravovat všechny programy, potom má uživatel právo Spravovat všechny programy

**Comment by jan-stanek** [comment]
Úprava databáze:
```
CREATE TABLE `user_role` (`user_id` int(11) NOT NULL, `role_id` int(11) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
ALTER TABLE `user_role` ADD PRIMARY KEY (`user_id`,`role_id`), ADD KEY `IDX_2DE8C6A3A76ED395` (`user_id`), ADD KEY `IDX_2DE8C6A3D60322AC` (`role_id`);
ALTER TABLE `user_role` ADD CONSTRAINT `FK_2DE8C6A3A76ED395` FOREIGN KEY (`user_id`) REFERENCES `User` (`id`) ON DELETE CASCADE, ADD CONSTRAINT `FK_2DE8C6A3D60322AC` FOREIGN KEY (`role_id`) REFERENCES `Role` (`id`) ON DELETE CASCADE;
INSERT INTO `user_role` (`user_id`, `role_id`) SELECT `id`, `role_id` FROM `User`;
ALTER TABLE User DROP FOREIGN KEY FK_2DA17977D60322AC;
ALTER TABLE `User` DROP `role_id `;
```

**Comment by DeetsCZ** [comment]
Databaze upravena..

**Comment by DeetsCZ** [comment]
Zkoušela jsem uživatele přidat do rolí účastník 100 a účastník 200, ale po potvrzení těchto rolí a přihlášení se zobrazila chyba:
![snimek obrazovky 2016-10-11 v 13 09 50](https://cloud.githubusercontent.com/assets/19816092/19268322/2a636b4e-8fb4-11e6-83c8-88afaf02430b.png)

Role mají právo přihlašovat se na programy a přístup na homepage by neměl být problém ani pro nepřihlášeného uživatele..
Prosím o opravu

**Comment by jan-stanek** [comment]
Když se podíváš na oprávnění u stránky, tak tam tyhle role nejsou povolené. Možná to ale dřív fungovalo jinak. Můžu tam přidat, že pokud má přístup role guest, tak mají přístup všichni? Mám pocit, že se ta role ani nijak nepoužívá.

**Comment by DeetsCZ** [comment]
Možná bych pro všechny role v defaultu po vytvoření nastavila stejný přístup na stránky jako role Nepřihlášený..

**Comment by jan-stanek** [comment]
Díval jsem se jak to bylo původně a myslím, že se chování změnit nemělo, udělám to tedy takhle.

**Comment by DeetsCZ** [comment]
Děkuji

**Comment by jan-stanek** [comment]
Když už jsme u toho, jakou máš představu o možnosti "Založit na roli"? Teď to funguje tak, že se akorát nastaví stejná oprávnění.

**Comment by DeetsCZ** [comment]
Asi bych to nazvala "Vychází z role", přijde mi to názornější.. Založená role by potom měla mít stejná oprávnění i nastavení jako role, ze které vychází.

**Comment by DeetsCZ** [comment]
Děkuji za úpravy
