### ISSUE TITLE
Omezit délku textu v záhlaví

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#240]
Prosím o omezení délky textu v záhlaví tabulky Uživatelé, ideálně na 3 slova a nakonec přidat "...":
Zde příklad z helpdesku
![snimek obrazovky 2017-03-22 v 10 19 32](https://cloud.githubusercontent.com/assets/19816092/24190563/49c4c690-0ee9-11e7-9dc2-92dd7f6f144c.png)

Děkuji

**Comment by jan-stanek** [comment]
Omezeno na 35 znaků, to by mělo +- odpovídat 3 řádkům.

**Comment by DeetsCZ** [comment]
Zkoušela jsem to a podle mne to není úplně ono.. Prosím o zkrácení na 20 znaků. To by mělo stačit. 
Potom prosím i o zkrácení odpovědi:
![snimek obrazovky 2017-03-23 v 14 19 40](https://cloud.githubusercontent.com/assets/19816092/24249580/1a0972a2-0fd4-11e7-9ee7-f19349f572f1.png)
Mohli bychom to vyzkoušet také na 20 znaků, celá odpověď je vidět v detailu uživatele a to by mělo stačit..

Děkuji

**Comment by jan-stanek** [comment]
Teď koukám, že jsem si to špatně přečetl a měly to být 3 slova, ne řádky, mám to tedy udělat na 3 slova nebo těch 20 znaků?

**Comment by DeetsCZ** [comment]
No já to špatně napsala, měly to být 3 řádky, takže jsi to četl vlastně dobře.. Zkusíme to na těch 20 znaků.. 
Děkuji

**Comment by DeetsCZ** [comment]
Nyní to vypadá mnohem lépe, děkuji.

Jen jak na to ještě koukám, tak se mi zdá, že je tam zbytečně velké spodní odsazení.. Bylo by možné ho zmenšit, tak aby bylo stejné odsazení nahoře i dole?
![snimek obrazovky 2017-03-23 v 19 30 24](https://cloud.githubusercontent.com/assets/19816092/24264028/5df07198-0fff-11e7-9a6b-66c2dcb32f3c.png)

**Comment by jan-stanek** [comment]
V tom odsazení se při najetí ukáže šipečka na schování sloupce. Asi se s tím nedá nic moc dělat, zaleží jak se to roztáhne podle nejdelšího slova a jestli je poslední slovo kratší.

**Comment by DeetsCZ** [comment]
To odsazení opravdu dělá šipka pro skrytí sloupce.. 

Děkuji za úpravy
