### ISSUE TITLE
Chyba: členství

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#248]
K problematice vyhodnocování členství přikládám vyjádření Jerryho:

Správné vyhodnocení členství (SRS): 
* zřejmě to teď nefunguje úplně správně, protože členství nikdy nemůže být pod ústředím (č. 1) ani v okresech a krajích (třímístná čísla jednotek, např. 116, 110, 510 apod.)
* členství se musí vyhodnocovat dle platných! záznamů v tabulce členství Membership
* u členství nás zajímá jen typ "řádné" a "čestné" (každá osoba má vždy jen jeden typ takového členství); členství typu "hostování" (taková osoba bude mít vždy i řádné/čestné) nebo "nečlen" (taková osoba vůbec není členem) nás nezajímá
V příloze posílám nějaký techničtější popis k rolím a členstvím a získáváním ze skautISu. Pro tuto problematiku jsou podstatné hlavně kapitoly 2), případně 3). Tak snad to při hledání a opravení té chyby pomůže 
[Jak získat informace o typu uživatele ze skautISu.docx](https://github.com/skaut/SRS/files/865844/Jak.ziskat.informace.o.typu.uzivatele.ze.skautISu.docx)

**Comment by jan-stanek** [comment]
Děkuji za popis

**Comment by jan-stanek** [comment]
Snad to bude fungovat i pro čestná členství, nemohu si ho nastavit ani v testovacím skautIS.

Je k tomu potřeba funkce `MembershipAllPerson`, možná nebude u některých AppId povolena.

**Comment by DeetsCZ** [comment]
Čestné členství funguje také. Děkuji
