### ISSUE TITLE
Tisk dokladu

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#25]
V detailu uživatele jsou nyní dvě tlačítka pro tisk, mělo by se zobrazovat pouze jedno podle typu platby:
1. Pokud je vybrána platební metoda "Hotovost", potom zobrazit tlačítko "Vytisknout příjmový doklad"
2. Pokud je vybrána platební metoda "Na účet", potom zobrazit tlačítko "Vytisknout potvrzení o zaplacení na účet"
Toto se musí zohlednit i v hromadných akcích nad evidencí účastníků:
1. Změnit popis z "Vytisknout příjmový doklad" na "Vytisknout doklad o zaplacení" 
2. Podle typu platby vygenerovat do pdf příslušný doklad

Umožnit tisk dokladu až po vyplnění položky "Zaplaceno dne".

Položku "Příjmový doklad vytištěn" vyplnit automaticky po vygenerování dokladu a doplnit datum, kdy byl doklad vytištěn.

Úprava příjmového dokladu:
1. přejmenovat "Firma" na "Dodavatel"
2. odebrat všechny přeškrtané nápisy (Výdajový pokladní doklad, Vyplaceno komu, Vydal a nápis Nehodící se škrtněte)

**Comment by jan-stanek** [comment]
"Doplnit datum, kdy byl doklad vytištěn" je myšleno do databáze, nebo do dokladu za "ze dne"?

**Comment by DeetsCZ** [comment]
Bylo by dobré do dokladu doplnit datum z položky "Zaplaceno dne" a předělat položku "Příjmový doklad vytištěn" z checkboxu na textové pole, kam se automaticky doplní datum, kdy byl vytištěn doklad (export přes tlačítka pro tisk dokladu).

**Comment by jan-stanek** [comment]
ALTER TABLE `User` CHANGE `incomeProofPrinted` `incomeProofPrintedDate` DATE NULL DEFAULT NULL;

**Comment by DeetsCZ** [comment]
První příkaz vyvolal chybu:
![snimek obrazovky 2016-09-01 v 14 23 43](https://cloud.githubusercontent.com/assets/19816092/18167251/d7e4db92-704f-11e6-8677-151f35665bfb.png)

**Comment by jan-stanek** [comment]
Tohle by mělo jít:
```
ALTER TABLE `User` ADD `incomeProofPrintedDate` DATE NULL DEFAULT NULL AFTER `incomeProofPrinted`;
ALTER TABLE `User` DROP `incomeProofPrinted`;
```

**Comment by DeetsCZ** [comment]
Databáze upravena..

**Comment by DeetsCZ** [comment]
Bylo by možné, aby se tlačítka pro tisk měnila ihned po výběru způsobu platby? Nyní se tlačítka aktualizují až po uložení profilu, což by mohl některé uživatele mást. 
Pokud to technicky není možné, potom by bylo dobré doplnit varováním, že se změna projeví až po uložení..

**Comment by DeetsCZ** [comment]
Po posledním uploadu se tlačítko pro tisk dokladu nezobrazuje vůbec..

**Comment by jan-stanek** [comment]
Nezobrazuje se, protože není vyplňeno datum platby

**Comment by jan-stanek** [comment]
Data by se musela s každou změnou metody i datumů uložit do databáze, aby byla vždy aktuální pro tisk.

Mohu přidat upozornění k tlačítku, ale jako lepší řešení mi možná přijde zrušit editaci v detailu - ve zbytku systému se používá pro editaci buď řádková úprava, nebo editace pomocí tlačítka "upravit".

**Comment by jan-stanek** [comment]
Kvůli možnosti přiřazení více rolí bylo přidáno tlačítko "upravit" a v detailu už není možné nic měnit, mělo by to vyřešit i tento problém.

**Comment by DeetsCZ** [comment]
Děkuji za zpracování
