### ISSUE TITLE
Chyba: hromadné nastavení role

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#250]
Hromadné nastavení role nefunguje (chybí menu pro výběr rolí) na prohlížeči 
Chrome:
![snimek obrazovky 2017-03-26 v 13 55 34](https://cloud.githubusercontent.com/assets/19816092/24331023/121a1b78-122c-11e7-9945-ae80cf4fd0a6.png)
Opera:
![snimek obrazovky 2017-03-26 v 14 08 22](https://cloud.githubusercontent.com/assets/19816092/24331103/bd1266e2-122d-11e7-880b-a8aa23086c4c.png)

Na firefox je funkční a IE nemám momentálně možnost otestovat..

**Comment by jan-stanek** [comment]
Problém je v novém release knihovny, bohužel ve starším je zase jiná chyba. Nahlášeno autorům.

**Comment by jan-stanek** [comment]
Jak moc je to prioritní, počkáme na nový release knihovny nebo ji mám nakopírovat do libs a opravit hned?

**Comment by DeetsCZ** [comment]
Jak to vypadá s přiřazováním rolí? Je už nový release knihovny? Díky

**Comment by DeetsCZ** [comment]
Funguje bez problému, děkuji za opravu
