### ISSUE TITLE
přehodit nette-forms-gpspicker do composeru

### ISSUE THREAD

**Issue by sinacek** [skaut/SRS#260]
Soubory uložené v libs https://github.com/skaut/SRS/tree/master/libs/vojtech-dobes/nette-forms-gpspicker by se měli přesunout k ostatním knihovnám do composeru, jestli tam není nějaký speciální důvod pro to, to držet takto. Pak bych cely adresar libs odebrat.

Pro composer je to zde: https://packagist.org/packages/vojtech-dobes/nette-forms-gpspicker

**Comment by jan-stanek** [comment]
Zatím prosím neměnit, verze není kompatibilní s nette 2.4, používá se verze z otevřeného pull requestu.
