### ISSUE TITLE
První a poslední přihlášení

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#27]
V administraci v detailu uživatele do sekce "Údaje o osobě a akci" přidat dvě položky:
1. první přihlášení uživatele
2. poslední přihlášení uživatele

**Comment by jan-stanek** [comment]
```ALTER TABLE `User` ADD `firstLogin` DATETIME NULL DEFAULT NULL AFTER `skautISPersonId`, ADD `lastLogin` DATETIME NULL DEFAULT NULL AFTER `firstLogin`;```

**Comment by DeetsCZ** [comment]
databáze upravena

**Comment by DeetsCZ** [comment]
Děkuji za úpravu
