### ISSUE TITLE
Přidání UserReport do administrace

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#281]
Prosím o přidání kódu:
 "Copy and insert the following code snippet before the closing </body> tag on your website - do this on every page where you wish to activate UserReport.":
<script type="text/javascript">
window._urq = window._urq || [];
_urq.push(['initSite', 'ff3bbb84-740e-49e3-afd9-db722e8047b5']);
(function() {
var ur = document.createElement('script'); ur.type = 'text/javascript'; ur.async = true;
ur.src = ('https:' == document.location.protocol ? 'https://cdn.userreport.com/userreport.js' : 'http://cdn.userreport.com/userreport.js');
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ur, s);
})();
</script>

**Comment by jan-stanek** [comment]
Poloha není úplně ideální třeba v tabulce uživatelů, ale nevím jak moc to jde nastavovat. Pokud jen pravá/levá apod., tak je to ok.

**Comment by DeetsCZ** [comment]
S tou polohou toho asi moc nevymyslíme, ale přijde mi to v pohodě. Děkuji
