### ISSUE TITLE
Dlaždice na první straně administrace

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#282]
Prosím o úpravu první strany administrace:
![snimek obrazovky 2017-04-27 v 13 18 43](https://cloud.githubusercontent.com/assets/19816092/25481135/1824d560-2b4c-11e7-84a4-e8473abb51e2.png)

Jednotlivé dlaždice by měly obsahovat odkazy do druhé úrovně menu a měly by být seskupeny do rámečků (fieldset) s nadpisem podle menu první úrovně.

**Comment by DeetsCZ** [comment]
Bylo by možné, aby se dlaždice přeskupily při zmenšení okna? Bylo by to hezké, ale není to nutné, pokud by funkce byla náročnější, potom to není potřeba zpracovávat.

**Comment by DeetsCZ** [comment]
Dále mne napadá, že by bylo dobré, aby se dlaždice vešly na jednu stranu, vzhledem k počtu dlaždic by mělo stačit upravit odsazení jednotlivých dlaždic, asi takto:
![snimek obrazovky 2017-10-02 v 12 52 22](https://user-images.githubusercontent.com/19816092/31074434-f83881e2-a770-11e7-8f8b-c34ab6846000.png)

**Comment by jan-stanek** [comment]
Přeskupení by šlo jednoduše, jen moc nevím, jak to zlepšit. Myslíš třeba jich dát méně vedle sebe při menším okně?

Odsazení zkusím, mně se tam vešly :-)

**Comment by DeetsCZ** [comment]
Moje představa je, pokud zúžím okno, potom se dlaždice, které se do okna nevejdou přesunou na další řádek, tak aby se "neschovávaly" za okraj:
![snimek obrazovky 2017-10-02 v 13 10 26](https://user-images.githubusercontent.com/19816092/31074893-11278a8e-a773-11e7-8442-104b57ad7ac5.png)

Já mám notebook 15,4 (1440x900) a končím v půlce mailingu :D :
![snimek obrazovky 2017-10-02 v 13 07 13](https://user-images.githubusercontent.com/19816092/31074931-3f0c1f00-a773-11e7-8307-33581fde3a26.png)

**Comment by jan-stanek** [comment]
Tak to už je moc velké zúžení, to už se schovává i horní menu. Celá stránka má minimální šířku kvůli menu, aby se tam vešly všechny položky.

**Comment by jan-stanek** [comment]
Co takhle?
![screen](https://user-images.githubusercontent.com/11959693/31096239-c506b30c-a7bb-11e7-9586-ffc7c91dc0de.png)

Kdyby nebyly "automatické e-maily" a "programové bloky", tak mohou být užší a i by to vypadalo líp.

**Comment by DeetsCZ** [comment]
Pravda s tím menu, navrhuji tedy pouze zmenšit odsazení a ostatní nechat, tak jak je.
Děkuji

**Comment by DeetsCZ** [comment]
Děkuji
