### ISSUE TITLE
Štítky u dokumentů

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#285]
Prosím o úpravu štítků:

- [x] přejmenovat na kategorie
- [x] přidat možnost nastavit, kdo může dokument v kategorii vidět

**Comment by jan-stanek** [comment]
@DeetsCZ má potom smysl, aby se u obsahu s dokumenty dalo nastavovat, jaké štítky se v něm mají zobrazovat, když to bude podle rolí?

**Comment by DeetsCZ** [comment]
@jan-stanek nevím jestli by tady nebylo dobré, kdyby se pro webový obsah daly vybírat nejen celé kategorie, ale i jednotlivé soubory. To je na zvážení..

Zkoušela jsem přidat dokumenty, které byly omezené pouze pro určitou roli. Pokud mám tuto roli, tak je zobrazení v pořádku:
<img width="571" alt="snimek obrazovky 2018-03-01 v 10 56 41" src="https://user-images.githubusercontent.com/19816092/36838562-ced2ca84-1d3f-11e8-8ec0-192dfb8a4900.png">
Pokud ale nemám oprávněnou roli, potom se zobrazí pouze nadpis webového modulu a to může být hodně matoucí:
<img width="711" alt="snimek obrazovky 2018-03-01 v 10 56 24" src="https://user-images.githubusercontent.com/19816092/36838628-f942686a-1d3f-11e8-9812-e3ddbe5b9587.png">
Bylo by možné skrýt i ten nadpis, pokud role nemá práva zobrazit kategorii?

**Comment by jan-stanek** [comment]
Potom bych asi zrušil kategorie a vybíral to přímo u jednotlivých souborů, ne?

Co tam dát jen hlášku, že není žádný soubor ke stažení? Asi se to běžně stávat nebude, ne?

**Comment by DeetsCZ** [comment]
Ta hláška by určitě stačila. 
Ty kategorie si zkusím ještě promyslet, asi by se dalo najít i nějaké lepší řešení.

**Comment by DeetsCZ** [comment]
Děkuji
