### ISSUE TITLE
Skautské logo a logo akce

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#286]
Prosím o úpravy:

1. přidat skrytý text "Název akce"
2. v defaultní nastavení přidat do bočního panelu text "Akci pořádá Junák - český skaut" plus skautské logo

**Comment by jan-stanek** [comment]
1. přidán title s názvem semináře jako title k logu
2. text bez nadpisu se zobrazoval špatně, udělal jsem to takto:
![logo](https://user-images.githubusercontent.com/11959693/31044380-90f7f128-a5ce-11e7-927e-6277805c4f73.png)

**Comment by DeetsCZ** [comment]
Bylo by možné vytvořit modul do stránek "Logo skaut", tak aby se dal přidat i později?
Možná bych zkusila u logo dát zarovnání doleva, ten střed vypadá vůči zbytku webu divně..
Děkuji

**Comment by jan-stanek** [comment]
Myslíš i s tím textem, nebo jen samotný obrázek loga? Možná zkusím horizontální variantu a dát ho na celou šířku sloupce, při vložení jako modul obrázek to nešlo.

**Comment by DeetsCZ** [comment]
Ok, zkus a uvidíme, jak to bude vypadat..

**Comment by jan-stanek** [comment]
U stávajících instalací bude potřeba ručně spustit toto:

```CREATE TABLE organizer_content (id INT NOT NULL, organizer VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
ALTER TABLE organizer_content ADD CONSTRAINT FK_B7F48760BF396750 FOREIGN KEY (id) REFERENCES content (id) ON DELETE CASCADE```

**Comment by DeetsCZ** [comment]
Pokud nyní modul přidám, potom se obrázek nezobrazuje:
![snimek obrazovky 2017-10-11 v 22 21 04](https://user-images.githubusercontent.com/19816092/31464772-87bef0ae-aed2-11e7-9396-19e744bb1c1c.png)

Pravděpodobně chybí obrázek loga..

**Comment by DeetsCZ** [comment]
Testováno na srs.skauting.cz:
přidala jsem modul na první a druhou stránku.
Na první je obrázek v pořádku:
![snimek obrazovky 2017-10-19 v 12 54 39](https://user-images.githubusercontent.com/19816092/31767783-c7f125fc-b4cc-11e7-9234-f2e01ceb9558.png)

Na druhé chybí:
![snimek obrazovky 2017-10-19 v 12 54 49](https://user-images.githubusercontent.com/19816092/31767785-cc033630-b4cc-11e7-935c-1de9fb45a181.png)

**Comment by DeetsCZ** [comment]
Děkuji
