### ISSUE TITLE
Harmonogram místnosti

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#288]
Prosím o přidání harmonogramu místnosti.
Harmonogram by se měl zobrazovat na stránce místnosti a mělo by být možné ho vytisknout.
Měla by to být jednoduchá tabulka čas/den s vyplněnými přednáškami.
Děkuji

**Comment by DeetsCZ** [comment]
Export vypadá dobře děkuji.
Prosím o přidání tlačítka ještě do tabulky přehledu místností (ideálně jen ikonka tiskárny). Děkuji

**Comment by jan-stanek** [comment]
Neuděléme to přes hromadné akce? Bylo by to stejné jako u uživatelů a umožnilo by to vytisknout harmonogramy všech místností najednou.

**Comment by DeetsCZ** [comment]
Myslím, že by bylo dobré mít možnost vytisknout vše najendou, ale přidala bych i tu možnost v přehledu programů..

**Comment by DeetsCZ** [comment]
Tak jsem to nyní zkoušela a za mne je to takto ideální...
