### ISSUE TITLE
Úprava variabilního symbolu

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#289]
Prosím o úpravu variabilního symbolu:
1. Je možné zadat 0-4 znaky pro předvolbu.
2. V nastavení v sekci Platba a doklady přidat možnost: 
Generovat variabilní symbol podle: 
a. Data narození
b. Pořadí přihlášky
Děkuji

**Comment by jan-stanek** [comment]
Už jsem to nenašel nikde zadané, ale rovnou upravím, aby se místo datumu prvního přihlášení evidoval čas odeslání přihlášky.

**Comment by DeetsCZ** [comment]
To je určitě dobrý nápad.. Děkuji

**Comment by DeetsCZ** [comment]
Děkuji
