### ISSUE TITLE
Možnost upravit vlastní pole z přihlášky

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#290]
Prosím přidání možnosti, aby si uživatel mohl do určitého data měnit odpovědi zadané v přihlášce.

1. V nastavení přihlášky prosím o přidání volby, do kdy mohou uživatelé odpovědi měnit.
2. Vlastní pole by se měly zobrazovat v profilu uživatele v sekci "Doplňující informace". Po uplynutí data pro změnu by měla pole "zešedivět" a nebude možné je už změnit.

Děkuji

**Comment by DeetsCZ** [comment]
Zkoušela jsem upravit údaje a po uložení se mi zobrazuje chyba: 
![snimek obrazovky 2017-10-04 v 13 23 53](https://user-images.githubusercontent.com/19816092/31173313-59436f50-a907-11e7-91e9-e2ff52e9fe79.png)

**Comment by DeetsCZ** [comment]
Pokud vyprší datum pro změnu, potom správně nejdou pole měnit, ale tlačítko pro změnu je stále aktivní a dokonce po stisknutí uloží změny:
![snimek obrazovky 2017-10-04 v 22 39 37](https://user-images.githubusercontent.com/19816092/31198585-17de444c-a955-11e7-9862-a8de44b27df8.png)

Ideální by bylo, aby tlačítko úplně zmizelo, nebo aby bylo neaktivní.

**Comment by jan-stanek** [comment]
To je správně, jinak by se nedalo měnit pole "O mně"

**Comment by DeetsCZ** [comment]
Pravda, toho jsem si nevšimla. Děkuji
