### ISSUE TITLE
Chyba: duplicitní záznamy v databázi

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#294]
V databázi v tabulce "custom_text_value" a "custom_input_value" se objevují duplicitní záznamy u některých uživatelů:
![snimek obrazovky 2017-05-23 v 23 29 03](https://cloud.githubusercontent.com/assets/19816092/26377926/bcbff656-4012-11e7-8da7-d181ae1cb8f5.png)

**Comment by jan-stanek** [comment]
ošetřeno vytváření nových záznamů při odeslání přihlášky, pokud už existují - nevím jak se to může stát, ale při editaci to ošetřeno bylo a jinde se s tím nepracuje

**Comment by DeetsCZ** [comment]
Při vytváření přihlášky jsem na problém již nenarazila.

Děkuji
