### ISSUE TITLE
Přidání externího lektora

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#298]
V administraci na stránce uživatelů by měl být odkaz “Přidat lektora” pro přidání dalšího uživatele.
 
Ve formuláři se bude zadávat:
**Fotka** (nepovinné) - výběr souboru
**Jméno** (povinné)
**Příjmení** (povinné)
**Přezdívka** (nepovinné)
**Email** (nepovinné)
**Datum narození** (nepovinné)
**Adresa** (nepovinné)
**O mě** (nepovinné)
**Neveřejná poznámka** (nepovinné)
 
Po uložení bude mít uživatel rovnou roli schváleného lektora.
 
Dále se s uživatelem bude pracovat stejně jako kdyby byl načtený přes skautIS, ale nebude možné, aby se k účtu na webu přihlásil (nebude vazba na žádnou reálnou osobu/účet ve skautISu).
V kolonce členství by měl být napsán nečlen. Budeme předpokládat, že člen by se normálně přihlásil přes skautIS a tedy ručně přidaný lektor je nečlen.
 
 
Informace o lektorech na stránce - frontend webu
 
V rámci zadaní bude nutné zpracovat modul s přehledem lektorů do frontpage. Zde bude zobrazen seznam všech lektorů. U každého lektora bude zobrazena fotka (pokud byla zadaná), jméno, příjmení, přezdívka a informace zadané v položce O mě a pokud již byl přiřazen k programu, potom by zde měl být ještě seznam jeho programů s krátkým popisem (“Stručný popis” z programu).

**Comment by jan-stanek** [comment]
Všechny údaje budou později editovatelné? Bude potřeba dodělat formulář, teď jsou tyhle údaje v administraci většinou neměnné.

**Comment by DeetsCZ** [comment]
Bylo by opravdu dobré, kdyby se údaje daly upravit. 
Formulář by mohl být stejný jako ten při přidání a do části osobní údaje v detailu přidaného lektora (u jiného typu ne) by se přidalo tlačítko upravit.

**Comment by jan-stanek** [comment]
Hotova 1. část - externí lektoři, chybí informace o lektorech na webu.

**Comment by DeetsCZ** [comment]
Děkuji za zpracování první části, funguje bez problému.

**Comment by DeetsCZ** [comment]
Dekuji za zpracování
