### ISSUE TITLE
Podakce

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#299]
**Administrace**
- po instalaci se implicitně vytvoří podakce v nastavení Struktura semináře 
    - název bude stejný jako název vytvořené akce : bylo by možné propojit s název, tak aby při změně názvu akce se upravil i název implicitní podakce? A pokud jednou přejmenuji, potom se již název automaticky měnit nebude.
    - tuto podakci nebude možné odstranit
    - mohli bychom doplnit nějakým vysvětlujícím textem 
    - cena bude nastavena na 0
- dále je možné přidat další podakce
    - ideálně přes tlačítko “Přidat podakci”
    - u každé podakce se nastavuje: 
    - **název**: text (povinné)
    - **cena akce**: číslo (nepovinné. pokud se nevyplní, potom je cena 0)
    - **kapacita akce**: číslo (nepovinné)
    - **nelze kombinovat s**: výčet zadaných akce: viz kombinovatelnost rolí
    - **podmíněná registrace s**: výčet zadaných akcí: viz podmíněná registrace rolí
    - **sleva v kombinaci s**: výběr již zadaných akcí a číslo: viz samostatné zadání

**V přihlášce**
- v přihlášce se potom uživateli zobrazí jako povinné vybrat si i akci (nebo kombinaci akcí)
- pouze pokud je počet zadaných podakcí 2 a více

**V programu**
- jednotlivé akce se poté v programu chovají jako kategorie programu
- při založení programu bude nutné vybrat do jaké podakce programový blok patří (pouze pokud je počet podakcí 2 a více)
- zařazení do podakce je povinné, pokud je založena pouze implicitní, potom jsou do ní programy automaticky zařazené
- k jednomu programu může být přiřazena pouze jedna podakce
- podakce se zobrazuje v přehledu programových bloků
- pokud nejsou další podakce (pouze implicitní) mohl by se sloupec skrýt

**V kalendáři pro výběr programu**
- každý uživatel vidí pouze programy zařazené pod své podakce
- pokud je založena pouze implicitní podakce, potom jsou do ní uživatelé automaticky zařazeni

**Nastavení ceny podakce/role**
- u nastavení ceny za roli přidat checkbox "Určit cenu podle ceny podakce"
- po zaškrtnutí se bude účastnický poplatek určovat podle zapsaných podkací
- při kombinaci s jinou neplacenou rolí bude poplatek opět nulový
- při kombinaci více placených rolí se cena sčítá

**Comment by jan-stanek** [comment]
Nebylo by lepší, aby byl název implicitní podakce trvale provázaný s názvem semináře - změna názvu by byla zakázaná. Zároveň by se implicitní podakce nezobrazovala v přihlášce. Použila by se prostě jenom pokud by se podakce nevytvářely a pak se celej ten výběr schová. Pokud by se podakce používaly, tak by se implicitní podakce nastavila programům při smazání jejich podakce.

**Comment by jan-stanek** [comment]
Pokud bude mít jednu roli s fixním poplatkem a jednu roli placenou podle podakcí. Může se ten poplatek za roli připočítávat k první registraci? (První registrace by měla u sebe příznak, že je první a při výpočtu ceny by se započetl tenhle poplatek.) Jinak by se muselo ještě někde evidovat zaplacení toho poplatku za roli, upravit generování dokladu, aby se to připočítávalo k první registraci / generovat samostatný doklad.

**Comment by jan-stanek** [comment]
Co se sloupečky platební metoda a datum zaplacení v přehledu uživatelů? Počítám s tím, že platební metoda může být u každé registrace jiná. Datum odeslání přihlášky se bude týkat první přihlášky?

Jsou to sice drobnosti, ale ovlivňuje to datovej model :-(

**Comment by jan-stanek** [comment]
Kdo bude mít přístup do struktury semináře? Administrátor a organizátor?

**Comment by DeetsCZ** [comment]
1. s nastavením implicitní podakce souhlasím, to mi přijde srozumitelné
2. tady si úplně nejsem jistá, jak to myslíš. pokud udělá registrace do obou rolí současně, potom by se ten poplatek měl sečíst do jednoho "za registraci"...
3. datum odeslání přihlášky bychom mohli nazvat "Datum odeslání první přihlášky", datum zaplacení bych nechala na datum zaplacení poslední registrace a do platební metody bych dala tři stavy: Hotovost, Na účet a Smíšená. Přijde ti to tak rozumné?
4. implicitně pouze administrátor

**Comment by jan-stanek** [comment]
1. ok

2. jak by to mělo funfovat, když si změní role, ale podakce zůstanou, žádná nová registrace se nevytvoří, kde to potom bude započtené? Nejjednodušší mi přijde mít tu první registraci odlišenou a připočítávat všechny poplatky za role k ní.

3. ok

4. upravím

**Comment by DeetsCZ** [comment]
Přidávám odsouhlasený popis fungování podakcí a registrace:

1. První registrace:
- Uživatel vybere roli a podakce
- Tím se vytvoří „objednávka“ u které se vygeneruje VS a cena, podle zadaných parametrů a přidá se datum splatnosti
- „Objednávku“ je možné měnit, je možné měnit role i podakce a vždy se změní i cena, ale splatnost zůstává stejná
- po zaplacení (zápis do tabulky v administraci) a tato „objednávka“ uzavře a není možné ji měnit
- po zaplacení není možné změnit si roli a ni původní podakce
- v profilu uživatele se tato „objednávka“ zobrazuje na jednom řádku s poznámkou zaplaceno
- pokud uživatel nezaplatí do konce splatnosti, potom se celá registrace zruší a on bude mít roli „Nepřihlášený“ a bude moct udělat celou registraci znovu
2. Další registrace
- Uživatel si po zaplacení první registrace může přidávat další podakce 
- Po zaplacení se mu objeví tlačítko „Přidat další“
- Zde si bude moct vybrat podakce, které ještě nemá zaplacené a zároveň, které mají volnou kapacitu
- Po výběru se vytvoří další „objednávka“
- Do přehledu se sjednotí vybrané podakce podle data vytvoření „objednávky“
- „Objednávku“ není možné upravovat 
- Pokud uživatel nezaplatí v době splatnosti, potom se objednávka zruší
- Uživatel může přidávat libovolně další „objednávky“, pokud existují nějaké podakce, kam by se mohl přihlásit

**Comment by DeetsCZ** [comment]
Chování sloupce akce v přehledu uživatelů:
Sloupec je defaultně zobrazený. Po přihlášení uživatele prázdný. Po registraci se buď vyplní registrovanými podakcemi uživatele, pokud je systém využívá, nebo se zde nastaví implicitní podakce.

**Comment by DeetsCZ** [comment]
Podle:
"Nebylo by lepší, aby byl název implicitní podakce trvale provázaný s názvem semináře - změna názvu by byla zakázaná. Zároveň by se implicitní podakce nezobrazovala v přihlášce. Použila by se prostě jenom pokud by se podakce nevytvářely a pak se celej ten výběr schová. Pokud by se podakce používaly, tak by se implicitní podakce nastavila programům při smazání jejich podakce, protože nějakou podakci přidělenou mít musí."

Tady bych udělala úpravu: 
1. nelze smazat podakci, která má přiřazené programové bloky, zobrazila bych varování "Nelze smazat podakci, která má přiřazené programy"
2. po přidání podakce bych do tabulky do sloupce "Akce" přidala nápis "Skrytá"
![snimek obrazovky 2017-09-15 v 13 48 01](https://user-images.githubusercontent.com/19816092/30481004-d7aafb64-9a1c-11e7-8b37-5ed18568a9e4.png)

**Comment by DeetsCZ** [comment]
Prosím o zařazení "Struktura akce" pod nastavení, tak abychom to trochu "uklidili" aby to zbytečně nemátlo lidí z akcí, které podakce nepoužívají. 
Děkuji

**Comment by DeetsCZ** [comment]
V přehledu podakcí mi zmizelo tlačítko pro smazání podakce:
![snimek obrazovky 2017-10-05 v 13 40 38](https://user-images.githubusercontent.com/19816092/31225529-d528b73a-a9d2-11e7-9379-cd959d7f4248.png)

**Comment by jan-stanek** [comment]
Nemůže to být tím, že je podakce přidělená nějakému bloku a nejde odstranit?

**Comment by DeetsCZ** [comment]
Pravda, bylo by tedy možné tam tlačítko nechat pouze ho zneaktivnit a přidat popis "Nelze smazat, k podakci je přiřazen programový blok"?

**Comment by jan-stanek** [comment]
To bohužel v tabulce neudělám. Mohl bych jen dát tlačítko aktivní všude a potom vypsat chybu.

**Comment by DeetsCZ** [comment]
To by také šlo.. Prosím tedy o zobrazení tlačítka vždy a přidání chybového hlášení

**Comment by DeetsCZ** [comment]
Pokud se to podaří, prosím o to, aby registrace podakcí byla povinná při výběru role, která určuje cenu podle podakcí.

**Comment by DeetsCZ** [comment]
Prosím o přesunutí checkboxu:
![snimek obrazovky 2017-10-15 v 22 52 32](https://user-images.githubusercontent.com/19816092/31589093-b28c9b48-b1fb-11e7-8b59-aeb5387ac8dc.png)
z nastavení semináře do podakcí
Děkuji

**Comment by jan-stanek** [comment]
Co dát na tu samou stránku ještě ty slevy, aby byla jasnější ta souvislost, nemuselo se nic schovávat v menu, ...?

**Comment by jan-stanek** [comment]
Bylo by to podobné jako přihláška:

Podakce - tabulka s podakcemi
Nastavení podakcí - checkbox pro povolení přidávání po zaplacení
Slevy - tabulka se slevami

**Comment by DeetsCZ** [comment]
Také mne to napadlo, ale nevím jestli ta stránka nebude trochu nepřehledná. Teď při zadání více podakcí se bude muset pro zadání slev hodně scrolovat dolu:
![snimek obrazovky 2017-10-19 v 12 45 16](https://user-images.githubusercontent.com/19816092/31767460-6cac8bf6-b4cb-11e7-8766-b3cd5d96b841.png)

Bylo by určitě lepší mít to na jedné stránce, nemohli bychom nahoru dát například nějakou navigaci? Odkaz který by odscroloval na danou pozici?

A potom prosím jeste o úpravu toho nastavení:
![snimek obrazovky 2017-10-19 v 12 43 27](https://user-images.githubusercontent.com/19816092/31767521-b0e49980-b4cb-11e7-9a71-c6ba1e713f6e.png)

Prosím o zarovnání úplně doleva a pokud by to bylo možné tak dát tlačítko uložit na jeden řádek s checkboxem.

**Comment by jan-stanek** [comment]
Určitě by to muselo být až dole. Navigace mě nenapadá jinak než pomocí nějakého podmenu v tom bočním menu, ale nepřijde mi to moc dobré.

Posunout úplně dolevy by to mělo jít, není ale lepší to nechat takhle? Je to všude stejné a když se tam něco přidá, tak se to bude vracet zpátky.

**Comment by DeetsCZ** [comment]
Asi by mi nejvíce sedělo, kdyby všechny checkboxy byly zarovnané vlevo a přehozené:
![snimek obrazovky 2017-10-20 v 13 02 01](https://user-images.githubusercontent.com/19816092/31818154-2a001008-b597-11e7-9487-47922513dbbf.png)

Tedy neprve vlevo tučně text s velkým písmenem jako je "Přihlášení na programy" a checkbox vpravo (vlastně tam, kde teď je) a tlačítko uložit potom nechat, jak je..

K té navigaci, mne napadlo špíš, kdyby odkazy byly nahoře:
![snimek obrazovky 2017-10-20 v 13 15 36](https://user-images.githubusercontent.com/19816092/31818519-cdd562e0-b598-11e7-819d-d0c58bde6c7e.png)

Jen si nejsem jistá, jestli to bude úplně ideální..

**Comment by jan-stanek** [comment]
Nevím, jestli už jsme to neřešili po skypu.

1. checkboxy bych nechal spíš takhhle - je to podle UX pravidel a vejde se tam i delší popisek (hlavně souhlas u přihlášky)

2. tu další úroveň menu bych určitě nezaváděl, to mi to přijde lepší na samostatné stránce, na druhou stranu na fullHD a větším to bude vidět celé a vzhledem k tomu, že se to nastaví jednou při instalaci, tak mi to přijde únosné i na menším

**Comment by jan-stanek** [comment]
Jaké je rozhodnutí, je tu k něco k dořešení?

**Comment by DeetsCZ** [comment]
Ta poloha checkboxů mí pořád nějak nesedí, ale asi je to jen malichernost. 

Děkuji uzavírám
