### ISSUE TITLE
Odhlášení účastníka při nezaplacení 

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#300]
V nastavení doplnit možnost:
**Datum splatnosti** (pro použití v emailingu a profilu účastníka):
1. XX dní (pravděpodobně bude nutné počítat jen s pracovními dny)
2. datum

**Automaticky odhlásit z akce**
1. pokud není zadána platba do XX dní od registrace na akci (pracovní dny?)
2. pokud není platba zadána do určitého pevného data
 
- Web si eviduje datum odeslání přihlášky 
- pokud nebude zadané datum platby do XX dní zadaných v nastavení (nebo v druhé variantě nebude platba zadaná do data, které bylo zadané v nastavení), potom se uživatel automaticky přesune do role Nepřihlášený
- v obou variantách by mělo odhlášení proběhnout na konci posledního dne o půlnoci, tedy například:
   - _Uživatel vyplnil přihlášku 1.1. Na platbu jsou nastavené 3 dny, tedy pokud není vyplněné datum platby, tak se uživatel z akce odhlásí 4.1. v 23:59. Pokud bylo nastavené zadání platby do 3.1., potom odhlášení proběhne 3.1. v 23:59._
 
- Bylo by tedy dobré provádět kontrolu zaplacení (pokud bylo zadané automatické odhlášení) každý den vždy 23:59 v první variantě. 
- V druhé variantě stačí provést kontrolu jednou v dané datum. 
- Možná by se kontroly daly provádět pouze v čase vymezeném datem “Odhlášení a změna role povolena do” plus počet dnů, které mají na platbu v případě první varianty. 
- U druhé varianty nemusíme omezovat, protože kontrola by měla proběhnout pouze jednou.

Pokud nejsou data zadaná, potom se kontroly vůbec neprovádí.

**Comment by DeetsCZ** [comment]
Pro spouštění kontrol bude potřeba využít cron, prosím tedy o pomoc @sinacek děkuji.

**Comment by sinacek** [comment]
Jak jsem psal dříve, cron je možný, ale zatím určitě jen ručně na lebedě, takže mi napište kde to chcete zkusit nastavit a já to tam udělám.

**Comment by jan-stanek** [comment]
@sinacek nevím, jestli už to není hotové, bylo to možné na srs a testweb?

**Comment by jan-stanek** [comment]
Je nutné používat ty pracovní dny? Splatnost bude asi většinou aspoň týden, ne? S krátkou splatností by ty platby musel někdo pořád kontrolovat.

**Comment by DeetsCZ** [comment]
Možná bych tedy přidala za tu první variantu splatnosti (do XX dní) checkbox "počítat jen pracovní dny", po zaškrtnutí by se opravdu počítalo jen s pracovními dny. Bude to potřeba, protože například pravé u Miquik jsou na platbu pouze 3 pracovní dny.

**Comment by DeetsCZ** [comment]
Prosím o úpravu formaláře s daty splatnosti následovně:
![snimek obrazovky 2017-10-10 v 23 01 37](https://user-images.githubusercontent.com/19816092/31410960-6f68ee82-ae10-11e7-9da0-215e4a6c1e44.png)

**Comment by jan-stanek** [comment]
Pro výpočet se používá stejný počet dní jako pro zaslání připomínky.

**Comment by DeetsCZ** [comment]
Zdá se, že při zadání 0 dní pro odhlášení k odhlášení nedojde:
![snimek obrazovky 2017-10-19 v 12 25 55](https://user-images.githubusercontent.com/19816092/31766983-c33721a4-b4c9-11e7-9f25-4254ee3c4a57.png)

K odhlášení mělo dojít 18.10. o půlnoci, ale nedošlo. (jedná se o srs.skauting.cz)
![snimek obrazovky 2017-10-19 v 12 36 02](https://user-images.githubusercontent.com/19816092/31767085-1a6a7d22-b4ca-11e7-8062-fa30d50a6a78.png)

**Comment by jan-stanek** [comment]
Opraveno, aby se to projevilo, je potřeba změnit nastavení, aby tam byla uložena 0, ne prázdné pole.

**Comment by DeetsCZ** [comment]
Děkuji za zpracování
