### ISSUE TITLE
Sleva při kombinaci podakcí

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#301]
Pokud uživatel vybere určitou kombinaci podakcí, potom dostane slevu, zadání slevy by mělo vypadat následovně:

V editaci podakce bude kolonka "Sleva":
- nejdříve bude obsahovat pouze tlačítko "Přidat slevu"
- po kliknutí na tlačítko se otevře dialog, který bude obsahovat:
   - "Vyber typ kombinace": "Nebo", "A"
   - "Vyber akci": multiselect všech akcí
   - "Sleva": textové pole
   - další tlačítko "Přidat slevu"
- pokud uživatel vybere "Nebo", potom bude platit sleva v kombinaci vždy dvou rolí a sleva se nesčítá
   - například: vyberu nebo, akce B, C a zadám slevu 10 kč, potom při kombinaci A+B nebo A+C dostane uživatel slevu 10kč, pokud bude kombinovat A+B+C potom bude sleva stále 10 kč
- pokud uživatel vybere "A", potom bude sleva při kombinaci všech vybraných akcí
   - například: vyberu a, akce B, C a zadám slevu 10 kč, potom při kombinaci A+B+C dostanu slevu 10 kč, pokud bych vybrala pouze A+B slevu nedostanu
- pokud uživatel zadá přes tlačítko další slevu, potom se budou slevy sčítat
   - například: v prvním formuláři vyberu nebo, akci B, C a zadám slevu 10 kč, v druhém formuláři vyberu a, akci D a zadám slevu 20 kč, potom při vybrání rolí A+B dostanu slevu 10kč, při vybrání A+B+C dostanu slevu 10 kč, při výběru A+D dostanu slevu 20 kč, při výběru A+B+D dostanu slevu 30 kč, při výběru A+B+C+D dostanu slevu 30kč

- bude nutné doplnit nápovědou, ideálně by se za slovo Sleva umístil otazník, na kterém se po najetí myší zobrazí dialogové okno s nápovědou a příklady
- sleva se bude uplatňovat pouze při registrace podakcí "najednou"

**Comment by DeetsCZ** [comment]
Prosím o drobnou úpravu, bylo by možné, aby se text v podmínce při zadávání posouval automaticky na konec?
![snimek obrazovky 2017-10-03 v 13 00 44](https://user-images.githubusercontent.com/19816092/31122220-3c67c4b6-a83b-11e7-9d6c-38f1a5a53233.png)
Ve firefoxu mi to jde posunout ručně, ale v safari to nejde.

**Comment by jan-stanek** [comment]
mělo by se to posouvat automaticky na konec, ale mělo by to jít i ručně

**Comment by DeetsCZ** [comment]
Automatické posouvání na konec již funguje, ale v safari se stále neposouvá ručně.
Bylo by možné udělat ještě několik úprav, aby zadávání bylo přehlednější:
1. tlačítka podakce až zrušit přesunout pod pole vzorce
2. pole vzorce roztahnout tak aby zabíralo 3 nebo možná spíš 4 řádky
asi takto:
![snimek obrazovky 2017-10-05 v 13 33 29](https://user-images.githubusercontent.com/19816092/31225323-cf25d120-a9d1-11e7-8675-039ee0232c1f.png)
Tak by mohl být vidět celý vzorec
3. bylo by možné přidat tlačítko pro mazání? Vím, že jsme řekli, že úpravy nebudou, ale to mazání z prava by tam hodně pomohlo.. (pokud by to bylo přiliš náročné, potom to nechme být..)

**Comment by DeetsCZ** [comment]
Bylo by možné ještě upravit:

1. položku Sleva přesunout v menu pod Podakce (teď je až za Platbou)
2. pokud se nevyužívají podakce (je pouze defaulní podakce), potom se tato položka skryje, eventuálně kdyby nešla skrýt, tak ji jen při nepoužívání zneaktivnit a přidat popis "Slevy je možné zadat pouze při používání podakcí" (varianta se skrytím by byla samozřejmě lepší)

**Comment by jan-stanek** [comment]
Aby mazání fungovalo spolehlivě, tak bych musel mít postupně uložené všechny úpravy a pak si to ještě ukládat do databáze, aby to fungovalo i pro editaci uložené slevy - vrátil bych se k tomu až bude čas.

**Comment by DeetsCZ** [comment]
Souhlasím, momentálně je zadávání slev ideální. Pokud bude v budoucnu čas, potom se můžeme vrátit k editaci.. Děkuji

**Comment by DeetsCZ** [comment]
Slevy jsou nyní funkční, proto uzavírám. Děkuji
