### ISSUE TITLE
Načítání fotky ze skautis

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#302]
Prosím o přidání fotky do detailu uživatele v administraci, která se bude načítat ze skautis.
Fotka by také měla být vidět v detailu uživatele v profilu na frontpage.

(Poznámka od Jerryho: některé fotky nemusí být momentálně k dispozici, protože se systém fotek ve skautis upravuje)

**Comment by DeetsCZ** [comment]
Testovala jsem a bohužel u žádného uživatele fotku nevidím, ale předpokládám, že se musí nejprve uživatele přihlásit.
U mé osoby fotka je, ale nenačítá se:
![snimek obrazovky 2017-07-12 v 9 42 59](https://user-images.githubusercontent.com/19816092/28107055-8494167c-66e6-11e7-977e-82e5d2e07f56.png)

Nevím, jestli je to chyba, nebo problém, o kterém mluvil Jerry ( @jerrysohn ), to nedokáži posoudit.

**Comment by jan-stanek** [comment]
Na localhost to funguje, zjistím kde je problém.

**Comment by jan-stanek** [comment]
Tak je to tím, že se nevytvořila složka, kam se fotky nahrávají, protože se ignoruje při deploy.

**Comment by DeetsCZ** [comment]
Děkuji, funguje
