### ISSUE TITLE
Dodatečné přidání podakcí

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#303]
V nastavení v sekci podakce prosím přidat checkbox: "Povolit dodatečné přidávání podakcí po zaplacení"
V profilu uživatele ve frontpage:
- Toto aktivuje možnost, aby si uživatel mohl v profilu po zaplacení (zadání data platby v administraci) přidávat další podakce.
- Nebude si moct akce ubírat pouze přidávat.
- Měl by mít možnost zaškrnout více podakcí, kde nebyla naplněná kapacita.
- Po potvrzení se mu vygeneruje a odešle email s informacemi o nové registraci a platbě (obsah bude upřesnět v samostatném issue #58 ).
- Toto bude možné opakovat, dokud buď nebude mít zapsané všechny podakce, nebo už se nebude možné na další zapsat (např vyčerpaná kapacita).

V databázi
- bude nutné přidat vazební tabulku:
 ![snimek obrazovky 2017-07-01 v 22 19 21](https://user-images.githubusercontent.com/19816092/27765177-66224a4e-5eab-11e7-9949-1cf07cd98a66.png)
- tabulka obsahuje: id uživatele, id podakce, datum registrace, datum platby a stav
- první záznam (záznamy, pokud vybere více podakcí) se uživateli vytvoří při vyplnění přihlášky do akce 
    - dokud má u první registrace stav čeká na platbu, potom si v profilu může měnit podakce
    - když se vyplní datum platby u první registrace, potom již nemůže podakce v profilu ubírat pouze přidávat
- stav
   - **čeká na platbu**: po registraci podakce
   - **zrušeno: nezaplaceno**: při využívání automatického odhlášení při nezaplacení #300 
   - **zrušeno**: pokud se v administraci akce uživateli ručně zruší
   - **zaplaceno**: pokud se v administraci zadá datum platby, toto datum se vyplní i do tabulky
v administraci 
- přehled uživatelů
   - za sloupec "Cena" (celková cena = součet cen podakcí, které mají stáv čeká na platbu a zaplaceno)  prosím přidat sloupec "Zbývá doplatit" (součet cen podakcí, které mají stav čeká na platbu)
   - při použítí hromadné akce “Zaplaceno dnes” se označí všechny podakce uživatele jako zaplacené
 - detail uživatele
   - do detailu bude nutné přidat přehled registrovaných podakcí: bude vidět pouze při používání podakcí
   - přehled by měl obsahovat jednotlivé registrace uživatele (ideálně, kdyby se podakce zadané při jedné registraci seskupily)
   - **Datum registrace**: 1.1.17 
   - **Podakce**: Akce A, Akce B (výpis podakcí, které si uživatel zaregistroval v této registraci)
   - **Cena**: 110 kč (cena za kombinací akcí)
   - **Stav**: Zaplaceno (stav se mění automaticky: Čeká na platbu, Zaplaceno, Zrušeno: nezaplaceno, Zrušeno)
   - **Zaplaceno dne**: 2.1.17 (výběr z kalendáře: po výběru data se automaticky stav změní na zaplaceno)
   - **Zrušit registraci**: tlačítko (nastaví stav na Zrušeno)

**Comment by jan-stanek** [comment]
Jak to bude s doklady, bude třeba vystavit pro každou platbu samostatný?

**Comment by DeetsCZ** [comment]
Asi bude nejlepší, když bude pro každou "registraci" zvlášť.

**Comment by DeetsCZ** [comment]
Otestováno, vše je funkční. Uzavřu po vyzkoušení automatického odhlášení při nezaplacení..
