### ISSUE TITLE
CHYBA: nefunkční menu v administraci

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#306]
V administraci přestalo fungovat "malé menu" v pravo nahoře:
![snimek obrazovky 2017-07-03 v 9 56 53](https://user-images.githubusercontent.com/19816092/27788701-ecd877d6-5fe9-11e7-8adc-945a4e3c6541.png)

Po kliknutí se nic neděje..

**Comment by DeetsCZ** [comment]
Menu funguje, děkuji za opravu.
![snimek obrazovky 2017-07-12 v 9 44 46](https://user-images.githubusercontent.com/19816092/28107188-f986cc40-66e6-11e7-80a8-0fada63943ae.png)

Jak jsem na to koukala, tak mi nejsou jasné položky "Administrátor" a "Profil", protože oba odkazují na profil uživatele ve frotend. Má položka administrátor nějaký význam? Pokud ne tak by v menu mohl být jen "Profil" a "Odhlásit", možná by dávalo smysl, kdyby místo administrátor byl odkaz na frotend (třeba "Web")

**Comment by jan-stanek** [comment]
Je to tam jen jako seznam rolí, myslím, že tam byl drobnej rozdíl, že kliknutím na roli se v profilu rovnou rozbalila ta část s rolema, ale pak jsme tam prohodili pořadí záložek a ta část je rozbalena tak jako tak.

**Comment by DeetsCZ** [comment]
Aha, tak to opravdu nedava smysl, možná, kdyby položka "Profil" rozbalila tu čast s osobními údaji.

**Comment by jan-stanek** [comment]
Ta chyba vznikla tím, že jsem chtěl, aby široké tabulky měly horizontální scrollbar, ale způsobuje to problém i s rozbalovacím menu v tabulkách, tak jsem to zase zrušil.

**Comment by jan-stanek** [comment]
Odkay upraven.

**Comment by DeetsCZ** [comment]
Funguje, děkuji
