### ISSUE TITLE
Hromadné přiřazování rolí

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#31]
Tak jako se nyní dá hromadně uživatelům zadat platba a tisk dokladů v evidenci účastníků, prosím o úpravu, aby se hromadně daly zadávat i role.

**Comment by jan-stanek** [comment]
Má to být pro všechny role, nebo jen některé? Bude tam pak dlouhý seznam položek jako "Schválit", ...,, "Přidat roli lektor", "Přidat roli administrátor", ...

Role se mají jen přidat, aby současné zůstaly zachované, nebo mají nově přidané nahradit současné role?

**Comment by DeetsCZ** [comment]
V případě většího počtu rolí na akci bude seznam opravdu dlouhý. 
Napadlo mne jiné řešení:
Na stránce evidence účastníků pod výběr hromadné akce ("Označené: "...), jak je tomu nyní přidat tlačítko "Výběr role", které zobrazí dialogové okno s checkboxy, kde bude možné zaškrtnout všechny role pro vybrané uživatele. Potom se současné role nahradí těmi zaškrtanými.
Je pravděpodobné, že jeden uživatel bude mít více než jednu roli hlavně v případě, že jede na akci jako účastník a zároveň bude v nějaké chvíli vystupovat jako lektor, nebo bude vystupovat jako lektor a zároveň organizátor, tedy ve většině případů půjde o kombinaci pouze dvou rolí a tak by seznam "Schválit" neměl být dlouhý.

**Comment by jan-stanek** [comment]
Ok

Jenom k tomu schválit - schvalovat se má každá role samostatně? Teď je to tak, že se schvaluje pouze uživatel.
- Pokud se přihlásí jako účastník, je schválen automaticky.
- Pokud se přihlásí jako lektor, ... musí být schválen.
- Po vyplnění přihlášky už se nezobrazuje formulář pro další přihlášení - další role musí někdo přidělit. (není tedy možné, aby se někdo přihlásil jako účastník, byl automaticky schválen, pak se přihlásil jako lektor a byl už předem schválený)

**Comment by DeetsCZ** [comment]
1. Ve formuláři pro přihlášení by mělo jít vybrat více než jednu roli:
![snimek obrazovky 2016-09-24 v 13 36 58](https://cloud.githubusercontent.com/assets/19816092/18808203/03a0d1aa-825c-11e6-9078-597e2efd6c28.png)

2. Po vyplnění přihlášky bych nechala možnost přidat další roli pouze administrátorovi nebo orgranizátorovi v administraci, tím pádem budou další role schválené.

3. Po registraci by mělo stačit schválení uživatele, ne jednotlivé role. Pokud bude minimálně jedna role, kterou si uživatel vybere, vyžadovat schválení, potom nedojde k automatickému schválení, ale bude nutno uživatele schválit.

**Comment by jan-stanek** [comment]
Doplněno hromadné přidělování rolí v administraci.

Přihlášování pod více rolemi bude doplněno po zavedení rolí vázaných na kategorii.

**Comment by DeetsCZ** [comment]
Issue nechám otevřený, než bude vše hotové, kvůli testování...

**Comment by DeetsCZ** [comment]
Děkuji za zpracování
