### ISSUE TITLE
Generování variabilního symbolu

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#32]
V konfiguraci přidat pole pro zadání předvolby (např. 99).

V evidenci účastníků v detailu uživatele přidat kolonku variabilní symbol, který se bude tvořit z předvolby a datumu narození (např. narození 8.10.2012 bude mít varibilní symbol 99121008). S tím, že orgranizátor a administrátor by měli mít právo VS upravit (pro případ, že by dva účastníci měli stejné datum narození).

**Comment by jan-stanek** [comment]
```
ALTER TABLE `User` ADD `variableSymbol` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_czech_ci NULL DEFAULT NULL AFTER `paymentDate`;
INSERT INTO `Settings` (`id`, `item`, `value`, `description`) VALUES (NULL, 'variable_symbol_code', '00', 'Předvolba pro variabilní symbol');
```

**Comment by DeetsCZ** [comment]
Databáze upravena..

**Comment by DeetsCZ** [comment]
Děkuji za úpravu.
Prosím ještě variabilní symbol zobrazit v frontendu v profilu uživatele pod položkou "Cena semináře":
![snimek obrazovky 2016-09-24 v 13 24 36](https://cloud.githubusercontent.com/assets/19816092/18808145/61430190-825a-11e6-82ee-a40b85267638.png)

**Comment by DeetsCZ** [comment]
Děkuji za úpravu..
