### ISSUE TITLE
Neveřejná poznámka k uživatelům

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#34]
V detailu uživatele přidat pole pro poznámku "Neveřejné poznámky", které může editovat a vidět pouze Administrátor nebo Orgranizátor.

**Comment by jan-stanek** [comment]
```ALTER TABLE `User` ADD `note` TEXT NULL DEFAULT NULL AFTER `phone`;```

**Comment by DeetsCZ** [comment]
Databaze upravena..

**Comment by DeetsCZ** [comment]
Děkuji
