### ISSUE TITLE
Nepropojený účet

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#35]
Pokud uživatel nemá propojený účet, potom by se mu v záhlaví (pod jménem) mělo zobrazovat upozornění "Nepropojený účet člena" s odkazem na novou stránku s návodem na propojení, jako je tomu na nyní na křižovatce:
![snimek obrazovky 2016-08-31 v 14 22 00](https://cloud.githubusercontent.com/assets/19816092/18128576/c4d55bcc-6f86-11e6-9384-8b33e0e9f7b6.png)
S textem:
"Nemáte propojený účet
Byli jste úspěšně přihlášeni na webu, ale pravděpodobně nejste členem Junáka.

Pokud členy jste, pak nemáte pravděpodobně propojený svůj uživatelský účet se skutečnými údaji v registraci. Kontaktuje svého vedoucího oddílu (nebo osobu, která zpracovává registraci) a požádejte ho o propojení vašeho účtu ve skautISu s reálnými údaji.

Pro propojení účtu potřebujete tyto údaje:
uživatelské jméno: "jméno ze skautis"
bezpečnostní kód: "bezpečnostní kód" - možno získat z "UserManagement=>User"

Poznámka: V žádném případě nikdy nikomu nedávejte své heslo. "
(bez tlačítka "odhlásit se")

V tabulce evidence účastníků přidejte sloupec "Členství".
Pokud nemá uživatel propojený účet, potom bude v sloupci "nepropojený účet".
Pokud má propojený účet, potom vypište evidenční číslo jednotky, kde má čestné nebo řádné členství.

**Comment by jan-stanek** [comment]
```ALTER TABLE `User` ADD `securityCode` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_czech_ci NOT NULL AFTER `displayName`, ADD `member` TINYINT(1) NOT NULL AFTER `securityCode`;```

**Comment by jan-stanek** [comment]
```ALTER TABLE `User` ADD `securityCode` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_czech_ci NULL DEFAULT NULL AFTER `displayName`, ADD `member` TINYINT(1) NOT NULL AFTER `securityCode`, ADD `organizationUnit` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_czech_ci NULL DEFAULT NULL AFTER `member`;```

**Comment by jan-stanek** [comment]
V seznamu uživatelů se zobrazuje nepropojený účet u všech uživatelů, dokud se nepřihlásí a databáze se neaktualizuje. Při nové instalaci s tím nebude problém.

K informaci o propojení účtu a jednotce pravděpodobně nemají přístup ostatní uživatelé, takže to nelze jinak vyřešit. Pouze by se dalo udělat, aby se zobrazoval jiný text.

**Comment by jerrysohn** [comment]
Je to tak, že k informaci o členství a účtu má vždy přístup jen daný uživatel a případně vedoucí/admin jednotky kde je (+ jejich nadřízení). Tedy je zcela v pořádku, že se toto aktualizuje spolu s přihlášením uživatele (protože on sám takové údaje o sobě zjistí).
Ale samozřejmě předpokládám, že pak se údaj o členství ukládá do databáze přímo na SRS, takže už tuto informaci má k dispozici pořadatelský tým akce (přestože sám by si takovou informaci o osobě přímo ve skautISu vyhledat většinou nemohl) ;-)

**Comment by jan-stanek** [comment]
Díky za upřesnění. Při každém přihlášení se informace o jednotce a propojení aktualizuje v databázi SRS.

**Comment by DeetsCZ** [comment]
Databáze upravena...

**Comment by DeetsCZ** [comment]
Bylo by dobré, kdyby byla informace o nepropojeném účtu v tabulce "Evidence uživatelů" výraznější. Asi by stačilo kdyby byl nápis "nepropojený účet" červeně, tak aby ta informace byla na první pohled vidět.

**Comment by DeetsCZ** [comment]
Pokusila jsem se přihlásit s nepropojeným účtem a přihlášení skončilo chybou:
![snimek obrazovky 2016-09-24 v 13 29 06](https://cloud.githubusercontent.com/assets/19816092/18808162/f41f149a-825a-11e6-8eaf-fe248598f57b.png)

**Comment by DeetsCZ** [comment]
Děkuji za zpracování
