### ISSUE TITLE
Fotka lektora

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#354]
Prosím o přidání fotky lektora do stránky se zápisem programu:
![snimek obrazovky 2017-10-08 v 10 26 22](https://user-images.githubusercontent.com/19816092/31315245-7ff7d7b6-ac14-11e7-8113-4b1d66b2dc32.png)

Ideálně tak, aby fotka byla miniatura a text ji obtékal v pravo:
![snimek obrazovky 2017-10-08 v 10 32 38](https://user-images.githubusercontent.com/19816092/31315249-92f8a6b0-ac14-11e7-9eb7-94026e55da0d.png)

**Comment by jan-stanek** [comment]
přidáno do detailu programu v kalendáři i detailu bloku v přehledu bloků

**Comment by DeetsCZ** [comment]
Děkuji

Jen mne k tomu ještě napadá snad drobnost:
![snimek obrazovky 2017-10-10 v 13 35 31](https://user-images.githubusercontent.com/19816092/31384606-f15a7ace-adbf-11e7-8618-30026603973a.png)

Bylo by možné skrýt pole, která nejsou zadaná?

**Comment by DeetsCZ** [comment]
Děkuji
