### ISSUE TITLE
Úprava povolení zápisu na programy

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#358]
Prosím o úpravu:

Odebrat z nastavení programu checkbox "povolit přihlašování na programy" a data pro povolení zápisu od od.
Přidat položku "Přihlašování na programy: ", kde bude možný výběr z 3 hodnot "Povoleno" (default), "Zakázáno", "Od Do"

Pokud vyberu "Zakázáno", potom není možné se zapisovat na programy a na webu nad kalendářem se zobrazuje hláška "Zápisování programů není v tuto chvíli povoleno"

Pokud vyberu "Od Do", potom se mi zobrazí možnost zadat data od do (povinné pole) a na webu nad kalendářem se zobrazuje hláška "Zapisování programů je povoleno od XX do XX"

Děkuji

**Comment by jan-stanek** [comment]
Od do nebudou povinná - stejný problém jako přihláška a podakce. Ale dalo by se využít zadáním jen jednoho datumu omezit jen v jednom směru.

**Comment by DeetsCZ** [comment]
No, pokud se to od do nevyplní, mohl by to systém brát jako neomezené, tak by nevadilo, ze je to nepovinné..

**Comment by DeetsCZ** [comment]
Děkuji
