### ISSUE TITLE
Nerozbalovat nabídku rolí v přihlášce

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#364]
Pokud je registrovatelná pouze jedna role, potom prosím o úpravu, aby se výběr v přihlášce po kliknutí nerozbaloval:
![snimek obrazovky 2017-10-11 v 21 50 12](https://user-images.githubusercontent.com/19816092/31462804-302738a0-aece-11e7-8b8a-a322d24d0f7f.png)

**Comment by jan-stanek** [comment]
+povinne podakce

**Comment by DeetsCZ** [comment]
Děkuji
