### ISSUE TITLE
Zvýraznění povinné položky v přihlášce

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#365]
Pokud je v přihlášce povinné vlastní pole prosím o její zvýraznění (například červenou hvězdičkou):
![snimek obrazovky 2017-10-11 v 22 14 38](https://user-images.githubusercontent.com/19816092/31464382-c3370b4a-aed1-11e7-9fb7-e43a176acaaf.png)

**Comment by DeetsCZ** [comment]
Děkuji, jen jak koukám na přihlášku, tak pokud se používaji podakce, potom by i kolonka měla být označena jako povinná:
![snimek obrazovky 2017-10-15 v 22 50 42](https://user-images.githubusercontent.com/19816092/31589070-4a7b5dc8-b1fb-11e7-9350-16711f1ab3bc.png)
Je to možné, nebo to nepůjde?

**Comment by jan-stanek** [comment]
Mohu to nějak zkusit, ale asi až v úterý/středu.

**Comment by DeetsCZ** [comment]
Děkuji
