### ISSUE TITLE
CHYBA: nenačítají se fotky ze skautis

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#380]
Fotky ze skautis se nenačítají:
![snimek obrazovky 2017-10-17 v 13 44 25](https://user-images.githubusercontent.com/19816092/31663574-da6771e0-b342-11e7-8c70-398e9e654f31.png)

**Comment by DeetsCZ** [comment]
Fotka se stále nezobrazuje:
![snimek obrazovky 2017-10-18 v 8 28 32](https://user-images.githubusercontent.com/19816092/31703767-69221d40-b3de-11e7-9bb6-df3cefe78beb.png)

**Comment by jan-stanek** [comment]
Teď je to tím, že se načítá jen při prvním přihlášení / změně fotky

Chce to v tabulce user nastavit všem photo_update na null

**Comment by jan-stanek** [comment]
a ještě bych taky musel potvrdit merge :-D

**Comment by jan-stanek** [comment]
```UPDATE `user` SET `photo_update`=NULL WHERE 1```

**Comment by DeetsCZ** [comment]
Děkuji :)
