### ISSUE TITLE
Chyba: Zobrazení programových bloků

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#4]
V administraci programových bloků by mělo být 10 bloků, ale systém bez zadaných filtrů zobrazuje jen dva:
![snimek obrazovky 2016-08-03 v 14 23 06](https://cloud.githubusercontent.com/assets/19816092/17365370/289b6802-5986-11e6-9176-9470dd5e2207.png)

Při filtrování podle lektora (například Kraj Jihomoravský TGM ) se zobrazují správně čtyři:
![snimek obrazovky 2016-08-03 v 14 25 57](https://cloud.githubusercontent.com/assets/19816092/17365379/3696fe58-5986-11e6-94b2-e6c6a3dcd03b.png)

**Comment by jan-stanek** [comment]
Nedaří se mi přidat takové programy, aby se chyba projevila i u mne. Nebylo by možné zaslat databázi ze srs.skauting.cz?

**Comment by DeetsCZ** [comment]
Děkuji za opravu..
