### ISSUE TITLE
Chyba: nelze uložit změny v profilu

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#40]
Při testování jsem změnila údaj o platbě, ale při pokusu uložit profil vyskočila chyba:
![snimek obrazovky 2016-09-02 v 13 22 17](https://cloud.githubusercontent.com/assets/19816092/18202546/fc934192-7110-11e6-8c58-1abc0484ff22.png)

**Comment by jan-stanek** [comment]
Projevuje se chyba stále? Na lokální kopii jsem na ní nenarazil, na webu jsem promazal cache.

**Comment by DeetsCZ** [comment]
Chvilku to šlo, ale nyní opět stejná chyba..

**Comment by DeetsCZ** [comment]
Nyní funguje...
