### ISSUE TITLE
Povinný výběr podakcí

### ISSUE THREAD

**Issue by jan-stanek** [skaut/SRS#400]
Zkontrolovat povinnost výběru podakcí (přihláška, úprava v profilu, úprava v administraci), tak aby byly podakce povinné v závislosti na vybrané roli.

**Comment by jan-stanek** [comment]
v přihlášce je výběr povinný, pokud je vybraná role s cenou podle podakcí, v administraci se nekontroluje

**Comment by DeetsCZ** [comment]
Děkuji
