### ISSUE TITLE
CHYBA: samovolná změna stavu registrace

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#401]
Narazila jsem na divné chování:
uživatel má dvě registrace
2. mu zruším: objeví se zrušeno
1. upravím a uložím
v tu chvíli se 2. sama opět přesune do stavu "čeká na platbu"

**Comment by jan-stanek** [comment]
To bude tím, že pokud upravuji první, je třeba přepočítat cenu ostatních podle nových rolí. Opravím to.

**Comment by jan-stanek** [comment]
opraveno

**Comment by DeetsCZ** [comment]
Děkuji
