### ISSUE TITLE
Logování

### ISSUE THREAD

**Issue by jan-stanek** [skaut/SRS#405]
- [x] ukládat u uživatele první přihlášení do SRS
- [x] SCD2 historizace - role-uživatel
- [x] SCD2 historizace - podakce-uživatel (včetně dalších údají z vazební tabulky)

**Comment by jan-stanek** [comment]
Použít: https://github.com/Kdyby/Events

**Comment by jan-stanek** [comment]
Přidat možnost zobrazení historie změn přihlášky?

**Comment by DeetsCZ** [comment]
Historie změn v přihlášce by se určitě také hodila.

**Comment by jan-stanek** [comment]
jsou tam všechny změny podakcí, rolí, stavu přihlášky, datumů zaplacení, změn VS, ...

záznamy o přihláškách se nemění ani nemažou, jen přidávají nové

zatím se to dá dostat jen z databáze - tabulka `application` + vazební `application_role` a `application_subevent`

**Comment by DeetsCZ** [comment]
ok, děkuji

**Comment by jan-stanek** [comment]
přidáno zobrazení logu

**Comment by DeetsCZ** [comment]
Děkuji
