### ISSUE TITLE
Počítat se svátky při výpočtu pracovních dní

### ISSUE THREAD

**Issue by jan-stanek** [skaut/SRS#409]
Funkce která počítá datum splatnosti nepočítá při výpočtu podle pracovních dnů se svátky.

Funkce: https://github.com/skaut/SRS/blob/17cbe052720bc7190298b0e91bf7fb4a2b2be744/app/services/ApplicationService.php#L534

Pro svátky lze použít: https://github.com/azuyalabs/yasumi

**Comment by DeetsCZ** [comment]
Děkuji za zpracování
