### ISSUE TITLE
Umožnit filtrování podle více parametrů

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#410]
Bylo by možné použití více filtrů najednou? Nyní pokud v seznamu uživatelů vyberu filtrování podle jednoho parametru, potom již nemohu zadat další filtr.

**Comment by jan-stanek** [comment]
Funguje to, dokud se nepoužívají složitější filtry (role, podakce) -> zkusit, jestli to půjde vyřešit.

**Comment by jan-stanek** [comment]
#411

**Comment by DeetsCZ** [comment]
Bylo by možné přidat řazení udalších sloupců?
Smysl mi to dává u sloupců Cena, Zbývá doplatit, Platební metoda, Datum poslední platby, Datum přihlášení, Nepřihlášené povinné bloky. Půjde to?

**Comment by jan-stanek** [comment]
U těch počítaných sloupců je to složitější. Řazení se dělí přímo na úrovni databáze, takže to musím napsat jako select.

Dalo by se to vyřešit tím, že by se ten údaj přidal k uživateli a při změnách se aktualizoval.

**Comment by DeetsCZ** [comment]
Pokud by ti to nezabralo příliš času, tak by to bylo určitě fajn, protože teď se tam například nedají jednoduše dohledat ti, kteří ještě nezaplatili vše..

**Comment by jan-stanek** [comment]
Kouknu na to v pondělí/úterý.

Jen do těch povinných bloků bych se teď nepouštěl. Nejdřív je třeba tam doplnit aplikační vrstvu a nedělat změny na víc místech.

**Comment by DeetsCZ** [comment]
Nepřihlášené povinné bloky asi můžeme nyní vynechat, to tak důležité..

**Comment by jan-stanek** [comment]
Při aktualizaci nebudou tyto sloupce u stávajících uživatelů vyplněny - aktualizují se při změně (platba, přihlášení, změna rolí/podakcí, ...)

**Comment by jan-stanek** [comment]
řazení podle rolí a podakcí to ještě víc komplikuje - u každého uživatele se bude muset ukládat přímo ten text, který potom bude nutné aktualizovat s každou změnou rolí/podakcí, ale taky při přejmenování rolí/podakcí apod.

u vlastních polí by to snad šlo i bez toho

**Comment by DeetsCZ** [comment]
Toto pro zatím uzavírám..
