### ISSUE TITLE
Problém s cookies

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#411]
Již druhý člověk, který aktivně pracuje s tabulkou uživatelů hlásí problém, kdy mu najednou nefunguje administrace. K vyřešení stačí promazat cookies v prohlížeči a je to opět v pořádku. Je nějaká možnost,  jak bychom mohli toto ošetřit na naší straně?

**Comment by jan-stanek** [comment]
Nefunguje znamená Server error? Je k tomu záznam v logu?

**Comment by DeetsCZ** [comment]
Tomu uživateli se zobrazuje Server error, ale ostaním web normálně funguje.
V logu je dnes přidaná chyba:
[2017-10-25 09-52-36] Doctrine\ORM\Query\QueryException: Too many parameters: the query defines 1 parameters and you bound 2 in /home/vu009408/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:103  @  https://miquik.skauting.cz/admin/users/  @@  exception--2017-10-25--09-42--019bbcf8ba.html

Ale nevím jestli to s tímto problémem souvisí.

**Comment by jan-stanek** [comment]
Nejspíš to s tím souvisí, ale netuším v čem je problém.

Zkusím update, mám ho zakázaný, protože obcházím ten problém s multiselectem na výběr rolí.

**Comment by DeetsCZ** [comment]
Pro zatím uzavírám, u mne tento problém není, pokud by se to znovu objevilo, tak issue znovu otevřu.
