### ISSUE TITLE
Přehodnocení rolí a přihlášek

### ISSUE THREAD

**Issue by jan-stanek** [skaut/SRS#415]
Problém:
Zobrazení rolí u první přihlášky způsobuje problém s tím, že první přihláška musí být odlišená od ostatních. Při zrušení první přihlášky přijde uživatel o své role a odstraní se všechny přihlášky (#408). Nemůže mít více prvních přihlášek.

Návrh řešení:
- Dát role zvlášť, jako to bylo dosud.
- Všechny přihlášky udělat rovnocenné.
- Při rušení registrace se přihláškám pouze nastaví "Zrušeno", nic se nebude mazat.
- Pokud bude mít uživatel všechny přihlášky zrušené, role mu zůstanou, ale při přihlášení bude mít "efektivní" roli Nepřihlášený. Pokud by se chtěl znovu přihlásit, tak by nevyplňoval celou přihlášku, ale přidal novou v profilu, jako když si chce přidat další podakce.
- Editovat půjde všechny nezaplacené přihlášky, ale přidat další půjde až po zaplacení všech předchozích.
- Editace rolí bude možná do zaplacení libovolné přihlášky.
- Cena se bude skládat z ceny za role + ceny jednolitvých přihlášek
- Podakce -> akce?

**Comment by jan-stanek** [comment]
Update:
- Role mimo tabulku objednávek. Změna multiselectem, dokud není cokoliv zaplaceno.
- K přihlášce půjde navázat role - pokud bude uživatel mít placné role, vypíší se jako jedna objednávka, pokud bude mít podakce budou následovat jednotlivé objednávky podakcí.
- Pokud nezaplatí, nastaví se přihláška jako zrušená - pokud nezaplatí placené role, nastaví se objednávka jako zrušená a odeberou se mu navíc tyto role; pokud nezaplatí objednávku s podakcemi, nastaví se jako zrušená; pokud nezaplatí žádnou objednávku s podakcemi, odebere se mu i role s cenou určenou podle podakcí
- Pokud nebude mít žádnou roli, otevře se mu znovu přihláška; může nastat to, že mu zůstanou placené role, ale odstraní se mu role placená podle podakcí - to asi nemá cenu řešit, role s fixní cenou a role s cenou podle podakcí se většinou nebudou kombinovat
- Editovat půjde všechny nezaplacené přihlášky s podakcemi, další půjde přidat po zaplacení přechozích (otevřená bude vždy jen jedna)
- Sloupečky v objednávkách se budou zobrazovat podle využití

pouze

 sloupeček Role (pouze role s fixní cenou, pak v ní bude maximálně jeden nezrušený záznam)

**Comment by jan-stanek** [comment]
Update:

    Role mimo tabulku objednávek. Změna multiselectem, dokud není cokoliv zaplaceno.
    K přihlášce půjde navázat role - pokud bude uživatel mít placné role, vypíší se jako jedna objednávka, pokud bude mít podakce budou následovat jednotlivé objednávky podakcí.
    Pokud nezaplatí, nastaví se přihláška jako zrušená - pokud nezaplatí placené role, nastaví se objednávka jako zrušená a odeberou se mu navíc tyto role; pokud nezaplatí objednávku s podakcemi, nastaví se jako zrušená; pokud nezaplatí žádnou objednávku s podakcemi, odebere se mu i role s cenou určenou podle podakcí
    Pokud nebude mít žádnou roli, otevře se mu znovu přihláška; může nastat to, že mu zůstanou placené role, ale odstraní se mu role placená podle podakcí - to asi nemá cenu řešit, role s fixní cenou a role s cenou podle podakcí se většinou nebudou kombinovat
    Editovat půjde všechny nezaplacené přihlášky s podakcemi, další půjde přidat po zaplacení přechozích (otevřená bude vždy jen jedna)
    Sloupečky v objednávkách se budou zobrazovat podle využití:
        pouze sloupeček Role (uživatel má pouze role s fixní cenou, v tabulce pak také bude maximálně 1 nezrušený záznam)
        pouze sloupeček Podakce (uživatel má pouze roli s cenou podle podakcí)
        oba sloupečky (uživatel kombinuje role s fixní cenou s rolemi s cenou podle podakcí - málo časté)
    Neskrývat podakce v administraci? I když bude pouze implicitní podakce, bude potřeba pro napojení na skautIS vzdělávací akci, tudíž by o ní měli vědět. (Myslím, že se snad ani v administraci neskrývají, kromé té tabulky objednávek, která bude nová, viz předchozí bod.)

**Comment by jan-stanek** [comment]
Update:
- Role mimo tabulku objednávek. Změna multiselectem, dokud není cokoliv zaplaceno.
- K přihlášce půjde navázat role - pokud bude uživatel mít placné role, vypíší se jako jedna objednávka, pokud bude mít podakce budou následovat jednotlivé objednávky podakcí.
- Pokud nezaplatí, nastaví se přihláška jako zrušená - pokud nezaplatí placené role, nastaví se objednávka jako zrušená a odeberou se mu navíc tyto role; pokud nezaplatí objednávku s podakcemi, nastaví se jako zrušená; pokud nezaplatí žádnou objednávku s podakcemi, odebere se mu i role s cenou určenou podle podakcí
- Pokud nebude mít žádnou roli, otevře se mu znovu přihláška; může nastat to, že mu zůstanou placené role, ale odstraní se mu role placená podle podakcí - to asi nemá cenu řešit, role s fixní cenou a role s cenou podle podakcí se většinou nebudou kombinovat
- Editovat půjde všechny nezaplacené přihlášky s podakcemi, další půjde přidat po zaplacení přechozích (otevřená bude vždy jen jedna)
- Sloupečky v objednávkách se budou zobrazovat podle využití:
  - pouze sloupeček Role (uživatel má pouze role s fixní cenou, v tabulce pak také bude maximálně 1 nezrušený záznam)
  - pouze sloupeček Podakce (uživatel má pouze roli s cenou podle podakcí)
  - oba sloupečky (uživatel kombinuje role s fixní cenou s rolemi s cenou podle podakcí - málo časté)
- Neskrývat podakce v administraci? I když bude pouze implicitní podakce, bude potřeba pro napojení na skautIS vzdělávací akci, tudíž by o ní měli vědět. (Myslím, že se snad ani v administraci neskrývají, kromé té tabulky objednávek, která bude nová, viz předchozí bod.)

**Comment by jan-stanek** [comment]
E-mail potvrzující změnu registrace rozdělit na změnu rolí a změnu podakcí.

**Comment by jan-stanek** [comment]
Přihlašování, odhlašování, ... je skoro celé nové, snažil jsem se co nejvíc otestovat.

**Comment by DeetsCZ** [comment]
Děkuji za zpracování, budu teď nějakou dobu testovat.

**Comment by jan-stanek** [comment]
Snad to bude lepší :-)

Nevím, co se stane při aktualizaci, lepší bude čistá instalace (mělo by stačit promazat `application)`

**Comment by DeetsCZ** [comment]
Vyzkouším a uvidím :)

**Comment by DeetsCZ** [comment]
Prosím o úpravu, pokud jde o prvního přihlášeného administrátora, aby měl automaticky svou roli zaplacenou.. 
Děkuji
