### ISSUE TITLE
Obsazenost podakcí

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#424]
V tabulce rolí je sloupec obsazenost. 
![snimek obrazovky 2017-11-01 v 22 35 24](https://user-images.githubusercontent.com/19816092/32299197-01a783d0-bf55-11e7-8d6f-466198384090.png)

Prosím stejný sloupec vytvořit i pro podakce.

**Comment by jan-stanek** [comment]
To by neměl být problém, bude to fungovat stejně jako u rolí (zruším sloupec kapacita a pokud bude někde omezená, tak se vypíše ve tvaru 5 / 10)

**Comment by DeetsCZ** [comment]
Ok, děkuji

**Comment by DeetsCZ** [comment]
Děkuji
