### ISSUE TITLE
Tituly u lektora

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#425]
Prosím o přidání pole pro titul před jménem a za jménem do formuláře pro ručně přidaného lektora.

**Comment by jan-stanek** [comment]
Pro ručně přidané by to neměl být problém. Bude nutné je zahrnout do jejich displayname, takže se budou zobrazovat všude, kde se teď vypisuje jméno lektora ve tvaru "Příjmení Jméno (Přezdívka)".

**Comment by DeetsCZ** [comment]
Díky

**Comment by jan-stanek** [comment]
Jaký tvar by měl být u toho jména?

Používáme ten Příjmení Jméno (Přezdívka), ale moc nevím, jak do něj nacpat tituly. Když to otočím, tak se nám to bude špatně řadit v tabulce uživatelů a vůbec to nebude konzistentní.

**Comment by DeetsCZ** [comment]
Mohli bychom v seznamu uživatelů zachovat stávající zobrazení a tituly zobrazovat pouze ve frontendu?
Tedy například v přehledu programů:
![snimek obrazovky 2017-11-07 v 13 26 47](https://user-images.githubusercontent.com/19816092/32493816-8a3a4d68-c3bf-11e7-99e8-d256a9300e9d.png)
Zde by se mohlo zobrazovat **TitulPřed Jméno Příjmení TitulZa (Přezdívka)**

**Comment by jan-stanek** [comment]
Dobře, přidám tam něco jako lectorName a bude se tam vypisovat to.

Mají tam nějaký lektory, kteří se přihlašují přes skautIS? U nich se to projeví až po přihlášení znovu a budou to mít zatím nejspíš bez titulů, jestli je skautIS neumí nějak hezký vrátit.

**Comment by jan-stanek** [comment]
Teď je třeba u všech lektorů dát upravit a uložit, i když nemají žádný titul. Pokud se některý přihlašuje přes skautIS, tak je třeba, aby se znovu přihlásil (pokud by to byl velký problém, můžeme upravit ručně v DB).

U lektorů, kteří se přihlašují přes skautIS se tituly nenačítají. Asi by to nebyl takový problém, vypisovaly by se všechny, ale asi aspoň ve správném pořadí.

**Comment by DeetsCZ** [comment]
Ve formuláři pro ruční zadání nového lektora nejsou kolonky pro tituly:
![snimek obrazovky 2017-11-08 v 12 07 33](https://user-images.githubusercontent.com/19816092/32545955-a80d0632-c47d-11e7-91fe-46a7ea8e16c0.png)

**Comment by DeetsCZ** [comment]
Ve frontend se zobrazuje za jménem "," má nějaký důvod?
![snimek obrazovky 2017-11-08 v 12 15 46](https://user-images.githubusercontent.com/19816092/32546308-f1beb7ac-c47e-11e7-9375-c336f3297758.png)

**Comment by jan-stanek** [comment]
Tituly za jménem se oddělují čárkou, doufám, že všechny.

**Comment by DeetsCZ** [comment]
Děkuji
