### ISSUE TITLE
Výběr více lektorů u programu

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#426]
Bylo by možné, aby program mohl mít více lektorů? 
Vybírat multiselektem a na stránce o programu zobrazovat lektory pod sebou?

**Comment by jan-stanek** [comment]
Tahle změna má hodně velký dopad, pokud to není úplně nutné, tak bych se do toho teď nepouštěl.

**Comment by DeetsCZ** [comment]
Ok, necháme na později.

**Comment by jan-stanek** [comment]
Chce to promyslet, ten lektor se vypisuje na hodně místech a někde to není moc vhodné, aby tam byl dlouhý seznam lektorů. 

Možná by nemuslelo být špatné mít 1 hlavního lektora a pak další lektory. Třeba v harmonogramu by byl jen ten hlavní a pak v detailu by byli i ti ostatní.

**Comment by jan-stanek** [comment]
O kolik lektorů jim šlo, může se reálně stát, že jich tam bude třeba více než 3?

**Comment by DeetsCZ** [comment]
Nedokáži určit, jestli se může stát, že bude více lektorů, ale je to možné..

**Comment by DeetsCZ** [comment]
Děkuji
