### ISSUE TITLE
Chyba: počet zobrazených záznamů

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#427]
Na miquik jsem dala zobrazit všechny uživatele (téměř 1200 záznamů) a poté jsem chtěla vrátit na zobrazení po 50ti ale stránka na změnu nereaguje. Zkoušela jsem i tlačítko Resetovat filtr, ale také bez reakce.

**Comment by jan-stanek** [comment]
To by fungovat mělo, jen to asi bude trvat déle.

**Comment by DeetsCZ** [comment]
Nyní funguje
