### ISSUE TITLE
Export všech uživatelů

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#428]
Na miquik jsem zkoušela export všech uživatelů (omezen fitr pro ty, kteří mají nějakou podakci). Nechala jsem zobrazit všechny záznamy, vybrala export, ale nic se nestalo. Pro těch téměř 1200 záznamů to neprochází. Napadá tě nějaké řešení? 
Nebylo by možné přidat možnost "Exportovat všechny", aby se nemuselo zaškrtávat? I to zaškrtnutí trvalo velmi dlouho. Ikdyž náš problém to asi neřeší.
Nevím jestli by třeba nepomohlo přidat možnost zobrazit 500 záznamů? Třeba by těch 500 prošlo.. Dělat to po 50 by bylo zdlouhavé.

**Comment by jan-stanek** [comment]
Museli bychom mít pro každý export tlačítko.

Další možnosti pro počet jde určitě přidat.

**Comment by jan-stanek** [comment]
Upravil jsem možnosti, zkus prosím, co je ještě únosné. Jako minimum jsem dal 25, výchozích 10 mi přišlo strašně málo, případně vrátím.

**Comment by DeetsCZ** [comment]
Možná by místo tlačítka mohl být jen checkbox "Vybrat všechny" a potom by se vybíraly hromadné akce jako nyní.. Ale nevím, jestli by nám to pomohlo, neskončili bychom na stejné chybě?

Jinak export pro 500 uživatelů se provede, pro 1000 již ne. Tedy bych možnost zobrazit 1000 zrušila.

**Comment by jan-stanek** [comment]
to bohužel tabulka neumí

1000 zruším, myslím, že byl problém v tom, že prohlížeče nepodporují víc než 1000 polí ve formuláři

**Comment by jan-stanek** [comment]
Vedle tlačítka "přidat lektora" by myslím mělo jít přidat tlačítko s roletkovým menu. Do něj by se daly dát ty exporty všeho.

**Comment by DeetsCZ** [comment]
V tuto chvíli je export po 500 dostatečný, proto uzavírám.

**Comment by jan-stanek** [comment]
Možná už to příště bude knihovna umět, někdo se tam o to snaží.
