### ISSUE TITLE
Evidence příjezdu a odjezdu

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#43]
Do detailu uživatele přidat dvě pole "Příjezd" a "Odjezd", zadávat by se mělo výběrem z kalendáře.

Do správy rolí přidat checkbox, zda se má u dané role evidence zobrazovat (primárně se bude používat u role Lektor).

Pokud se bude u role příjezd a odjezd evidovat, potom bude čas odjezdu a příjezdu uživatel zadávat při registraci.

Pole je pouze informativní a nebude mít další návaznost.

**Comment by jan-stanek** [comment]
```ALTER TABLE `User` ADD `arrival` DATETIME NULL DEFAULT NULL AFTER `attended`, ADD `departure` DATETIME NULL DEFAULT NULL AFTER `arrival`;```

**Comment by jan-stanek** [comment]
Nedaří se mi zprovoznit kalendář pro zadávání datumu a času. Všechny novější pluginy vyžadují Nette 2.2+.

**Comment by jan-stanek** [comment]
Dojde k mírné úpravě formátu datumu, bude třeba znovu nastavit začátek, konec a konec v konfiguraci.

Pro srs.skauting.cz stačí spustit:
UPDATE Settings SET value="01.05.2013" WHERE 'item'="seminar_from_date";
UPDATE Settings SET value="03.05.2013" WHERE 'item'="seminar_to_date";
UPDATE Settings SET value="01.03.2016" WHERE 'item'="cancel_registration_to_date";

**Comment by DeetsCZ** [comment]
Databáze upravena

**Comment by DeetsCZ** [comment]
Děkuji za úpravu
