### ISSUE TITLE
Synchronizace akcí s vzdělávacími akcemi ve skautIS

### ISSUE THREAD

**Issue by jan-stanek** [skaut/SRS#433]
### Poznámky
**Společné**
- v současnosti se nebere ohled na přítomnost účastníka na akci - synchronizují se i ti, kdo se nakonec nezúčatnili
- není možné vybrat skautIS roli -> nemusí být přístup k akci
- jak zjistit, že má uživatel oprávnění upravovat účastníky akce?

**Vzdělávací akce**
- synchronizovat se bude: s jedním kurzem / s celou akcí (kurzy budou odpovídat našim podakcím)? 
- jaké parametry jsou u WS povinné? (https://test-is.skaut.cz/JunakWebservice/Events.asmx?op=EventEducationAll)
- hlídání kapacity akce
- dostávají uživatelé e-mail o odhlášení, je možné je při synchronizaci všechny odstranit a znovu přidat?

**Comment by jan-stanek** [comment]
Vylepšení
- [] přidat možnost zapnout přidávání účastníků VzA do skautIS už při přihlášení
- [] při vkládání hromadnou akcí označit účastníky ve skautIS jako schválené

Poznámky
- možná bude potřeba rozšířit oprávnění aplikace

**Comment by DeetsCZ** [comment]
Přidávám jen pro shrnutí celé zadání:
V nastavení srs bude možné namapovat akci (i její podakce) na vzdělávací akci ve skautis (případně i na více akcí).
Účastníci se budou vybírat v seznamu uživatelů a synchronizovat se budou přes hromadné akce do seznamu přihlášených účastníků. 
Před každou synchronizací proběhne kontrola, zda daný účastník již není v seznamu (není možné všechny účastníky smazat a poté přidat, protože systém odesílá účastníkům e-mail při změně).

**Comment by DeetsCZ** [comment]
Přidávám další detaily:
1. Splnění vstupních podmínek nebudeme řešit
2. Organizátor by měl mít dve možnosti, jak synchronizovat účastníky:
 a. jen do seznamu přihlášených
 b. do seznamu přihlášených a zároveň i přijatých

**Comment by jan-stanek** [comment]
Přidáno cachování seznamu rolí ze skautIS. Seznam se načítá jen při přihlašování a ne při každém pohybu v administraci, prosím o otestování.

**Comment by jan-stanek** [comment]
- [ ] přidat chybovou hlášku k vložení účastníků do skautIS, pokud není nastaveno propojení žádného kurzu s podakcemi
- [ ] vyřešit problém, který způsobují kurzy bez názvu

**Comment by jan-stanek** [comment]
Zobrazení názvu kurzu: typ[ - název]

**Comment by jan-stanek** [comment]
U většiny VzA je jen jeden kurz, pokud je také jen jedna podakce - nastavit automaticky propojení mezi nimi.

**Comment by jan-stanek** [comment]
@DeetsCZ Řešili jsme, že možnost přidávat účastníky nezávisí na stavu, ale na nějaké složité podmínce, kterou nejsem schopný přes API ověřit? Takže to bude řešené tak, že buď synchronizace projde, nebo ne.

Bylo by ale dobré, aby se v tom seznamu aspoň nenabízely akce, u kterých to nemá smysl - dávno uzavřené, zrušené, ... - daly by se vybrat stavy, které má smysl tam nabízet?

**Comment by jan-stanek** [comment]
Překlep v textu, který se bude nejspíš měnit, ...

"V **sezmanu** akcí jsou neuzavřené akce, ...."

**Comment by DeetsCZ** [comment]
Hotovo
