### ISSUE TITLE
Porovnávání string v MySQL

### ISSUE THREAD

**Issue by jan-stanek** [skaut/SRS#434]
Teď je porovnávání case insensitive a ignoruje diakritiku.

**Comment by jan-stanek** [comment]
http://www.ouchangjian.com/question/58c42fb1b84f50b06b58a20f

**Comment by jan-stanek** [comment]
Zatím víme jen o tomto problému: nemohou se přihlásit 2 uživatelé, kteří mají z tohoto pohledu stejný username.

**Comment by jan-stanek** [comment]
V mysql asi neexistuje case sensitive varianta, jen binární porovnávání, které by nám způsobilo problémy jinde - nastavím ho, jen na username.

**Comment by DeetsCZ** [comment]
Děkuji
