### ISSUE TITLE
Vyhledávání v účastnících programu

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#436]
Bylo by možné přidat vyhledávání uživatelů v seznamu uživatelů přihlášených/nepřihlášených na program:
![snimek obrazovky 2017-11-14 v 13 26 00](https://user-images.githubusercontent.com/19816092/32779986-0372b0e6-c940-11e7-86a8-9140ffb8a612.png)

**Comment by jan-stanek** [comment]
Stačí přidat filtr na sloupec v datagridu.

**Comment by petrparolek** [comment]
není priblém přidat, otázkou pár minut práce, můžu se do toho vrhnout

**Comment by jan-stanek** [comment]
Tabulka je tady: https://srs.skauting.cz/admin/program/blocks/detail/1 zobrazí se tlačítkem "Seznam oprávněných účastníků"

**Comment by petrparolek** [comment]
hotovo

**Comment by DeetsCZ** [comment]
Děkuji za zpracování
