### ISSUE TITLE
Odhlašování z akce

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#44]
1. V administraci do konfigurace přidat položku 
Odhlašování povoleno do: "datum"
(ideálně pod položku "Konec semináře")

2. V profilu přihlášeného uživatele přidat tlačítko "Odhlásit se ze semináře", které se zobrazuje do data, které je nastaveno v bodě 1

3. Pokud se uživatel odhlásí, potom se změní jeho role na "Nepřihlášený"

4. Pokud je uživatel v roli "Nepřihlášený", potom by se měla smazat i všechna jeho data vyplněná při registraci a pro účast na akci bude muset znovu vyplnit přihlášku. Tedy to bude jako kdyby se poprvé přihlásit na web. 
(Nyní jsou všechny informace o uživateli uloženy a zobrazuje se, že jeho přihláška byla již potvrzena:
![snimek obrazovky 2016-09-04 v 14 43 34](https://cloud.githubusercontent.com/assets/19816092/18231112/8b0ab5c8-72af-11e6-835c-8aeabc14a01c.png)

5. Stejně by se měl systém chovat, pokud se uživatel do role "Nepřihlášený" přesune v administraci.

**Comment by jan-stanek** [comment]
Pokud bude mít uživatel více rolí, má dostat na výběr, z jakých se chce odhlásit?

**Comment by DeetsCZ** [comment]
Tady je to myšleno odhlásit se úplně z akce, tedy by se mu měly odebrat všechny role..

**Comment by jan-stanek** [comment]
'''
INSERT INTO `Settings` (`id`, `item`, `value`, `description`) VALUES (NULL, 'cancel_registration_to_date', '2016-10-05', 'Odhlašování povoleno do');
'''

**Comment by DeetsCZ** [comment]
Databáze upravena..

**Comment by DeetsCZ** [comment]
Děkuji za zpracování
