### ISSUE TITLE
Nefunkční instalace release na Windows

### ISSUE THREAD

**Issue by jan-stanek** [skaut/SRS#441]
Nenačítají se první 2 migrace, kvůli špatným koncům řádků po stažení release z githubu.

**Comment by DeetsCZ** [comment]
@jan-stanek máš tohle otestované? Já to na windows nevyzkouším :)..

**Comment by jan-stanek** [comment]
Ne, od té doby nebyl nový release

**Comment by petrparolek** [comment]
Za mě se má vyvíjet na linuxu, Existují výborné nástroje - Vagant, Docker nebo přímo vyvýjet na Linuxu.

**Comment by jan-stanek** [comment]
Tady jde jen o EOL znaky v migracích, které github převede na LF.

**Comment by petrparolek** [comment]
to není o GitHubu, ale o nastavení Git klienta viz https://git-scm.com/book/cs/v1/Individu%C3%A1ln%C3%AD-p%C5%99izp%C5%AFsoben%C3%AD-syst%C3%A9mu-Git-Konfigurace-syst%C3%A9mu-Git#Form%C3%A1tov%C3%A1n%C3%AD-a-pr%C3%A1zdn%C3%A9-znaky

**Comment by jan-stanek** [comment]
tady se to děje při sestavování release pomocí travis

teď je to opraveno tak, že může být v souboru libovolný EOL

**Comment by jan-stanek** [comment]
otestováno
