### ISSUE TITLE
Přidání souboru do přihlášky

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#442]
Prosím o přidání možnosti "Nahrát soubor" mezi vlastní pole přihlášky (Nastavení->Přihláška).
Možnost by měla mít nastavení "Název" a "Typ nahrávaného souboru", například PDF, word, excel, atd. a mělo by být možné vybrat více možností najednou.
V přihlášce se potom zobrazí text "Název" a tlačítko "Vybrat soubor".

**Comment by DeetsCZ** [comment]
Chybí možnost vybrat typ souboru.
Po přidání souboru do přihlášky, není možné přihlášku odeslat (zkoušela jsem doc a txt):
<img width="965" alt="snimek obrazovky 2018-01-02 v 13 52 48" src="https://user-images.githubusercontent.com/19816092/34484348-7365546c-efc4-11e7-8615-009568921371.png">

**Comment by DeetsCZ** [comment]
Zobrazení souboru v přehledu je dobrý nápad, ale bylo by možné u uživatelů, kteří soubor nemají nahraný nezobrazovat odkaz pro stažení? 
Pokud tam souboru není, tak se tam zbytečně zobrazuje chyba:
<img width="1529" alt="snimek obrazovky 2018-01-02 v 13 57 06" src="https://user-images.githubusercontent.com/19816092/34484453-095486aa-efc5-11e7-8db8-6d0f41bdaa5c.png">

<img width="681" alt="snimek obrazovky 2018-01-02 v 13 58 51" src="https://user-images.githubusercontent.com/19816092/34484469-1a4b3594-efc5-11e7-991e-132155419c6b.png">

**Comment by jan-stanek** [comment]
Bez souboru to jde? Spíš to bude tím blokováním dvojitého odeslání.

Odkaz schovám.

**Comment by DeetsCZ** [comment]
Dala jsem soubor jako povinný a bez něj bylo sice tlačítko aktivní, ale nešla přihláška odeslat.. Vyzkouším..

**Comment by DeetsCZ** [comment]
Tak ten problem asi opravdu nesouvisí se souborem, založím vlastní issue..

**Comment by DeetsCZ** [comment]
Prosím o:
1. schvání odkazu v administraci, pokud uživatel nemá nahraný žádný soubor
2. prosím o zachování názvu nahrávaného souboru

**Comment by DeetsCZ** [comment]
Bylo by ještě možné, aby se v profilu uživatele zobrazoval aktuálně nahraný soubor?

**Comment by jan-stanek** [comment]
Nenapadá mě, jak ten soubor zobrazit, jedine to uděla podobně jako v administraci, že se formulář vypíše až po kliknutí na "upravit"

**Comment by jan-stanek** [comment]
Stávající soubory můžu dát maximálně někam mimo formulář. Za 2 večery jsem nepřišel na to, jak dostat do formuláře vlastní komponentu.

**Comment by jan-stanek** [comment]
Už asi vím, jak to udělám. O víkendu se k tomu snad dostanu.

**Comment by DeetsCZ** [comment]
Bylo by možné zobrazit název aktuálního souboru?
<img width="940" alt="snimek obrazovky 2018-02-05 v 18 22 38" src="https://user-images.githubusercontent.com/19816092/35818942-9f625d92-0aa1-11e8-99f5-65cb44d03bd9.png">

**Comment by jan-stanek** [comment]
Uvnitř pole to možné není. 

Nebylo by lepší prohodit tlačítko s polem pro výběr? Nejdřív aktuální soubor a potom možnost vybrat nový.

**Comment by DeetsCZ** [comment]
A nešlo by to rozdělit na dva řádky?  Pomohlo by to takto?

**Aktuální soubor:** "název"   Tlačítko "Stáhnout"
**Nahrát nový soubor:** Pole pro výběr 

Pokud to nejde nebo by to bylo zbytečné složité, tak to nechme, jak to je.. Bylo by fajn mít tam název souboru, ale pokud to nepujde, tak se bez toho nyní obejdeme. Díky

**Comment by jan-stanek** [comment]
Ještě tam musíš dát název toho pole

**Comment by DeetsCZ** [comment]
nešlo by to zobrazení souboru jako rozbrazujeme dokument na webu:
<img width="351" alt="snimek obrazovky 2018-03-01 v 10 53 30" src="https://user-images.githubusercontent.com/19816092/36838208-dd250d1e-1d3e-11e8-9c40-6c7903a7f2b0.png">

Je tam název jako odkaz pro stažení souboru..

**Comment by DeetsCZ** [comment]
a pod tím ta část pro nahrání nového..

**Comment by jan-stanek** [comment]
To půjde, na jeden řádek mi to nešlo, protože ten název může být libovolně dlouhý.

**Comment by DeetsCZ** [comment]
Teď je to naprosto ideální :) Děkuji
