### ISSUE TITLE
Automatický email při změně role uživatele

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#444]
Prosím o přidání dalšího automatického emailu a to při změně role uživatele. Email by se neměl posílat při první registraci, ale až při změně role jak z administrace tak i v profilu uživatele.

**Comment by jan-stanek** [comment]
Tenhle e-mail už máme, je společný se změnou podakcí. Stačí přidat i pro změnu z administrace.

**Comment by DeetsCZ** [comment]
Posílá se email i při změně v administraci?
Teď jsem zkoušela přidat uživateli druhou roli v adminisraci a email nepřišel.

**Comment by jan-stanek** [comment]
Měl by, volá se stejná funkce. Jestli jsi měla víc mailu za sebou, tak někdy přijde až za dýl.

**Comment by DeetsCZ** [comment]
Teď koukám, že problém bude jinde. 
Změna role v administraci se totiž vůbec neuloží.

**Comment by DeetsCZ** [comment]
Založila jsem nové issue, email se odesílá. Děkuji
