### ISSUE TITLE
Automatický email při změně vlastních polí

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#445]
Prosím o přidání automatického emailu, pokud si uživatel změní v profilu některé z vlastních polí z přihlášky. 
Email se bude odesílat na email akce.
V nastavení emailu by se kromě textu mělo zobrazovat upozornění **"Tento automatický email se bude odesílat na email pro mailing, který je vyplněný v nastavení mailingu"**

**Comment by jan-stanek** [comment]
Ať je to trochu univerzálnější, co přidat u všech automatických mailů zaškrtávací políčka - zaslat uživateli, zaslat pořadateli.

Mohlo by se to hodin i někde jinde, ne?

**Comment by DeetsCZ** [comment]
Dekuji
