### ISSUE TITLE
Přidání harmonogramu uživatele do detailu v administraci

### ISSUE THREAD

**Issue by jan-stanek** [skaut/SRS#449]
V profilu uživatele je tabulka s harmonogramem uživatele. Ta samá tabulka by měla být i v detailu uživatele v administraci.

**Comment by jan-stanek** [comment]
Bylo by vhodné vytvořit komponentu a neopakovat stejný kód.

**Comment by DeetsCZ** [comment]
V hromadném exportu harmonogramu je chybka s posunem sloupců, ve sloupci do je název:
<img width="660" alt="snimek obrazovky 2018-10-05 v 13 11 53" src="https://user-images.githubusercontent.com/19816092/46532238-4e5f6f80-c8a0-11e8-8601-c7364130e037.png">

**Comment by DeetsCZ** [comment]
Děkuji
