### ISSUE TITLE
Zkontrolovat automatické e-maily

### ISSUE THREAD

**Issue by jan-stanek** [skaut/SRS#457]
Některé automatické e-maily se posílají jen pokud akci provede uživatel sám, jiné pokud se provede i v administraci. Bylo by dobré to sjednotit / upozornit na to / umožnit nastavit.

[Popis aktuálního stavu](https://github.com/skaut/SRS/wiki/Administrace-Mailing#automatick%C3%A9-e-maily)

**Comment by jan-stanek** [comment]
Mělo by být opraveno, viz popis.

**Comment by DeetsCZ** [comment]
Děkuji
