### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by jan-stanek** [skaut/SRS#464]
Budeme aktualizovat na bootstrap 4? (https://getbootstrap.com)

**Comment by DeetsCZ** [comment]
Určitě by bylo dobré mít vše aktuální. Vidíš v tom teď nějaký zádrhel?

**Comment by jan-stanek** [comment]
Zatím vím jen to, že vyšel, možná teprve beta. Uvidíme, jestli to bude mít nějaký přínos a není jen lepší responzivita.

**Comment by DeetsCZ** [comment]
Dokud je to jen beta, tak bych to určitě neřešila..

**Comment by petrparolek** [comment]
Bootstrap 3 bude léta postačovat, nic převratného ve 4 není

**Comment by jan-stanek** [comment]
Už není beta...

Počkáme až bude rendered pro formuláře: https://github.com/nextras/forms/issues/53

**Comment by adaamz** [comment]
bootstrap 4 ma hlavne flexboxy a rem jednotky

**Comment by jan-stanek** [comment]
@adaamz přinese nám to něco, když máme stejně responzivitu vypnutou kvůli fullcalendaru?

**Comment by petrparolek** [comment]
myslím si, že nic nepřinese

**Comment by adaamz** [comment]
nevim co mate za problem s full calendar, nicmene by bylo potreba projit stranku po strance a zkontrolovat jestli vse sedi (spis asi nebude)

**Comment by jan-stanek** [comment]
Bylo by dobré web rovnou přizpůsobit pro použití na mobilu. Původně se s touhle možností moc nepočítalo kvůli tomu, že fullcalendar na mobilu moc použitelný není. Většina akcí SRS pro zapisování programů používala, teď už je možná více akcí, které používají jen přihlašování.
