### ISSUE TITLE
Chyba: odeslání přihlášky

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#473]
Pokud při vyplnění přihlášky nezadám některé povinné pole, potom se správně zobrazí chyba, ale po vyplnění povinného pole se zneaktivní tlačítko pro odeslání a přihlášku již není možné odeslat:
<img width="1174" alt="snimek obrazovky 2018-01-02 v 14 09 32" src="https://user-images.githubusercontent.com/19816092/34484662-96a38e06-efc6-11e7-94c6-2ff0d62200a7.png">

**Comment by jan-stanek** [comment]
Máš poslední verzi? Mělo by to být opravené (#462).

**Comment by DeetsCZ** [comment]
Aktualizovala jsem a je to v pořádku, jen je tam trochu větší prodleva při odesílání a je to trochu zvlaštní, když se zneaktivní to tlačítko.
Nešlo by nějak zkrátit tu odezvu?

**Comment by jan-stanek** [comment]
Na prodlevu by to nemělo mít žádný vliv, jen se to tlačítko dá disabled po prvním stisknuti při kterém je formulář správně vyplněn.

**Comment by DeetsCZ** [comment]
Toto je již v pořádku, děkuji
