### ISSUE TITLE
Chyba: role uživatele

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#474]
V přihlášce jsem uživateli vybrala roli Účastník. Po odeslání se mu ale zobrazuje potvrzení pro role Nepřihlášený a Účastník:
<img width="1206" alt="snimek obrazovky 2018-01-02 v 14 05 14" src="https://user-images.githubusercontent.com/19816092/34484710-00f2bdcc-efc7-11e7-99c5-45c301bbc319.png">

Role se zde zobrazuje správně.

Po dalším přihlášení má ale uživatel obě role a znovu může vyplnit přihlášku:
<img width="1202" alt="snimek obrazovky 2018-01-02 v 14 13 36" src="https://user-images.githubusercontent.com/19816092/34484738-2c75d718-efc7-11e7-83a2-a57f451e6d43.png">

**Comment by jan-stanek** [comment]
Zvláštní, při testování se mi to nestávalo, podívám se na to.

**Comment by DeetsCZ** [comment]
Dala jsem u uživatele odhlásit ze semináře a ikdyž to vypadalo, že odhlášení proběhlo v pořádku, tak u něj role zůstaly:
<img width="411" alt="snimek obrazovky 2018-01-02 v 23 00 35" src="https://user-images.githubusercontent.com/19816092/34501831-f657b63e-f010-11e7-87e7-2b6df88b26ec.png">


Opětovné vyplnění přihlášky zobrazí chybu serveru..

**Comment by DeetsCZ** [comment]
Děkuji, vypadá to, že se podařilo opravit
