### ISSUE TITLE
Chyba: změna role v administaci

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#475]
Pokud dám upravit role uživatele v administraci a jedna z nových rolí je Nepřihlášený, potom se změna neuloží. Jiné kombinace rolí fungují.
Nejsem si jistá jestli to není schválně, kvůli odhlašování?

**Comment by jan-stanek** [comment]
To je správně, jen koukám, že se nemá kde zobrazit chyba, jak se ten formulář zavře.

Ideální by bylo tam tu roli nemít vůbec na výběr, ale to nejde, když už ji má.

**Comment by DeetsCZ** [comment]
Tam tedy bude potřeba doplnit nějaké chybové hlášení.
Škoda, že to nejde odebrat z toho výběru.

**Comment by jan-stanek** [comment]
Zkusím to upravit aby při neúspěšně validaci formulář nezmizel. Podobný problém je u inline editací v tabulkách, tam je to řešeno hláškou mimo.

**Comment by jan-stanek** [comment]
Kdyby se zakázaly úpravy v tomhle formuláři u nepřihlášených uživatelů, tak by se dala i odebrat.

**Comment by DeetsCZ** [comment]
To by podle mne nebylo dobře, pokud budou chtít někomu přiřadit roli přes administraci, tak by to potom nešlo..
Možná nepovolit uložení, pokud je vybraná role Nepřihlášený a zobrazit chybu..

**Comment by jan-stanek** [comment]
To je pravda, zkusím udělat, aby se ten formulář při chybě neschoval a zůstal tam s chybou.

**Comment by DeetsCZ** [comment]
Děkuji
