### ISSUE TITLE
Automatické testování a CI

### ISSUE THREAD

**Issue by jan-stanek** [skaut/SRS#479]
Bylo by dobré...

**Comment by petrparolek** [comment]
Velmi mi vše usnadnilo a odhalilo spoustu chyb.

**Comment by jan-stanek** [comment]
Při tom bychom mohli ještě přesunout všechny činnosti na jeden CI nástroj (kvůli jednotnosti s dalšími projekty spíš wercker, pokud tam vše půjde) a nastavit deploy na srs.skauting.cz

**Comment by jan-stanek** [comment]
Začal bych akceptačními testy na nejkritičtější akce - přihlášování účastníků a změny přihlášek

**Comment by jan-stanek** [comment]
Založen http://test-srs.skauting.cz/, kam by se měl nahrát vždy aktuální obsah master větve

**Comment by jan-stanek** [comment]
Na https://test-srs.skauting.cz/ se nahrává vždy aktuální master větev

**Comment by jan-stanek** [comment]
Uzavírám CI, na testy vytvořím nové issue
