### ISSUE TITLE
Chyba: pokud aktivní email nemá zaškrtnutého příjemce

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#481]
Na webu Navigamusu se objevila chyba:
Pokud změním v administraci roli uživateli a zaškrtunu schválená, potom se po uložení zobrazí chyba.

Nejprve tam byla chyba:

[2018-01-08 12-37-55] Nette\Mail\SendException: Unable to send email. in /home/vu009740/vendor/nette/mail/src/Mail/SendmailMailer.php:50  @  https://registrace-navigamus.skauting.cz/admin/users/detail/25  @@  exception--2018-01-08--10-09--57259c7db4.html

To jsem si všimla, že není vyplněný smtp v config, tak jsem přesně zkopírovala z srs.skauting.cz, ale nyní je tam stále chyba ikdyž trochu jiná:

[2018-01-08 12-38-58] Nette\Mail\SmtpException: SMTP server did not accept DATA with error: 503 Must have valid receiver and originator in /home/vu009740/vendor/nette/mail/src/Mail/SmtpMailer.php:190  @  https://registrace-navigamus.skauting.cz/admin/users/detail/25  @@  exception--2018-01-08--12-38--5d728d0b4f.html

**Comment by DeetsCZ** [comment]
Nevím, jestli to má nějakou váhu, ale bylo nastaveno, že email je aktivní ale nebylo zaškrtnuté odesílání administrátorovi ani uživateli..
(po zakázání tohoto automatického emailu funguje)

**Comment by jan-stanek** [comment]
Tím to bude, snaží se odeslat e-mail bez příjemce. Do budoucna by asi bylo lepší mít ty políčka 3 - účastníkovi, uživateli, organizátorovi. Tím by to pokrylo i ty změnu e-mailu. Pak by bylo povinné zaškrtnout aspoň jednu možnost.

**Comment by DeetsCZ** [comment]
Za mně by tam "Ověření změny e-mailu semináře" nemělo vůbec být. Když to někdo omylem vypne, tak nepůjde změnit email, tam bych volbu vůbec nedávala.
Rozdělení účastník a uživatel je hrozně matoucí, protože to u jiných emailů nedává úplně smysl.
Já bych tedy odebrala možnost "Ověření změny e-mailu semináře" (to se bude posílat vždy) a u aktivních emailů bych nechala povinně zaškrtnout minimálně jednu variantu (účastník nebo organizátor nebo obojí).

**Comment by jan-stanek** [comment]
Ono je to tam jako systémový e-mail a vypnout nejde, ne? Není problém ho ani odfiltrovat z tabulky.

Co to znamená by se tam vysvětlilo, ale teď nevím, jestli to má u nějakýho mailu smysl, aby se posílal tomu, kdo změnu provedl. Spíš by se možná hodilo poslat ho ostatním lidem v nějaký roli, jako má třeba skautIS že pošle všem vedoucím, když někomu změním časopis.

**Comment by DeetsCZ** [comment]
No to by asi bylo hezké, ale možná zbytečné. Musel by tam být nějaký výběr, které roli se to má nebo nemá posílat. 
Podle mne si to zbytečně komplikujeme. Šla bych opravdu tou jednodušší cestou.
U automatického emailu pro změnu emailu si nedokáži představit, že by ho někdo nechal posílat i účastníkům :D a vlastně mi ani nedává úplně smysl, že by se posílal na ten původní email organizátorů, když se jedná pouze o potvrzení, že nově vyplněný email existuje.
A u ostatních, které jsou aktivní, bych nechala povinně vybrat alespoň jednu variantu.

**Comment by jan-stanek** [comment]
Ok, vynutim alespoň jedno a skryjí systémové

**Comment by DeetsCZ** [comment]
Děkuji
