### ISSUE TITLE
Zobrazení pouze "aktivních" VS

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#487]
Při pohledu na přehled uživatelů navigamusu mne napadlo, že by bylo dobré, kdyby se v přehledu nezobrazovali VS, kde byla registrace zrušena:
<img width="551" alt="snimek obrazovky 2018-01-10 v 12 57 29" src="https://user-images.githubusercontent.com/19816092/34771788-14f6a1ae-f606-11e7-879f-433cfbb77568.png">

<img width="918" alt="snimek obrazovky 2018-01-10 v 12 57 10" src="https://user-images.githubusercontent.com/19816092/34771793-17e77564-f606-11e7-8d7f-2d6aa1a1efc0.png">

Zobrazovala bych pouze ty, kde je stav čeká na platbu a zaplaceno, co myslíš?

**Comment by jan-stanek** [comment]
Dal bych všechny nezrušené. Vyhledávání bych ale nechal i v těch zrušených.

**Comment by DeetsCZ** [comment]
Souhlas..

**Comment by DeetsCZ** [comment]
Vypadá to dobře děkuji
