### ISSUE TITLE
Chyba: uživateli se nenačítá celá stránka

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#489]
Uživatel: Pěnička Jakub (Barbušák) nám nahlásil problém: po přihlášení nevidí celou stránku:
![noname](https://user-images.githubusercontent.com/19816092/35065337-49be5d88-fbcd-11e7-90ff-0d045a1c2f12.png)

**Comment by DeetsCZ** [comment]
Chyba mohla být v tom, že byl v databázi navázaný na neexistující závod.
Čekáme na potvzení, protože chybu vidí pouze on.

**Comment by jan-stanek** [comment]
To je asi vedle :-)

**Comment by DeetsCZ** [comment]
hups :D

**Comment by DeetsCZ** [comment]
Uzavírám, patří k webu závodů :)
