### ISSUE TITLE
Omezit kapacitu role

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#5]
U každé role je nyní možné zadat od kdy do kdy se do ní dá registrovat:
![snimek obrazovky 2016-08-03 v 15 05 14](https://cloud.githubusercontent.com/assets/19816092/17366476/bff03f70-598b-11e6-8901-67ed4ed2de02.png)

Prosím přidejte možnost definovat i kapacitu (kolik lidí se do role může přihlásit).

**Comment by jan-stanek** [comment]
ALTER TABLE `role` ADD `usersLimit` INT NULL DEFAULT NULL AFTER `registerableTo`;

**Comment by DeetsCZ** [comment]
Omezení funguje.
Jen mne napadá, že nyní pokud je vyčerpaná kapacita, tak role zmizí ze seznamu:
![snimek obrazovky 2016-08-25 v 14 37 18](https://cloud.githubusercontent.com/assets/19816092/17969266/922f6384-6ad1-11e6-908b-2d6caf4d4d77.png)
(testovano na roli účastník)
Lepším řešením by bylo nechat v seznamu rolí, dovolit ji vybral, ale při pokusu uložit vypsat "Překročena kapacita"..

**Comment by DeetsCZ** [comment]
Testovala jsem řešení, ale pokud se mění role v tabulce u spodního uživatele, potom je trochu nepřehledné, že chybové hlášení je nahoře. 
Napadají mne dvě řešení:
1. chybové hlášení vypsat v tabulce přímo u záznamu, který se uživatel snaží uložit
2. chybové hlášení zobrazit ve vyskakovacím okně

Pokud je to technicky možné, tak prosím o první řešení.

**Comment by DeetsCZ** [comment]
Řešení vypadá dobře a je funkční. Děkuji
