### ISSUE TITLE
Generování dokladů z latte šablony

### ISSUE THREAD

**Issue by jan-stanek** [skaut/SRS#502]
Používané kníhovny jsou abandoned. U náhrady se mi nepodařilo nastavit stejný font jako používáme, s jiným fontem se formulář rozhodí.

Bude také jednodušší úprava formulářů, půjde je udělat hezčí, ... Stejný způsob využijeme v elektronických vstupenkách.

**Comment by petrparolek** [comment]
nechal bych ty nevyvýjené knihovny, sám používám např. mrtnzlml/testbench, v případě problémů se dá všechno forkovat a použít svůj fork

**Comment by jan-stanek** [comment]
Fork existuje, ale v jejich verzi se mi nepodařilo nastavit vlastní font.

Hlavně to ale není moc praktické, pdf se generují tak, že máme pdf s prázdným formulářem a tam se na přesnou pozici dopisují texty. Zatím se takhle generují jen doklady (2 pdf), ale v budocnu přibydou ještě další dokumenty, tak bych na to přešel až se budou přidávat ty další.

**Comment by jan-stanek** [comment]
Lze použít něco jako: https://github.com/Joseki/PdfResponse a mpdf

**Comment by petrparolek** [comment]
jsem rád, že jsi to tu dal,cojsem ti radil

**Comment by jan-stanek** [comment]
Ideálně přejít co nejdříve, stávající knihovny nejsou kompatibilní s php 7.3

**Comment by petrparolek** [comment]
a nette 3, klidně se toho ujmu a nasadil bych i Twitter Bootstrap 4, protože nový ublaboo datagrid 6.x nepodporuje BS 3

**Comment by jan-stanek** [comment]
@DeetsCZ můžeme zavřít?

**Comment by jan-stanek** [comment]
doklady se generují, když si bude někdo stěžovat na chybějící údaje apod., vytvoříme nové issue
