### ISSUE TITLE
Automatické párování plateb

### ISSUE THREAD

**Issue by jan-stanek** [skaut/SRS#509]
Zatím jen místo pro poznámky...

Asi bude možné jen pro FIO. 

U open banking bude nejspíš potřeba mít přidělený certifikát od ČBA nebo jiné autority. Evropské standardy mají být hotové až v roce 2019. Existuje český standard (https://www.czech-ba.cz/sites/default/files/cesky-standard-pro-open-banking/ceskystandardproopenbankingv021.pdf), podpora zatím asi jen u KB. 

U přihlášek evidovat zaplacenou částku místo zaplaceno/nezaplaceno.

**Comment by jan-stanek** [comment]
Open banking se nejspíš odkládá a popis českého standardu už je nedohledatelný...

**Comment by petrparolek** [comment]
já mám reguální výraz pro čtení emailů z KB vlastní výroby, pokud je zájem

**Comment by jan-stanek** [comment]
Díky, zatím to asi není úplně aktuální, kdyžtak pak dáme vědět.

**Comment by DeetsCZ** [comment]
Jen schrnu, jak by mělo fungovat:
1. přidání tabulky plateb
 - platby se přidávají automaticky párováním z banky (zatím pouze FIO), z exportu plateb z banky ve formátu CSV, nebo po jedné ručně
2. platby se párují s tabulkou uživatelů podle VS a částky
- pokud souhlasí vytvoří se propojení a u uživatele je zaznamenáno, že má poplatek urazený
- pokud souhlasí jen VS, ale ne částka, potom se platba nespáruje, ale vytvoří se spojení s uživatelem
- pokud platba není identifikována vůbec potom se označí jako nespárovaná
3. Platby je možné řadit podle VS, jména, stavu (spárováno, nespárováno)

**Comment by jan-stanek** [comment]
CSV bych alespoň zatím neimplementoval, každá banka má jiný formát

**Comment by jan-stanek** [comment]
platba může být i za více uživatelů a přihlášek dohromady - bude se vypisovat něco jako:

Příjmení Jméno (Přezdívka) - 123456, 123457; Příj Jm - 123458

s řazením podle toho je podobný problém jako u podakcí a rolí

**Comment by jan-stanek** [comment]
stavy budou - spárováno (automaticky), spárováno (ručně), nespárováno (nesouhlasí cena), nespárováno (neexisutjící VS)

podle stavu půjde filtrovat, řadit podle kategorických hodnot nemá moc smysl, ne?

**Comment by jan-stanek** [comment]
Měli bychom odebrat možnost změnit VS přihlášky, jinak s tím budou problémy při párování

**Comment by jan-stanek** [comment]
Všechny platby zadávané do této tabulky budou jen platby na účet? Nebo se tam mají zadávat i hotovostní?

**Comment by DeetsCZ** [comment]
Z prvního testování prosím o:

1. načítání z FIO se mi nepovedlo rozchodit
2. pokud je přidaný token v nastavení, potom by se měla zobrazit hláška "Token byl uložen"
3. pokud je to možné, tak by bylo lepší, kdyby byl token při zápisu viditelný
4. pokud je token uložen, bylo možná dobré, kdyby v nastavení přibylo tlačítko "Odpojit token"
5. v nastavení by se mělo být i nastavení od kdy se mají platby načítat, ideálně možnost zadat datum
6. pokud se budou párovat platby tak by se u spárované platby mělo uložit placeno přes účet
7. platby hotovostí se do tabulky plateb zadávat nebudou
8. pokud je to možné a jde zjistit, že zadaný token není platný, potom by se mělo zobrazit chybové hlášení "Zadaný token není platný"
9. pokud to půjde, tak pokud token skončila platnost, tak by se opět měla zobrazit hláška "Zadaný token není platný" (eventálně pokud je to dost chytré tak přímo hlášku "Platnost zadaného tokenu skončila"

**Comment by jan-stanek** [comment]
Pro kontrolu by se měla cronem spouštět: action/bank/check (např. https://srs.skauting.cz/action/bank/check)

**Comment by DeetsCZ** [comment]
Z testování:

1. nenačítají se nové příchozí platby (testováno přes "https://srs.skauting.cz/action/bank/check")..
2. platby se napárují s uživateli:

Platba:
<img width="1048" alt="snimek obrazovky 2018-10-16 v 15 35 06" src="https://user-images.githubusercontent.com/19816092/47020322-687b3680-d159-11e8-896e-721f6960b560.png">

Objednávka:
<img width="886" alt="snimek obrazovky 2018-10-16 v 15 35 24" src="https://user-images.githubusercontent.com/19816092/47020303-5c8f7480-d159-11e8-9666-889d11f39d0d.png">

**Comment by DeetsCZ** [comment]
Děkuji

Ještě se platby nenacitaji automaticky (přes cron), ale ručně odkaz funguje, nutno dořešit s @sinacek

**Comment by DeetsCZ** [comment]
Děkuji
