### ISSUE TITLE
Přidat hlášku upozorňující na zakázanou editaci harmonogramu

### ISSUE THREAD

**Issue by jan-stanek** [skaut/SRS#510]
Na stránku s editací harmonogramu přidat informaci, pokud není povolena editace harmonogramu v Nastavení -> Program -> povolit úpravu harmonogramu semináře.

Například nad kalendář jako bootstrap alert typu warning.

Podobně jako tady:
![198d2f58-8990-4c54-8719-2928f51b83ad](https://user-images.githubusercontent.com/11959693/36646768-798a4518-1a7c-11e8-9ee5-5d239bc1c7ae.png)

Text: "Úprava harmonogramu není povolena." ??? @DeetsCZ

**Comment by DeetsCZ** [comment]
Hláška vypadá dobře, ale bylo by fajn ji doplnit o větu: "Úpravy můžete povolit v Nastavení->Program."

**Comment by DeetsCZ** [comment]
Výborně, odkaz do nastavení je výborný nápad. Děkuji
