### ISSUE TITLE
Refactoring od začátku - současný chaos

### ISSUE THREAD

**Issue by petrparolek** [skaut/SRS#512]
Nejradši bych aplikaci napsal od začátku, nemá žádný koncept a stal se z toho chaos i ergonomie ovládání je belmi neintuitivní. Podle mě je potřeba si říct, co má aplikace umět a porom s rozmyslel v budoucnu aplikaci rozšiřovat

**Comment by jan-stanek** [comment]
Máš na mysli nějaké konkrétní připomínky, podle nichž by se mohl systém vylepšit?

Za systémem samozřejmě jsou možná stovky hodin analýz. Složitost je z velké části dána tím, že jej používají různé akce s rozmanitými požadavky a business procesy.

Další změny potom reflektují zpětnou vazbu jednotlivých akcí a až na jeden větší zásah (podakce) si nevybavují, že by se dělaly nějaké zásadnější změny měnící základ systému. Takový rozvoj mi přijde přirozený u všech informačních systémů.

**Comment by DeetsCZ** [comment]
Tohle je věc, kterou bychom určitě mohli probrat a podívat se na možnosti, pokud by například nedalo nějak optimalizovat databázi, atd.. Ale to bychom měli probrat a rozmyslet mimo github a sem zakládat až připravé zadání. Proto zde uzavírám, ale píši si do podkladů pro další diskuzi.
