### ISSUE TITLE
v baliku SRS chybi slozka vendor

### ISSUE THREAD

**Issue by lbsotek** [skaut/SRS#513]
Ahoj,
bez slozky vendor neni mozne SRS provozovat, je mozne tento adresar doplnit?

Dik
Sotek

**Comment by jan-stanek** [comment]
Ahoj, 
složka vendor se vytvoří přes composer, nebo si můžeš stáhnout kompletní instalační balíček z releases: https://github.com/skaut/SRS/releases (SRS.zip)

Honza

**Comment by lbsotek** [comment]
Super - zkusim pouzit to ze SRS.zip
jen ze zvedavosti - jak se composer pouziva pri instalaci SRS na web Lebedy? (nevim, jak ho pres web spustit - nebo je tam i nejaky ssh pristup?)

**Comment by jan-stanek** [comment]
Zatím se spouští lokálně a jen se to nahraje přes FTP. Jde to i přes SSH, ale zatím jsem nezkoušel.

**Comment by lbsotek** [comment]
diky - issue zaviram

Sotek
