### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by jan-stanek** [skaut/SRS#533]
Upravit deploy tak, aby nepřepisoval soubory, které může uživatel upravovat.

**Comment by jan-stanek** [comment]
@DeetsCZ domluvili jsme se na nějaké úpravě?

Pokud dělají deploy různí lidě, tak je třeba hlídat, jestli tam nemají vlastní úpravy. 

Úprava jednoho CSS se dá zkontrolovat ručně, ale pokud si někdo upravuje i něco dalšího, měl by si deploy dělat sám, případně to mít někde ve vlastním forku na gitu.

**Comment by DeetsCZ** [comment]
Navrhuji z deploy odebrat ten jeden soubor s CSS, aby se neprepisoval a zbytek nechat jak je. Pokud má někdo schopnosti si zadávat úpravy i jinam, potom by měl být schopný si i instalovat aktualizace přes github sám.

**Comment by jan-stanek** [comment]
do deployment.ini.sample přidán `/www/css/web/style.css`, teď si to ještě musíš aktualizovat ve svých deployment.ini souborech

**Comment by DeetsCZ** [comment]
Po úpravě a deploy se zobrazuje server error:
[2018-10-05 12-34-30] WebLoader\FileNotFoundException: Neither 'web/style.css' or '/home/vu008925/www/css/web/style.css' was found in /home/vu008925/vendor/janmarek/webloader/WebLoader/Nette/Extension.php:232  @  https://srs.skauting.cz/  @@  exception--2018-10-05--12-34--09d643269c.html

**Comment by DeetsCZ** [comment]
Po doplnění souboru css již funkční.
Děkuji
