### ISSUE TITLE
Zákaz odebrání implicitní podakce

### ISSUE THREAD

**Issue by jan-stanek** [skaut/SRS#534]
@DeetsCZ řešili jsme po skypu, jestli zakázat odebrání implicitní podakce (uživateli), nebo přidat podmínku, že každý uživatel musí mít minimálně jednu podakci

**Comment by DeetsCZ** [comment]
Prosím o druhou možnost, tedy pokud má uživatel pouze jednu podakci, potom nebude možné ji odebrat. Děkuji
