### ISSUE TITLE
Chyba: nespouští se instalace

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#54]
Zkoušela jsem si nainstalovat srs podle wiki návodu (https://github.com/skaut/SRS/wiki/Instala%C4%8Dn%C3%AD-p%C5%99%C3%ADru%C4%8Dka), bohužel jsem skončila na bodu 5, kdy se po zkopírování souborů na FTP a změně práv nespustí instalační průvodce, jak je v popsáno v 6 bodě návodu. Zobrazí se pouze prázdná stránka:
![snimek obrazovky 2016-09-24 v 15 06 07](https://cloud.githubusercontent.com/assets/19816092/18808667/82aed698-8268-11e6-88d7-085fb65ea540.png)

Prosím o kontrolu návodu a jeho aktualizaci, aby podle něj bylo možné systém nainstalovat..

**Comment by jan-stanek** [comment]
Na localhostu s tím nemám problém, mohl bych vyzkoušet rovnou na testweb?

Archiv máš stažený z gitu? V něm chybí knihovny, měla by se zobrazit chyba, ale jejich zobrazování je tam asi defaultně vypnuté.

**Comment by DeetsCZ** [comment]
Archiv mám stažený z gitu, pokud tam chybí knihovny, potom by bylo dobré je doplnit nebo dopsat do návodu, jak je získat. 
Přístup do testweb jsem ti poslala, je možné tam postup vyzkoušet..

**Comment by jan-stanek** [comment]
Děkuji za přístup

Návod jsem upravil, průvodce se spouští, více jsem nezkoušel (nemám skautIS appID), ale neměl by s tím být problém.

Pokud by se v budoucnu vydávaly nějaké větší verze, tak by bylo lepší připravit rovnou archiv včetně knihoven.

**Comment by DeetsCZ** [comment]
Děkuji, nyní instalace běží.
Bylo by přece jen možné, abys knihovny rovnou do archivu přidal? Instalaci podle návodu budou dělat i ne úplně zdatní uživatelé a práce s příkazovým řádkem by pro ně mohla být příliš.. Potřebujeme návod i samotnou instalaci co nejvíce zjednodušit.

**Comment by jan-stanek** [comment]
Můžu je odstranit z gitignore a mít je nahrané na gitu.

**Comment by jan-stanek** [comment]
Nahráno, návod upraven.

**Comment by DeetsCZ** [comment]
Nyní instalace skončí chybou:
![snimek obrazovky 2016-09-25 v 18 17 26](https://cloud.githubusercontent.com/assets/19816092/18816532/6cd6c4e0-834c-11e6-8628-62df10ca3888.png)

**Comment by jan-stanek** [comment]
Tak to vypadá, že to takhle nepůjde, některé knihovny mají v sobě svůj .gitignore a na git se nenahrají všechny soubory.

Ještě můžu nechat stahování přes composer a příkaz uložit do bat/sh skriptu.

**Comment by jan-stanek** [comment]
Vytvořen skript pro stažení knihoven, návod upraven.

**Comment by JindrichPilar** [comment]
Pokud by se k instalacim pouzivali releasy a ne zip z masteru, tak muzes
archiv s knihovnama pridat rucne a nebo nechat automaticky vygenerovat k
releasu.

https://help.github.com/articles/creating-releases/

https://docs.travis-ci.com/user/deployment/releases

**Comment by jan-stanek** [comment]
Díky, vyzkouším

**Comment by DeetsCZ** [comment]
Instalace i návod je nyní v pořádku. 

Budeš ještě upravovat, nebo mám toto issue uzavřít?

**Comment by jan-stanek** [comment]
Po domluvě přidán zip s knihovnami. Návod upraven.

**Comment by DeetsCZ** [comment]
Řešení je funkční, ale má drobnou vadu:

![snimek obrazovky 2016-09-27 v 8 54 18](https://cloud.githubusercontent.com/assets/19816092/18863188/5f2c8092-8490-11e6-997e-42916033c15f.png)

Navrhuji knihovnu vytvořit zip pouze ze složky global a do návodu dopsat, aby po rozbalení složku global přesunuli do libs..

**Comment by jan-stanek** [comment]
Upraveno

**Comment by DeetsCZ** [comment]
Dva pokusy instalace proběhli bez problému, ale nyní mi další pokus vypisuje chybu:
![snimek obrazovky 2016-10-10 v 14 56 07](https://cloud.githubusercontent.com/assets/19816092/19249783/80388f7c-8f37-11e6-9614-72d1a03b9466.png)

**Comment by jan-stanek** [comment]
Návod upraven

**Comment by jan-stanek** [comment]
@JindrichPilar Nahrávání releasů mi funguje, ale nedaří se mi doplnit žádné soubory (složku, která je v .gitignore, ani zip s knihovnami, který jen není sledovaný). Nevíš v čem by mohl být problém?

.travis.yml: https://github.com/skaut/SRS/blob/travis/.travis.yml

**Comment by JindrichPilar** [comment]
Takhle od oka to nastaveni vypada spravne.  Je repozitar skaut/SRS napojen na travis-ci.org? (org je pro verejne projekty, com pro privatni)


Jinak ten zip muzes klidne generovat take na travisu https://docs.travis-ci.com/user/languages/php Muzes tak mit jistotu ze k distribuci davas knihovny vhodne pro deployement a u sebe mas vhodne pro vyvoj.

Muzes tam tak mit naporad nastavene ``composer install --no-dev --prefer-dist --optimize-autoloader --ignore-platform-reqs`` (To posledni je tam protoze travis nemusi mit nektere php extenstions, ty ale k vytvoreni zipu nepotrebujes).

**Comment by jan-stanek** [comment]
Děkuju, napojen na travis-ci.org není, myslel jsem, že to k tomu není potřeba. Jdu sehnat oprávnění.

Zip ani vytvářet nepotřebuju, ideální by bylo, kdyby se knihovny nahrály do libs/global/.

**Comment by JindrichPilar** [comment]
Ano, je to potreba jinak nikdo nebude delat cos nadefinoval v .travis.yml :) Asi si uplne nerozumime k cemu ten travis je.

Git repositar je na kod, pro vyvojare. Ve chvili kdy mas kod ve stadiu ktere chces vydat (nemas nic rozpracovaneho a vsechno funguje), tak na githubu das vytvorit release - tady pres webovku, ne pres git tag v command line. (on vytvori tag sam) 
Travis je sluzba ktera ceka na upozorneni od githubu ze se neco stalo (pushnul jsi zdrojaky, prijal pull request, vydal release apod). Ve chvili kdy se tak stane on udela git clone repozitare na svuj server a provede veci nadefinovane v ``.travis.yml``. Coz muze byt treba spusteni testu a nebo vytvoreni release.  

V pripade vytvoreni release je idealni kdyz travis dela tohle:
  * Pusti testy (pokud existujou, overi ze se nesnazis releasnout nefunkcni verzi)
  * Stahne knihovny, vygeneruje assety (grunt/gulp apod)
  * Potom se spusti tvuj bash script kterej vytvori zip/7z/tar.bz2/tar.gz/tar.xz/dar - v podstate jakejkoliv format vhodnej k distribuci(normalni bash, muzes si cp / mv co chces)
  * Vezme ten jeden soubor a uploadne ho na GitHub kde se prida k releasu (nemeni obsah repozitare)

Tedy ten zip je kompletni software(cele SRS). Uzivatel zip stahne, rozbali, nahraje na FTP a spusti instalaci.  (pokud muze rozbalit zip az na serveru je to lepsi, FTP je na mnoho malejch souboru velmi pomale).

Opravneni pridat mozna mam/mel jsem ja, ale @sinacek neco u meho uctu menil, tak se radsi v nastaveni ted hrabat nebudu.

**Comment by sinacek** [comment]
@JindrichPilar Máš podle mně stále stejná práva tedka. Asi bych ti pak casem odebral nektera, ktera bys nemel potrebovat, ale zatim mas vse.

**Comment by JindrichPilar** [comment]
Tak  travis je aktivovan. Tak @jan-stanek muzes zkusit jestli to ted bude fungovat. (release / push). [Tady](https://travis-ci.org/skaut/SRS) bys pak mel videt log s pripadnejma chybama.

**Comment by jan-stanek** [comment]
Díky za povolení a objasnění, ráno zkusím.

**Comment by jan-stanek** [comment]
Instalační příručka upravena. Děkuji za pomoc.

**Comment by JindrichPilar** [comment]
Rado se stalo.

**Comment by jan-stanek** [comment]
Ještě malé zjednodušení, příručka upravena.

**Comment by DeetsCZ** [comment]
Instalace je nyní bez problému a jednoduchá, velmi děkuji všem zúčastněným..
