### ISSUE TITLE
Možnost zobrazit přihlášku od do

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#545]
Prosím do nastavení přihlášky přidat možnost zobrazení registračního formuláře od do.. Ideální by bylo upravit formulář stejně jako je to u programu:
<img width="591" alt="snimek obrazovky 2018-08-19 v 11 30 25" src="https://user-images.githubusercontent.com/19816092/44307472-625c1a00-a3a3-11e8-9ce6-006562fa5659.png">

Pokud je zobrazení zakázáno, potom by se na stránce mělo zobrazovat varování:
1. Přihlašování je nyní zakázáno
2. Přihlašování je povoleno od do

Děkuji

**Comment by jan-stanek** [comment]
To bych řekl, že bude komplikovat nastavení - udělal bych, že když nebude žádná registrovatelná role, tak to ukáže tuhle hlášku místo formuláře.

**Comment by jan-stanek** [comment]
Může to tak být, nebo to speciální nastavení bude v něčem lepší? Přijde mi, že to zesložití nastavení a nepřinese nic moc nového.

**Comment by DeetsCZ** [comment]
Za men by to takto mohlo být řešené, ale ještě to proberu s lidmi od Miquik, kteří toto nastavení chtěli.

**Comment by DeetsCZ** [comment]
Prosím o úpravu, jak jsi psal.
Pokud není registrovatelná role, potom se skryje formulář přihlášky a zobrazí se hláška: "Aktuálně není možné se na seminář přihlásit".
Pokud je nějaká role registrovatelná od do a zrovna jsme mimo tento interval, tak se skryje přihláška a místo ní se zobrazí: "Na seminář je možné se přihlásit od do".

**Comment by DeetsCZ** [comment]
Děkuji
