### ISSUE TITLE
Elektronické vstupenky

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#547]

**Comment by jan-stanek** [comment]
Jsou k tomu nějaké poznámky?

Jinak bych udělal papír, kde budou základní údaje a harmonogram účastníka.

Má smysl tam teď dávat QR kód, když nemáme aplikaci pro čtení? Nevím, co bych do něj dával, pro aplikaci by stačilo id uživatele v SRS, ale to je nám bez ní k ničemu. Leda tam dát nějakej JSON s id a ještě třeba jménem.

**Comment by jan-stanek** [comment]
- jméno, příjmení, e-mail (nebo skautIS username?)
- role, podakce
- harmonogram
- QR kód s id uživatele (lze použít pro ruční ověření, případně v budoucnu pro aplikaci)

**Comment by DeetsCZ** [comment]
Děkuji zatím toto uzavírám, pravděpodobně se k vstupenkám budeme vracet příští rok..
