### ISSUE TITLE
Počet přihlášených uživatelů v roli

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#57]
Tak jako se vytvářel seznam přihlášených uživatelů do frontendu, prosím ještě o přidání možnosti zobrazit počet přihlášených v roli plus kapacitu..
Např. : 
### Kapacita semináře:
**Účastník**
Přihlášeno 10 z 20
**Lektor**
Přihlášeno 5 z 6
**Servis team**
Přihlášeno 10
(pokud u role nebyla zadaná kapacita, potom by se zobrazovalo pouze kolik je uživatelů přihlášeno)

V administraci u role by se měl zaškrtávat checkbox: "Zobrazit kapacitu na webu"

**Comment by jan-stanek** [comment]
```
CREATE TABLE `CapacityBoxContent` (
  `id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

ALTER TABLE `CapacityBoxContent`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `CapacityBoxContent`
  ADD CONSTRAINT `FK_F63DBA2FBF396750` FOREIGN KEY (`id`) REFERENCES `Content` (`id`) ON DELETE CASCADE;
```

**Comment by DeetsCZ** [comment]
Databáze upravena..

**Comment by DeetsCZ** [comment]
Děkuji za úpravu, funguje. 
Jen prosím o drobno úpravu textu: "Žádný role nemají veřejné kapacity" na "Žádné role nemají veřejné kapacity":
![snimek obrazovky 2016-10-06 v 23 10 15](https://cloud.githubusercontent.com/assets/19816092/19170925/911c280a-8c1a-11e6-91c6-d05957af2f77.png)

**Comment by DeetsCZ** [comment]
Děkuji
