### ISSUE TITLE
Úprava mailing

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#58]
V administraci upravit mailing následovně:
1. Přidat doleva menu, jako je například na stránce "Konfigurace"
2. položky: Potvrzovací email, Zaslat nový email, Historie 
# Potvrzovací email:
- Zde je možné měnit text automatických emailů, které chodí uživateli při registraci a při schválení.
- Odesílání automatických emailů při registraci a schválení se musí vytvořit
### Pokud uživatel vyplní registraci, kde jsou všechny role automaticky schválené, nebo byla jeho registrace schválena, potom by mu měl přijít email s potvrzením:

Předmět: Potvrzení registrace do semináře "Název semináře"

Děkujeme za registraci do semináře "Název semináře".
Registrovali jste se jako "Role1", "Role2", ...

Vaše registrace byla schválena.
### Pokud uživatel vyplní registraci, kde některá role vyžaduje schválení, potom by mu měl přijít email s potvrzením:

Předmět: Registrace do semináře "Název semináře"

Děkujeme za registraci do semináře "Název semináře".
Registrovali jste se jako "Role1", "Role2", ...

Vyčkejte na potvrzení vaší registrace. 
# Zaslat nový email
- Obsahuje stávající formulář.
# Historie
- Zde by měly být vypsány emaily, které byly odeslány.
- Obsahuje Čas, Předmět, Komu byl odeslán (Buď jeden uživatel, nebo role, které byl email odeslán).

**Comment by jan-stanek** [comment]
Jak si představuješ ty automatické maily a jejich úpravu?

Mail by měl obsahovat ten text s názvem a rolemi + nějaký nastavitelný text, nebo by to měl být úplně libovolný text, do kterého by se vkládal název semináře s rolemi pomocí nějakého speciálního tagu?

**Comment by jan-stanek** [comment]
Zatím jen historie. Maily se ukládají i na serveru, ve formátu eml.

Na automatické maily by šlo vytvořit pevnou šablonu, do které by se doplňovaly texty z polí. Jen je třeba vymyslet, co všechno by tam mělo být nastavitelné.

**Comment by jan-stanek** [comment]
Co dát potom to nastavení automatických e-mailů pod "Nastavení", aby to bylo jednotné?

**Comment by DeetsCZ** [comment]
Přemýšlím, jaké nastavení by tam mělo být. 
Pokud jde o úpravu textu automatických emailů, to bych nechala v sekci mailing. Ale do nastavení bych přidala položku mailing, kde by mohlo být nastavení:
E-mail pro mailing (nyní v sekci Seminář) 
 - bylo by možné zde přidat formulář pro ověření emailu? Odeslání kontrolního emailu s potvrzením..

Dále by tam byly checkboxy:
Odesílat potvrzení po přihlášení
Odesílat potvrzení po registraci
Odesílat informaci o změně role
Odesílat potvrzení o zaplacení
Odesílat potvrzení o odhlášení ze semináře

**Comment by jan-stanek** [comment]
Ok, myslel jsem úpravu textu, ale asi to patří víc do mailingu.

Přesunutí není problém. Ověření snad také ne.

**Comment by DeetsCZ** [comment]
Přehled nový emailing: 

1. Automaticky odesílané emaily: každý email by měl být položkou v levém menu
- u každého typu emailu by úplně nahoře měl být checkbox "Neodesílat tento typ emailu"
    - po zaškrtnutí se daný email nebude odesílat, tedy v defaultu se odesílají všechny automatické emaily
- **po přihlášení uživatele**
   - text: 
   - možné pole:
- **po registraci uživatele**
   - text: 
   - možné pole:
- **po změně role**
   - text: 
   - možné pole:
- **po změně podakce**
   - text: 
   - možné pole:
- **po zaplacení**
   - text: 
   - možné pole:
- **při odhlášení z role**
   - text: 
   - možné pole:
- **při zrušení podakce**
   - text: 
   - možné pole:
- **upozornění na splatnost**
   - text: 
   - možné pole:
2. Ručně odesílané emaily
- vychází ze stávajícího formuláře
- bylo by zajímavé, kdyby šlo vyhledávat příjemce i mezi jednotlivci, například tak, že po rozkliknutí výběru budou stále viditelné role a pod tím vyhledávací pole, které vyhledává podle příjmení a jména mezi jednotlivými účastníky

**Comment by jan-stanek** [comment]
Hotova úprava ručně odesílaných e-mailů, aby mohly být posílány i jednotlivcům.

**Comment by jan-stanek** [comment]
Hotovo vše, kromě ověření e-mailu semináře a automatických mailů souvisejích s podakcemi (nastaveny jako neaktivní)

**Comment by jan-stanek** [comment]
Hotovo až na maily související s podakcemi.

**Comment by DeetsCZ** [comment]
Nelze změnit email akce..
![snimek obrazovky 2017-09-14 v 15 54 22](https://user-images.githubusercontent.com/19816092/30480172-c833043c-9a18-11e7-8c08-50964cd29b75.png)
Bylo předvyplněno "srs@skauting.cz"
Vyplnila jsem deets@skaut.cz : po uložení se ale email vrátil na srs@skauting.cz, jak je vidět na obrázku.
Potvrzovací email by měl odejít na nově vyplněný email, ale byl odeslán na email uživatele, který email zadal, tedy bylo odesláno na deets@seznam.cz
Změna po potvrzení proběhla v pořádku. 
1. to, že zůstane vyplněný starý email je vlastně v pořádku, ale bylo by možné po uložení například vypsat pod textové pole "Změna emailu čeká na potvrzení"
2. prosím o odesílání kontrolního emailu na nově vyplněný email
3. byla by možná úprava, aby se pro potvrzení emailu kliknutím na odkaz nemuselo přihlašovat? Mohl by ten odkaz fungovat i bez přihlášení na web?

Děkuji

**Comment by jan-stanek** [comment]
Kdy se má posílat upozornění na splatnost? Mám někam přidat nastavení na počet dnů?

**Comment by DeetsCZ** [comment]
Určitě by bylo lepší, kdyby někde bylo nastavení, kdy (kolik dní před koncem splatnosti) se má upozornění odesílat.

**Comment by jan-stanek** [comment]
Všechny 3 připomínky ke změně e-mailu jsou zapracovány. 

Pokud má přihlášený uživatel přístup do tohoto nastavení, je po potvrzení přesměrován tam, jinak se na hlavní stránce vypíše hláška o (ne)úspěšné změně.

**Comment by DeetsCZ** [comment]
Bylo by možné do emailu s potvrzením registrace přidat proměnné?
částku k zaplacení
datum splatnosti
číslo účtu
variabilní symbol

**Comment by DeetsCZ** [comment]
Pokud se uživatel přihlásí na seminář a poté se přes profil odhlásí potom mu přijde automatický email "Potvrzení zrušení registrace", stejný email by měl chodit i při odhlášení uživatele z administrace tlačítko "Odhlásit ze semináře" v detailu uživatele.

**Comment by DeetsCZ** [comment]
Děkuji
