### ISSUE TITLE
Skrýt sloupec "Zaplaceno"

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#6]
V seznamu účastníků skrýt sloupec "Zaplaceno" a sloupec "Datum zaplacení" přejmenovat na "Zaplaceno dne". 
![snimek obrazovky 2016-08-03 v 15 07 12](https://cloud.githubusercontent.com/assets/19816092/17366857/ad8d57b2-598d-11e6-85db-4ab1c030f452.png)

(Sloupec Zaplaceno je nyní nadbytečný, protože ve chvíli, kdy se zadá datum zaplacení, potom je účast zaplacena)

**Comment by jan-stanek** [comment]
Sloupec "Zaplaceno" odstranit, nebo jen skrýt ve výchozím stavu - aby mohl být přidát pomocí "Zobrazit/Skrýt sloupce"?

Checkbox "zaplatil" v detailu účastníka může být zaškrtnut, i pokud není vyplněn datum platby, a naopak může být vyplněn datum platby a "zaplatil" nezaškrtnutý. Pokud by se sloupec "Zaplaceno" odstranil, bylo by vhodné odstranit i checkbox, jinak kontrolovat konzistenci.

**Comment by DeetsCZ** [comment]
Sloupec prosím úplně odstranit a v detailu účastníka odstranit i checkbox. Pokud je tam nějaká funkční návaznost na sloupec "Zaplaceno", nebo checkbox v detailu, potom by vyplnění data platby mělo mít stejnou účinnost.

**Comment by DeetsCZ** [comment]
Děkuji za úpravu, otestováno, uzavírám...
