### ISSUE TITLE
Chyba: Aktualizovat údaje do skautIS

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#60]
Pokud ve frontendu v profilu uživatele vyberu "Aktualizovat data a sesynchronizovat se skautIS", potom vyskočí dvě hlášení: 
1. Synchronizace se nezdařila
2. Data aktualizovaná
![snimek obrazovky 2016-09-25 v 13 47 38](https://cloud.githubusercontent.com/assets/19816092/18815115/019d7586-8327-11e6-9c5b-99f64fe4aad2.png)

Což nedává smysl a data se do skautIS nesesynchronizují.

**Comment by jan-stanek** [comment]
@jerrysohn Při volání funkce PersonUpdateBasic dostávám chybu `Chyba validace (Person_EnterCity, Person_EnterPostcode, Person_EnterStreet)` po doplnění City, Postcode a Street dostávám zase: `Chyba validace (Person_OnlySimplePersonAddressChange)`, nevíš prosím, co dělám špatně?

**Comment by jan-stanek** [comment]
Nevím jestli tu hlášku chápu správně, ale vypadá to, že je ta funkce zablokovaná a u uživatele půjde změnit jen adresa.

**Comment by jan-stanek** [comment]
Má ta synchronizace vůbec smysl? Pracuje se jen se základními údaji, které stejně asi mají všichni ve skautISu správně.

**Comment by DeetsCZ** [comment]
Jen ještě doplním, že by bylo dobré, kdyby se u propojených účtů daly měnit pouze údaje o adrese.

**Comment by jan-stanek** [comment]
S tím problém není, ale změna jména, příjmení apod. nejde ani u nepropojených - vypadá to, že to bylo ve skautISu zablokováno, nebo jestli se na to přidělují nějaká oprávnění, tak ho SRS nemá.

**Comment by jerrysohn** [comment]
@jan-stanek s jakými AppID pracuješ? abych ověřil to oprávnění (pro vývoj bys měl mít povoleny všechny funkce, ale je možné, že pro dané AppID to tak není). Jinak funkce PersonUpdateBasic má určitá omezení, co s ní jde a nejde měnit. Je to zjednodušená verze klasického PersonUpdate, kde jsou validovány všechny zadávané povinné údaje (včetně RČ) a pokud nejsou zadány, tak nejdou změnit. PersonUpdateBasic je zjednodušená v tom, že s její pomocí lze změnit i jen část údajů (bez nutnosti RČ apod.), ale údaje musí být vyplněny a validní, aby to prošlo.

**Comment by jan-stanek** [comment]
@jerrysohn AppID jsem poslal na mail, ale nefunguje mi to ani na srs.skauting.cz a test-ws.skautis.cz.

Pokud vyplním povinné údaje podle http://is.skaut.cz/napoveda/(S(wntvdm45epk3edz2jtq4z455))/programatori.WS-OrganizationUnit-Funkce-PersonUpdateBasic.ashx, dostanu `Chyba validace (Person_EnterCity, Person_EnterPostcode, Person_EnterStreet)`.

Pokud přidám vyjmenované údaje, dostanu `Chyba validace (Person_OnlySimplePersonAddressChange)`.

**Comment by jerrysohn** [comment]
Tak se ukázalo, že jsme v minulosti v té funkci webové služby dělali nějaké potřebné úpravy a zapomněli jsme tam zohlednit tu Basic variantu. Takže jsme teď upravili testovací skautIS a už by v Basic variantě neměly být povinné údaje Street, City, Postcode a mělo by ti to jít zavolat správně i bez těchto údajů.
Prosím vyzkoušej to a dej nám vědět, že je to už OK, abychom to pak aktualizovali i v ostrém skautISu.

**Comment by jan-stanek** [comment]
Teď už to funguje, děkuji.

Jen je tam asi malý rozdíl, původně se té funkci předávaly všechny údaje o osobě, teď je nutné poslat jen ty, které požaduje, jinak vrátí `Chyba validace (Person_OnlySimplePersonAddressChange)`.

**Comment by jerrysohn** [comment]
Ano, je v tom ten drobný rozdíl, ale předpokládám, že to nevadí a na funkčnost to nemá vliv a je to tedy v pohodě :) Děkuji za otestování a že jsi to dořešil. Nasadíme to upravené i do ostrého skautISu.

**Comment by jan-stanek** [comment]
Žádný problém s tím není.

**Comment by DeetsCZ** [comment]
Testovala jsem a aktualizace probíhá bez problému..
