### ISSUE TITLE
Optimalizace hromadné změny programů

### ISSUE THREAD

**Issue by jan-stanek** [skaut/SRS#605]
Zrychlit změnu programů při
- vytvoření/odstranění automaticky přihlašovaného programu
- změna bloku na automaticky přihlašovaný (a zpět)
- editace/odstranění role
- hromadná změna rolí
- editace kategorie
- ...

(kdykoliv, kdy je velkému množství účastníků potřeba odhlásit/přihlásit nějaké programy)

**Comment by petrparolek** [comment]
@jan-stanek v čem ukládání pomalé? :o

**Comment by jan-stanek** [comment]
vyřadil jsem přepočítávání sloupce s nepřihlášenými povinnými bloky, teď by to mohlo být o dost rychlejší

**Comment by jan-stanek** [comment]
Kompletně přepsáno, přihlašování/odhlašování probíhá jen při relevantních změnách (změna názvu kategorie apod. není problém). 

Transakce nejsou problém - doctrine nevytváří vnořené transakce.

Jinak výrazné zlepšení nečekám, to by bylo nutné implementovat celou logiku znovu speciálně pro hromadné změny.
