### ISSUE TITLE
Automatický email při odhlášení za nezaplacení

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#606]
Prosím o přidání dalšího automatického emailu "Při odhlášení kvůli nezaplacení"

**Comment by jan-stanek** [comment]
Nestačí do tohohle: "Potvrzení zrušení registrace" napsat něco jako "byli jste odhlášeni, pravděpodobně z důvodu nezaplacení"?

**Comment by DeetsCZ** [comment]
Bude lepší mít toto oddělené protože tento email může obsahovat jiný text třeba s návodem, jak postupovat, pokud již poslali platbu a podobně..

**Comment by jan-stanek** [comment]
@DeetsCZ můžeme zavřít?
