### ISSUE TITLE
Chyba: rozesílání emailu pro urcitou roli

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#608]
Ve formuláři pro odeslání emailu chybí některé role:
<img width="881" alt="snimek obrazovky 2018-11-09 v 13 30 51" src="https://user-images.githubusercontent.com/19816092/48262745-f75f3400-e423-11e8-8a94-025ead3f6212.png">

Například Nepřihlášený.

Ale přesto email rozeslaný jen vypsaným rolím se poslal i na uživatele ostatních rolí:
<img width="886" alt="snimek obrazovky 2018-11-09 v 13 34 55" src="https://user-images.githubusercontent.com/19816092/48262871-57ee7100-e424-11e8-89b0-0e5864e4f679.png">

Například poslední uživatel je v roli nepřihlášený a přesto se email rozeslal i jemu..

**Comment by jan-stanek** [comment]
Nepřihlášený tam chybí záměrně, má smysl jim něco posílat?

Ten e-mail byl odeslaný vybraným rolím + všem vybraným uživatelům.

**Comment by DeetsCZ** [comment]
moznost poslat neprihlasenym bych tam dala, pokud se treba bude potreba upozornit, ze se uvolnila kapacita a apod..

**Comment by jan-stanek** [comment]
přidána role "nepřihlášený"

**Comment by DeetsCZ** [comment]
Děkuji
