### ISSUE TITLE
Chyba: nelze uložit kategorii

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#609]
V menu Program, není možné uložit kategorii. Při editaci nereagují tlačítka "Uložit" a "Zrušit":
<img width="889" alt="snimek obrazovky 2018-11-09 v 18 33 29" src="https://user-images.githubusercontent.com/19816092/48278724-a57fd380-e44e-11e8-9111-988f5eb1149a.png">

**Comment by jan-stanek** [comment]
Problém s rychlostí, bude vyřešeno v #605

**Comment by DeetsCZ** [comment]
Testovala jsem:
1. Vytvoření funguje
3. Uložení nové kategorie funguje
2. Při editaci funguje rozbalení rolí, ale opět nereagují tlačítka uložit a zrušit. Uložení samo o sobě funguje, pokud místo na uložit kliknu na tlačítko pro přidání další kategorie ("+"), tak se upravená kategorie uloží..

**Comment by jan-stanek** [comment]
pořád nefunguje?

**Comment by DeetsCZ** [comment]
Tlačítka stále tak úplně nefungují, jak by měly.
Zadání nové kategorie je v pořádku.
Když edituji oprávněné role u již vytvořené kategorie, tak tlačítka Uložit a Storno nereagují, ale když po kliknutí obnovím stránku, tak se změněné role uloží..

**Comment by jan-stanek** [comment]
duplicate of #605
