### ISSUE TITLE
Defaultní souhlas se zpracováním údajů

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#615]
Prosím o úpravu defaultního souhlasu na:

"Má účast na této akci je součástí činnosti Junáka - českého skauta a jeho jednotek, a tak beru na vědomí, že zpracování mých osobních údajů pro potřeby této akce se řídí pravidly, poučením a souhlasy danými v rámci přihlášky člena do organizace Junák - český skaut (případně pokud nejsem členem, tak přihláškou nečlena na akci). Podrobné znění je vždy dostupné na www.skaut.cz/osobniudaje. Zpracování osobních údajů a nakládání s nimi na této akci probíhá v souladu s Nařízením Evropského parlamentu a Rady 2016/679 (tzv. GDPR) a zákonem 101/2000 Sb., o ochraně osobních údajů, ve znění pozdějších předpisů. Společným správcem osobních údajů je Junák - český skaut, z. s. (hlavní spolek) a případné další pořádající organizační jednotky (pobočný spolek uvedený v kontaktech na webu této akce)."

**Comment by jan-stanek** [comment]
projeví se jen při nové instalaci, jinak by se přepisoval i těm, kteří si ho sami upravili

**Comment by DeetsCZ** [comment]
Děkuji
