### ISSUE TITLE
Kategorie programových bloků a zobrazení na webu

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#62]
1. programovým blokům přidat kategorie
2. správa kategorii (přidání, odebrání, editace) bude na stránce program semináře v administraci (do podmenu přidat položku kategorie)
3. při tvorbě programového bloku umožnit blok zařadit do kategorie
4. na stránku program semináře->programové bloky přidat možnost řadit podle kategorie
5. ve frontendu vytvořit stránku "Program semináře", kde bude přehled programů
- vlevo bude sloupec, kde budou vypsané kategorie, které bude možné rozkliknout a tak zobrazit seznam programových bloků v dané kategorii
- po kliknutí na programový blok se v hlavní části se zobrazí údaje o programovém bloku, které byly zadané při vytváření bloku

**Comment by DeetsCZ** [comment]
Doplním kvůli issue: Úpravy pro Miquik #70
 - stránku s přehledem vidí všichni bez ohledu na roli a mohou také procházet detaily všech programových bloků

**Comment by jan-stanek** [comment]
```
INSERT INTO `Resource` (`id`, `name`) VALUES (NULL, 'Kategorie');
```

**Comment by DeetsCZ** [comment]
databáze upravena..

**Comment by jan-stanek** [comment]
zobrazení bloků je zatím trochu zjednodušené, případně vylepším později

**Comment by DeetsCZ** [comment]
1. omezila jsem programový blok pro roli Účastník (blok skautIS a novinky) a přihlásila jsem se pod rolí účastník, ale tento blok v výběru programů nevidím a nemohu si blok tedy zapsat.

2. Prosím úpravu zobrazení programových bloků ve frontendu, tak aby se dala kategorie (například přes křížek) zabalit/rozbalit.

**Comment by jan-stanek** [comment]
1. na srs.skauting.cz jsem také jako účastník a vidím tohle: 
![srs](https://cloud.githubusercontent.com/assets/11959693/19249194/71273f18-8f34-11e6-9902-cc21f15c7ad2.png)

2. zkusím to nějak vymyslet

**Comment by DeetsCZ** [comment]
Zjistila jsem, že ten problém je, pokud jsem přihlášená jako administrátor a v administraci vyberu, že se chci přihlásit jako účastník, potom programový blok nevidím. Pokud se přihlásím pod účtem účastníka, potom je vše v pořádku.
Což nám vlastně v ostrém provozu vadit nebude..

**Comment by jan-stanek** [comment]
Tuhle možnost jsem asi nikdy nepoužil, tak snad toho nebude víc. Pokusím se opravit.

**Comment by jan-stanek** [comment]
Mělo by fungovat i tlačítko pro změnu role.

**Comment by DeetsCZ** [comment]
Prosím drobnou úpravu textu "Kategorie -> nezařazené":
![snimek obrazovky 2016-10-11 v 13 07 11](https://cloud.githubusercontent.com/assets/19816092/19268671/0125ce1e-8fb6-11e6-83f3-d0acd723a586.png)

**Comment by DeetsCZ** [comment]
Děkuji za zpracování
