### ISSUE TITLE
Chyba: automatické přihlašování na programy

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#625]
Pokud zadám automaticky přihlašovaný povinný program a chci ho přidat do harmonogramu, potom se zobrazí "načítací kolečko", ale blok se nepřidá:
<img width="800" alt="snimek obrazovky 2019-01-26 v 14 08 49" src="https://user-images.githubusercontent.com/19816092/51787585-2a3bdd00-2174-11e9-8efe-c15a20f9ada5.png">

**Comment by jan-stanek** [comment]
zkusil jsem drobnou úpravu, můžete prosím vyzkoušet třeba na srs.skauting.cz?

**Comment by jan-stanek** [comment]
Tak to se obávám, že s tím rychle nic neudělám, ještě se zkusím podívat, jestli by se nadlo zrušit přepočítávání některých údajů, které se pak zobrazují v tabulce uživatelů.

**Comment by jan-stanek** [comment]
vyřadil jsem pořpočítávání sloupce s nepřihlášenými povinnými bloky, teď by to mohlo být o dost rychlejší

**Comment by DeetsCZ** [comment]
Na srs.skauting.cz je automatické přihlašování i přidání bloku do harmonogramu v pořádku (pouze 6 přihlášených).
Na elixir.skauting.cz stále do harmonogramu zařadit nelze (velké množství uživatelů)..

**Comment by jan-stanek** [comment]
duplicate of #605
