### ISSUE TITLE
Zrychlení tabulky plateb

### ISSUE THREAD

**Issue by jan-stanek** [skaut/SRS#639]

**Comment by jan-stanek** [comment]
Editace přesunuta na samostatnou stránku.

**Comment by DeetsCZ** [comment]
Určitě k zrychlení došlo, ale stále je tabulka dost pomala :(.
Půjde to ještě řešit?

**Comment by jan-stanek** [comment]
Dá se někde vyzkoušet? Teď už by ji nemělo nic brzdit a měla by být podobně rychlá jako tabulka uživatelů.

**Comment by DeetsCZ** [comment]
Již běží rychle, děkuji
