### ISSUE TITLE
Chyba: Přidávání plateb ručně

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#642]
Když zadávám ručně platbu a vyberu datum (z malého kalendáře), tak mi stále svítí chyba, že mám zadat datum. Platba přesto potvrdit lze:
<img width="340" alt="snimek obrazovky 2019-02-19 v 16 05 09" src="https://user-images.githubusercontent.com/19816092/53025174-bafa9580-3460-11e9-8034-1f93789b728d.png">

A potom jedna "drobnost", když zadávám platbu, tak zadání přeskočí na konec stránky:
<img width="1136" alt="snimek obrazovky 2019-02-19 v 16 05 45" src="https://user-images.githubusercontent.com/19816092/53025611-7c190f80-3461-11e9-85b2-1442cf0ced41.png">

Platba se ale přidá na začátek tabulky. Nebylo by možné, aby se i formulář pro zadání platby zobrazoval na začátku tabulky?

**Comment by jan-stanek** [comment]
Všechny tabulky upraveny tak, aby se nové položky zadávaly nahoře.

**Comment by DeetsCZ** [comment]
Děkuji, zadávání vypadá velmi dobře
