### ISSUE TITLE
Kritická chyba: zmizely tlačítka v dialogových oknech

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#647]
V dialogovém okně pro potvrzení smazání místnosti a programového bloku chybí tlačítka, tedy místnost ani programový blok nejde odstranit:
<img width="378" alt="snimek obrazovky 2019-02-27 v 13 33 53" src="https://user-images.githubusercontent.com/19816092/53490694-a8054800-3a94-11e9-9e90-45e4207665dd.png">
<img width="451" alt="snimek obrazovky 2019-02-27 v 13 34 22" src="https://user-images.githubusercontent.com/19816092/53490698-aa67a200-3a94-11e9-8c5b-3240b15e44fe.png">

**Comment by jan-stanek** [comment]
uz byla vydana nova verze bootstrap-confirmation, ktera tenhle problem resi

**Comment by DeetsCZ** [comment]
Moc děkuji za opravu
