### ISSUE TITLE
Přesměrování po přihlášení

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#65]
1. V administraci v konfiguraci v nastavení Systém přidat možnost vybrat, na jakou stránku bude uživatel přesměrován po přihlášení.
2. U každé role zobrazit volbu, kam má být uživatel v této roli přesměrován, pokud zde nebude nic vybráno, potom se používá defaultně nastavená stránka v konfiguraci.

**Comment by jan-stanek** [comment]
přidáno do nastavení webu, může být přesunuto

**Comment by jan-stanek** [comment]
nastavení se použije pouze na úvodní stránce (slug /), jinak se po přihlášení vrátí tam kde uživatel byl

**Comment by DeetsCZ** [comment]
Vyzkoušeno. Děkuji
