### ISSUE TITLE
Chyba: filtrování v seznamu přihlášených na program

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#657]
Ve filtrování v seznamu přihlášených na program jsem narazila na dvě chyby:
1. filtrování nezpřihlášených "Ne" nefunguje:
<img width="938" alt="Snímek obrazovky 2019-03-11 v 12 36 37" src="https://user-images.githubusercontent.com/19816092/54121430-b0497580-43fa-11e9-82fa-2081f34b9822.png">
2. při filtrování přihlášených "Ano" funguje jen první strana seznamu, při překliknutí na další se zobrazí všichni:
<img width="946" alt="Snímek obrazovky 2019-03-11 v 12 36 49" src="https://user-images.githubusercontent.com/19816092/54121477-d1aa6180-43fa-11e9-900f-153d455e499f.png">

**Comment by DeetsCZ** [comment]
Tak ještě jedna chyba:
Nefunguje zobrazení všech záznamů, při volbě "všechny" se zobrazí pouze 10 záznamů.
<img width="878" alt="Snímek obrazovky 2019-03-11 v 12 43 48" src="https://user-images.githubusercontent.com/19816092/54121655-55fce480-43fb-11e9-81c8-fe323e40503c.png">

Zde podle mne úplně nadává smysl mít zobrazeno najednou třeba 700 záznamů. Navrhuji místo všechny zadat nějaké vysoké číslo například 200 nebo víc podle toho co systém bez problému zvládne.

**Comment by jan-stanek** [comment]
zobrazení všech je chyba knihovny, kterou nejspíš brzy opraví (https://github.com/contributte/datagrid/issues/754)

filtrování opraveno #659

**Comment by petrparolek** [comment]
@jan-stanek nevím, můj PR tam leží hromadu měsíců a chybí testy, pomohl bys je napsat prosím? Nevím si rady a potom bude si myslím PR přijat. U sebe to řeším stažením vlastního forku a větve:

```
...
	"repositories": [
		{
			"type": "vcs",
			"url": "https://github.com/petrparolek/testbench"
		},
		{
			"type": "vcs",
			"url": "https://github.com/petrparolek/ublaboo-datagrid"
		}
	],
        "require": {
                ....
       		"ublaboo/datagrid": "dev-v5.x-custom",
                ...
```

**Comment by DeetsCZ** [comment]
Funguje..
