### ISSUE TITLE
Přihlášení a odhlášení z programu

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#66]
Umožnit přihlášení a odhlášení uživatele z programu.
Řešením by mohl být využití seznamu přihlášených a nepřihlášených uživatelů v detailu programového bloku:
![snimek obrazovky 2016-09-26 v 13 48 18](https://cloud.githubusercontent.com/assets/19816092/18833211/eeb8a8fe-83ef-11e6-9846-6a1d07241bed.png)
1. Na seznamu přihlášených uživatelů přidat ke každému uživateli checkbox a k tlačítku "Zavřít" tlačítko "Odhlásit z programu". Pokud zaškrtneme uživatele a stiskneme "Odhlásit z programu", potom se tento program uživateli odebere.
   - Odebranému uživateli by se měl dále odeslat email s informací: "Byl jste odhlášen z programu "Název programu", zkontrolujte si váš rozvrh."
2. Na seznamu nepřihlášených uživatelů přidat ke každému uživateli checkbox a k tlačítku "Zavřít" tlačítko "Přihlásit na program". Pokud zaškrtneme uživatele a stiskneme "Přihlásit na program", potom se tento program uživateli přidá.
   - Přihlášenému uživateli by se měl dále odeslat email s informací: "Byl jste přhlášen na program "Název programu", zkontrolujte si váš rozvrh."

**Comment by jan-stanek** [comment]
Jaká oprávnění by měla být k přihlašování a odhlašování potřeba? "Spravovat své programy" (změny by mohli dělat lektoři u svých programů), nebo jen "spravovat všechny programy" (změny by mohl dělat jen administrátor, organizátor apod.)?

**Comment by DeetsCZ** [comment]
Asi bych to sloučila pod "Spravovat své programy", tak aby si účastníky mohli upravovat i sami lektoři.

**Comment by jan-stanek** [comment]
Ok

**Comment by jan-stanek** [comment]
Úprava nahrána na testweb.

Zatím je to bez odesilání e-mailů, budou doplněny po #58

**Comment by DeetsCZ** [comment]
Děkuji úprava funguje, bude uzavřeno po dokončení #58

**Comment by DeetsCZ** [comment]
Emaily také fungují.. Děkuji za zpracování
