### ISSUE TITLE
Chyba: je možné se přihlásit i přes naplněnou kapacitu role

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#660]
Otestováno na webu poradní skály:
Je možné se přihlásit do role, ikdyž je již naplněná kapacita.

**Comment by jan-stanek** [comment]
Zkusil jsem registraci povolit a chová se to, tak jak má

![Screenshot_2019-05-08 Přihlášení Poradní skála 2019](https://user-images.githubusercontent.com/11959693/57408626-6e646200-71e6-11e9-9f84-a5e1db70993b.png)

**Comment by jan-stanek** [comment]
Vzpomínám si, že se to nepodařilo nasimulovat, byl s tím ještě problém?

**Comment by DeetsCZ** [comment]
Pravda, nejdříve mi to šlo, ale po druhé už se mi to nepovedlo nasimulovat.
Uzavírám..
