### ISSUE TITLE
CHYBA: nelze změnit velitel závodu

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#661]
U krajského kola Libereckého kraje nejde změnit velitel:
Velitele změním na "Opočenský Karel":
<img width="806" alt="Snímek obrazovky 2019-04-29 v 15 33 46" src="https://user-images.githubusercontent.com/19816092/56958101-88000c80-6b49-11e9-983f-947b44458586.png">

Ale formulář se neuloží, vrátí pole velitele na původní hodnotu a zobrazí chybu:
<img width="820" alt="Snímek obrazovky 2019-04-29 v 15 34 12" src="https://user-images.githubusercontent.com/19816092/56958129-aebe4300-6b49-11e9-92c5-f2f22c7ea249.png">

**Comment by jan-stanek** [comment]
To bude spíš k závodům :-)

Dne út 30. 4. 2019 13:13 uživatel DeetsCZ <notifications@github.com> napsal:

**Comment by DeetsCZ** [comment]
Je to tak, jsem se to zadala vedle :D
