### ISSUE TITLE
Tisk harmonogramu

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#67]
1. V profilu uživatele ve frontendu přidat tlačítko "Stáhnout harmonogram". Harmonogram by se po stisku tlačítka měl exportovat do excelu.
   ![snimek obrazovky 2016-09-26 v 14 02 50](https://cloud.githubusercontent.com/assets/19816092/18833635/f5b44210-83f1-11e6-8df0-08357ab44645.png)
2. Do hromadných akcí na seznamu uživatelů přidat možnost "Stáhnout harmonogram". Tato možnost vyexportuje do excelu harmonogram všech zaškrtaných uživatelů.
   ![snimek obrazovky 2016-09-26 v 14 03 38](https://cloud.githubusercontent.com/assets/19816092/18833659/1364e0f8-83f2-11e6-8f7b-9f7f49f91ec4.png)

**Comment by jan-stanek** [comment]
Jak by měl vypadat harmonogram pro více uživatelů - uživatelé jako jednotlivé listy?

**Comment by DeetsCZ** [comment]
Ano, prosím jednotlivé uživatele zobrazovat na jednotlivých listech. Děkuji

**Comment by DeetsCZ** [comment]
Zobrazuje se stejná chyba jako u exportu uživatelů a rolí..

**Comment by DeetsCZ** [comment]
Stejná chyba je ve frontend i administraci:
![snimek obrazovky 2016-10-31 v 20 50 47](https://cloud.githubusercontent.com/assets/19816092/19869269/f1498e9e-9fab-11e6-9cc5-95f6d27cf329.png)

**Comment by jan-stanek** [comment]
Viz 144

**Comment by DeetsCZ** [comment]
Děkuji za zpracování
