### ISSUE TITLE
Přidání LICENSE souboru

### ISSUE THREAD

**Issue by jan-stanek** [skaut/SRS#679]
Pro použití premium features z fullcalendar je třeba mít projekt pod GPLv3 licencí (https://fullcalendar.io/license/premium).

Je třeba zjistit, jestli s ní nemáme nějakej problém.

**Comment by petrparolek** [comment]
pokud dobře chápu text: "Option 3)  GPL License

Under the GPL license, you may use Scheduler without charge. You may even modify its source code and redistribute it under the same license. However, there is one big caveat. Any project that leverages Scheduler must be open source. So, if you have a commercial project, and you don’t want its source code to be released publicly, it is best to choose another license. This GPL license is directed towards GPL-compatible open source projects that want to bundle Scheduler.", tak SRS jako OSS nekomerční projekt nemá problém s fullcalendar.

**Comment by jan-stanek** [comment]
@DeetsCZ můžeme zavřít?
