### ISSUE TITLE
Nastavení uživatele

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#69]
U každého uživatele evidovat:
1. množství zobrazených položek na stránku: "Záznamů na stranu:"
   - v administraci na strákách program semináře a evidence uživatelů
     ![snimek obrazovky 2016-09-26 v 14 12 43](https://cloud.githubusercontent.com/assets/19816092/18834037/ffb2283e-83f3-11e6-8580-5fa8626f33ca.png)
2. které sloupce má uživatel zobrazené na stránce evidence uživatelů v administraci
   ![snimek obrazovky 2016-09-26 v 14 19 36](https://cloud.githubusercontent.com/assets/19816092/18834081/5660adae-83f4-11e6-888e-b9e243e5a6d1.png)

**Comment by jan-stanek** [comment]
Ukládání řeší nový datagrid sám, akorát se to neukládá do db, ale cookies prohlížeče. Stačí to?

**Comment by jan-stanek** [comment]
Navíc se ukládá i řazení a filtrování.

**Comment by DeetsCZ** [comment]
Je toto hotové? Issue je ve stavu rozpracovaný, ale podle chování tabulek se zdá, že je toto již hotové.

**Comment by jan-stanek** [comment]
Jak se to vezme, neukládá se to do databáze k uživateli, ale jen v prohlížeči.

**Comment by jan-stanek** [comment]
Nechal bych to asi podle ohlasů, jestli to bude potřeba.

**Comment by DeetsCZ** [comment]
Zatím to vypadá bezproblémově.. Děkuji za úpravu
