### ISSUE TITLE
Notice Undefined property: stdClass::$UserDetailOutput při prvním přihlášení během instalace

### ISSUE THREAD

**Issue by petrparolek** [skaut/SRS#699]
@jan-stanek  používáš jakousi alfa verzi  skautis/nette a ne stabilní verzi 2.2.0 a stabilní verzi skautis/skautis 2.1.0? S těmito verzemi vše maká, jak má.

**Comment by jan-stanek** [comment]
Vím o tom, problém není u nás, starší verze nejsou zase kompatibilní s Nette 3.0, oprava už je připravená a čeká na merge: https://github.com/skaut/Skautis/pull/91

**Comment by petrparolek** [comment]
je kompabilní, viz můj commit 278b21204a3e8c38a52312a37eee46b20539d2e2
