### ISSUE TITLE
Úpravy pro Miquik

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#70]
Po skype poradě prosím o zpracování úprav:

1. Na registračním formuláři při výběru role zobrazovat volnou kapacitu role

2. Pokud si uživatel vybere "placené" role, potom jeho cena je součet cen za všechny vybrané role

3. Umožnit při vytváření role vybrat roli, kterou není možné současně vybrat při regitraci
 - v regitračním forumuláři přidat varování, pokud uživatel vybere paralelní role

4. Při vytváření programového bloku umožnit vybrat, která role si může daný blok zapsat a vidět ho v kalendáři

**Comment by jan-stanek** [comment]
```
ALTER TABLE `Role` DROP `fee`;
```

**Comment by DeetsCZ** [comment]
databáze upravena..

**Comment by jan-stanek** [comment]
Další úpravy:
```
ALTER TABLE `Block` ADD `category_id` INT(11) NULL DEFAULT NULL AFTER `room_id`;

CREATE TABLE `Category` (
  `id` int(11) NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `category_role` (
  `category_id` int(11) NOT NULL,
  `role_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

ALTER TABLE `Role` ADD `displayCapacity` TINYINT(1) NULL DEFAULT NULL AFTER `displayInList`;

CREATE TABLE `role_role` (
  `role_id` int(11) NOT NULL,
  `incompatible_role_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

ALTER TABLE `Block`
  ADD KEY `IDX_42DAB82612469DE2` (`category_id`);

ALTER TABLE `Category`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `UNIQ_FF3A7B975E237E06` (`name`);

ALTER TABLE `category_role`
  ADD PRIMARY KEY (`category_id`,`role_id`),
  ADD KEY `IDX_DCF2F02D12469DE2` (`category_id`),
  ADD KEY `IDX_DCF2F02DD60322AC` (`role_id`);

ALTER TABLE `role_role`
  ADD PRIMARY KEY (`role_id`,`incompatible_role_id`),
  ADD KEY `IDX_E9D6F8FED60322AC` (`role_id`),
  ADD KEY `IDX_E9D6F8FE657B53D5` (`incompatible_role_id`);

ALTER TABLE `Category`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `Block`
  ADD CONSTRAINT `FK_42DAB82612469DE2` FOREIGN KEY (`category_id`) REFERENCES `Category` (`id`);

ALTER TABLE `category_role`
  ADD CONSTRAINT `FK_DCF2F02D12469DE2` FOREIGN KEY (`category_id`) REFERENCES `Category` (`id`) ON DELETE CASCADE,
  ADD CONSTRAINT `FK_DCF2F02DD60322AC` FOREIGN KEY (`role_id`) REFERENCES `Role` (`id`) ON DELETE CASCADE;

ALTER TABLE `role_role`
  ADD CONSTRAINT `FK_E9D6F8FE657B53D5` FOREIGN KEY (`incompatible_role_id`) REFERENCES `Role` (`id`),
  ADD CONSTRAINT `FK_E9D6F8FED60322AC` FOREIGN KEY (`role_id`) REFERENCES `Role` (`id`);

ALTER TABLE `UserBoxContent`
  ADD CONSTRAINT `FK_A9A6F9D1BF396750` FOREIGN KEY (`id`) REFERENCES `Content` (`id`) ON DELETE CASCADE;
```

**Comment by DeetsCZ** [comment]
Databáze upravena

**Comment by DeetsCZ** [comment]
Prosím úpravu, tak aby při registraci bylo v chybě vypsané, které role není možné kombinovat:
![snimek obrazovky 2016-10-10 v 22 01 36](https://cloud.githubusercontent.com/assets/19816092/19249331/42b7b81e-8f35-11e6-89c8-6cedfe24aab4.png)

Např: "Není možné kombinovat role: účastník, účasník 2"

**Comment by jan-stanek** [comment]
Upraveno, zprávu nelze upravit v závisloti na vybraných rolích, vygeneruje se tedy hláška pro každou roli.

Pokud tedy například účastník nelze zaregistrovat s žádnou jinou rolí a bude jich vybráno více může se zobrazit třeba "Není možné kombinovat role: účastník, lektor, servis tým, super lektor", ale i "Není možné kombinovat role: servis tým, účastník", podle toho, jaké pravidlo se použije dříve.

**Comment by DeetsCZ** [comment]
Měl by se zobrazovat pouze ten konflikt. Tedy teď nejde zároveň vybrat roli účastník a roli účastník 100, dále nejsem účastník a účastník 2, ale účastník 2 a účastník 100 vybrat zle.
Ve formuláři při zadání účastník a účastník 2 se ale vypsalo, že není možné kombinovat účastník, účastník 2 a účastník 100, což je špatně protože účastník 2 a účastník 100 kombinovat lze:
![snimek obrazovky 2016-10-12 v 13 12 39](https://cloud.githubusercontent.com/assets/19816092/19308119/4b27e9e8-907e-11e6-9fba-26d856961be8.png)

**Comment by jan-stanek** [comment]
To je zvláštní, teď jsem zkoušel stejné role a přihlásil jsem se, nezměnilo se něco?

**Comment by jan-stanek** [comment]
Nebo na tom screenu není reálná situace a jde jen o tu hlášku, přitom formář s tímto výběrem by odeslat šel?

Upravil jsem hlášku, aby dávala větší smysl.

![hlaska](https://cloud.githubusercontent.com/assets/11959693/19312894/b468d780-9094-11e6-9040-061ea0d82e1f.png)

**Comment by DeetsCZ** [comment]
Děkuji za úpravy
