### ISSUE TITLE
Mapa s popisem cesty

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#74]
Vytvořit content, který obsahuje textové pole pro popis cesty a body zadané pomocí GPS, které se poté zobrazují na mapě (implementace API Mapy.cz nebo Maps.google.com).

**Comment by jan-stanek** [comment]
Úprava databáze:
```
CREATE TABLE place_point (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, gps_lat DOUBLE PRECISION NOT NULL, gps_lon DOUBLE PRECISION NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE settings CHANGE value value LONGTEXT DEFAULT NULL;
```

**Comment by DeetsCZ** [comment]
Testovala jsem a v administraci je pouze:
![snimek obrazovky 2017-03-20 v 21 19 01](https://cloud.githubusercontent.com/assets/19816092/24119884/02cf0f3e-0db3-11e7-8711-39b2cd6bbeb2.png)

1. prosím přejmenovat Místo na Mapa
2. chybí textové pole pro zadání popisu cesty (ideálně, pokud se sem něco zapíše, potom se zobrazí na webu vedle mapky - mapka se tam zmenší, pokud se nezadá, potom se zobrazí pouze mapka, jako je to nyní)
3. chybí místo pro zadání místa: ideálně by mělo fungovat zadání, jak podle GPS, tak i podle názvu např. Praha

**Comment by jan-stanek** [comment]
V nastavení stránky se přidává jenom obsah, údaje které se v něm zobrazují se nastavují v nastavení.

![misto](https://cloud.githubusercontent.com/assets/11959693/24120341/86d653f4-0db4-11e7-9bae-811d816c0abd.png)
![misto2](https://cloud.githubusercontent.com/assets/11959693/24120344/8b123e92-0db4-11e7-80c3-c2c7f4e2786b.png)

Zjistím proč tam není vidět ta mapka pro výběr polohy místa.

**Comment by DeetsCZ** [comment]
Pardon, moje chyba, nevšimla jsem si toho..
Tak možná jen prosím přejmenovat Místo na Mapa, to místo je trochu matoucí..

**Comment by jan-stanek** [comment]
Mapka už by se měla zobrazovat.

Místo mám dát všude, nebo jen u toho v tom obsahu stránky?

**Comment by DeetsCZ** [comment]
Děkuji za zpracování

**Comment by jan-stanek** [comment]
Ještě není hotové to přejmenování.

Špatně jsem se zeptal, mělo to být: "Mapa" mám dát všude, nebo jen v tom obsahu stránky?
