### ISSUE TITLE
Práva k stránkám u role

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#75]
Nyní se nastavují práva přístupu pro role u každé stránky. Nově by toto nastavení mělo jít zadat u stránky ale také přímo v roli. 
Tedy vyberu si roli, zde budu mít nastavení "Viditelné stránky" a zde vyberu, ke kterým stránkám na přístup.

**Comment by DeetsCZ** [comment]
Děkuji za zpracování. 
Jen prosím Issues z Milestone "Vylepšení" by se měly dělat až jako poslední..

**Comment by jan-stanek** [comment]
Ok, tohle jen implementačně souviselo s jiným issue.

**Comment by DeetsCZ** [comment]
Je pravda, že teď se to hodilo a je dobře, že to tam je zpracované..

12. 10. 2016 v 13:15, Jan Staněk <notifications@github.com>:
