### ISSUE TITLE
Instalace "na klik"

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#77]
Vytvořit instalační balíček, který bude od uživatele vyžadovat pouze zadání údajů k FTP a databázi.

**Comment by jan-stanek** [comment]
V nové verzi nebude zatím nastavení databáze a skautisu v průvodci, protože zápis do config.local.neon a to, že ty údaje chybí před instalací způsobuje spoustu problémů. Takže tohle by bylo ideální řešení, nevím ale o ničem, co by něco takového umožňovalo (kromě toho, že některé hostingy mají průvodce pro wordpress apod.)

**Comment by jan-stanek** [comment]
Nedalo by se na lebedě udělat nějak podobně jako řeší @sinacek pro WP se skautskou šablonou? 

Pokud to má cenu, jiné řešení nevidím.

**Comment by sinacek** [comment]
Ahoj,
udělal bych to asi jen že se to bude pouštět z příkazové řádky na požádání (nebude to v UI) ale pujde to. Jen je potreba udelat ten php script, ktery to vse nastavi. Az dotahnu WP, tak s tim muzu pomoct. 
inspirace: https://github.com/skaut/lebeda/blob/wp/app/Console/InstallWpCommand.php
https://github.com/skaut/lebeda/blob/wp/app/model/Wordpress/WordpressService.php

**Comment by jan-stanek** [comment]
Pro snadné nasazení máme nakonfigurované pipeliny v https://app.buddy.works/skaut-srs/srs/pipelines

Pro přidání nového webu je potřeba:
1. nechat si povolit SSH přístup
1. vygenerovat SSH klíč a přidat přes FTP public key do .ssh/authorized_keys
1. zduplikovat existující pipeline v Buddy
1. nastavit proměnné (SSH klíč, uživatelská jména, hesla, ...)
1. spustit

- local.neon se vygeneruje - není třeba konfigurovat žádné soubory
- při každém nasazení se nahradí všechny soubory a z předchozí verze se nakopírují
  - style.css (vlastní css)
  - adresář files (adresář pro upload souborů, fotek uživatelů, ...)
  - adresář backup (zálohy db)
- při přechodu ze starého způsobu deploymentu je potřeba pročistit FTP

**Comment by jan-stanek** [comment]
@DeetsCZ můžeme zavřít?

**Comment by jan-stanek** [comment]
Instalace přes buddy se myslím osvědčila, zavírám
