### ISSUE TITLE
Náhradníci program

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#771]
Doplnit možnost náhradníků na program.

Možnost zapisovat náhradníky by se měla dát aktivovat v programovém bloku, plus by měla být možnost zapínat a vypínat v jednotlivých opakováních u harmonogramu..

Když se naplní program, tak by se v kaledáři mělo změnit tlačítko na "Přihlásit jako náhradník" (pokud by to bylo příliš dlouhé, tak jen "Náhradník".

Pokud se uvolní místo v programu, tak by se měl z náhradníka stát účastník programu a měl by mu přijít email.

Pokud má uživatel již tento blok zapsaný a chtěl by se přihlásit na jiný termín jako náhradník, tak by to nemělo být možné.

Pokud má blok více termínů a uživatel blok nemá žádný termín zapsaný, tak by se mohl jako náhradník přihlásit na všechny (pokud by to bylo příliš náročné, tak by to mohlo fungovat i tak, že se může jako náhradník přihlásit pouze na jeden termín). Ve chvíli kdy se na jednom termínu uvolní místo a bude z něj účastník programu, tak se mu náhradnictví v ostatních termínech zruší.

**Comment by jan-stanek** [comment]
Neměl by to být problém stihnout do konce roku.

Máš nějakej příklad využití toho, aby se dalo náhradníky vypínat/zapínat i u jednotlivých opakování? Ne že by to bylo nějak náročné na implementaci, spíš aby bylo nastavení co nejjednodušší.

"tak by se mohl jako náhradník přihlásit na všechny" - myslíš to tak, že by se jako náhradník mohl přihlásit na libovolný počet opakování programu, nebo tak že by někde kliknul na tlačítko "chci tenhle program, jedno kdy"?

**Comment by jan-stanek** [comment]
- [ ] nepovolit zmenšit kapacitu bloku pod počet přihlášených účastníků
- [ ] při zvětšení kapacity bloku přihlásit náhradníky
- [ ] zobrazovat v přehledu bloků, jestli jsou náhradníci povoleni

**Comment by DeetsCZ** [comment]
Děkuji za úpravu, vyzkoušeno akci elixír a funguje výborně

**Comment by jan-stanek** [comment]
Vyzkoušeno elixírem, zavírám
