### ISSUE TITLE
Omezující podmínky při tvorbě rozvrhu

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#78]
- [x] Nepovolit v jedné místnosti dva programy ve stejný čas.
- [x] více programů lektora ve stejném čase

Seznam se bude ještě doplňovat...

**Comment by jan-stanek** [comment]
1. hotovo

**Comment by jan-stanek** [comment]
@DeetsCZ: obě podmínky fungují, další mě ani nenapadají
