### ISSUE TITLE
Možnost instalace SRS do podadresáře

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#8]
Při instalaci do podadresáře hází systém E_NOTICE v PagePresenteru, což znemožnuje fungování v debug modu. Přišlo by mi užitečné, kdyby to bylo možné instalovat do libovolného umístění.

**Comment by jan-stanek** [comment]
Špatný odkaz u nadpisu SRS v administraci - místo "/podsložka/admin/" jen "/admin/"

**Comment by jan-stanek** [comment]
Za celou dobu, co to používám pro testování, už jsem nenarazil na jiný problém.

**Comment by DeetsCZ** [comment]
Také jsem nenarazila na problém
