### ISSUE TITLE
Přihlašování na povinné programy

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#80]
1. do programového bloku, přidat checkbox "Přihlásit automaticky"
   - pokud se toto zaškrtne, potom se všichni účastníci, kteří mají roli spjatou s daným programovým blokem automaticky na tento blok přihlásí
2. V tabulce evidence uživatelů přidat sloupec "Nezapsané povinné semináře", zde se u daného uživatele bude zobrazovat počet povinným seminářů, na které se zatím nepřihlásil. Po najetí myší se zobrazí jmenný seznam seminářů, na které není uživatel přihlášený

**Comment by DeetsCZ** [comment]
Jěště doplním jednu chybičku s povinnými programy.
Pokud je program povinný a uživatel se na nějaký přihlásí, potom mu ale další časy tohoto bloku v kalendáři nezešedivý, jako to je u nepovinných. Tedy pokud se přihláším na jeden povinný programový blok, potom ostatní opakování programu mají být šedé a nemělo by dále svítit, že se nemám přihlášený nějaký povinný blok.

**Comment by DeetsCZ** [comment]
To je pravda, řešení s celými povinnými bloky dává větší smysl než nynější řešení. 
Prosím tedy o úpravu, tak aby byl povinný celý blok a účastník se musel přihlásit na jedno z opakování.
Děkuji

**Comment by jan-stanek** [comment]
Upraveny barvy, aby to nebylo matoucí pro miquik. Ostatní úpravy budou trvat déle.

Další problém bude, pokud bude potřeba mít stejný blok v různých místnostech, pokud se to vyřešení založením více stejných bloků lišících se místností, není pak možné kontrolovat, že nejsou zapsány současně. Místnost by se třeba mohla vybírat až při vkládání do kalendáře.

**Comment by jan-stanek** [comment]
Databáze je na to připravena, ale je potřeba dodělat kontroly kolizí při vytváření harmonogramu, přihlašování programů po změně rolí (teď se jen odhlásí ty, ke kterým ztratí přístup). Může se také stát, že má uživatel nějaké nepovinné programy a změnou rolí se mu přidají povinné na dobu, kdy už má nepovinné apod.

**Comment by DeetsCZ** [comment]
On bude vznikat i problém, pokud by se dodatečně upravovali programy a přidal se povinný na dobu, kdy mají někteří nepovinný a podobně..
Bylo by možné přidat kontrolu kolizí vždy při přihlášení uživatele (tím že při změně role dochází také k znovu přihlášení, tak bychom to měli pokryté) a pokud byl uživateli automaticky přidám povinný program, který je v kolizi s jiným, potom by se uživateli nahoře na všech stránkách zobrazovalo varování: "Některé tvé programy jsou v kolizi, prosím zkontroluj si svůj harmonogram na stránce pro zápis programů." (není to ideální, ale teď mne nenapadá lepší vyjádření). Je to možné takto udělat?

**Comment by jan-stanek** [comment]
Asi to tak bude lepší, kdyby se to mělo řešit při vytváření harmonogramu, tak to bude strašně složité kontrolovat.

To automatické zapisování povinných by se teda dělalo bez ohledu na kolize, ale jen pokud je ten blok zařazenej v harmonogramu jenom 1x? Nějak takhle máme i rozvrhy ve škole, líp to asi moc vyřešit nejde.

Pustil bych se do toho po dodělání automatických mailů #58

**Comment by DeetsCZ** [comment]
Přemýšlím, jestli bychom to nemohli ještě udělat jinak..
Co takhle:
1. odškrtnu, že blok je povinný
2. zobrazí se mi možnost "Automaticky přihlásit všechny", odšktrnu
3. takový program potom mohu vložit do harmonogramu pouze jednou a jen do prázdného místa
4. jiné programy není možné dát na toto místo
5. pokud při úpravě programu odškrtnu "Automaticky přihlásit všechny", potom se z něj všichni uživatelé odhlásí

Přijde ti to reálné, nebo je to příliš náročné?

**Comment by jan-stanek** [comment]
Přemýšlel jsem o tom a je to asi jediná možnost jak to udělat, ty ostatní způsoby mi sice přijdou trochu přívětivější pro uživatele a umožnily by automaticky zapisovat víc programů, ale aby u nich nevznikaly problémy, tak by to chtělo, aby se před přihlašováním uživatelů zamkla úprava harmonogramu.

**Comment by jan-stanek** [comment]
`ALTER TABLE block CHANGE mandatory mandatory INT NOT NULL`

**Comment by DeetsCZ** [comment]
Nahrála jsem na testweb i se změnou v databázi, ale v programovém bloku možnost "Automaticky přihlásit" chybí..

**Comment by DeetsCZ** [comment]
Napadá mne, že navíc budeme muset hlídat zařazení bloku v kategorii..

**Comment by jan-stanek** [comment]
Nenahrála se tam žádná změna.

Kategorie se hlídá, jediné co se nehlídá je, když se u bloku kategorie změní, to ale nezpůsobuje ani odhlášení těch, kdo k němu ztratí přístup.

**Comment by DeetsCZ** [comment]
Na srs.skauting.cz se aktualizace normálně nahrála..

**Comment by jan-stanek** [comment]
Mám rozdělanou úpravu, aby se přihlašování/odhlašování dělo i při změně kategorie, změně rolí u kategorie a při odstranění kategorie.

Zatím prosím neuzavírat.

**Comment by jan-stanek** [comment]
Přidání automaticky zapisovaných programů a odhlášení programů, které už uživatel nemá dostupné, by mělo probíhat při těchto událostech:
- vyplnění přihlášky
- změna rolí v profilu
- úprava rolí v editaci uživatele
- hromadná úprava rolí
- odstranění role
- vytvoření automaticky přihlašovaného programu
- nastavení automatického přihlášování u bloku (v editaci bloku i přepínačem v přehledu bloků)
- změna kategorie bloku
- změna rolí u kategorie
- odstranění kategorie

**Comment by jan-stanek** [comment]
Ještě tam chybí odchytit to, když se u role odebere/přidá oprávnění zapisovat si programy.

**Comment by jan-stanek** [comment]
Doplněno

**Comment by DeetsCZ** [comment]
Otestováno snad ze všech stran. Děkuji
