### ISSUE TITLE
Ošetření chyby při nezadání ceny za roli

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#826]
Pokud se nezadá cena u role, potom sytém spadne na chybě.
Řešením je buď:
1. při nezadání automaticky považovat za 0
2. při nezadání vypsat chybu: "Prosím zadejte cenu"
3. automaticky vždy předvyplnit 0

Všechna řešení mi přijdou dobrá, takže bych vybralo to, kde je nejjednodušší implementace.

Moc děkuji

**Comment by jan-stanek** [comment]
Nejlepší varianta (konzistentní s chováním SRS jinde) mi přijde: 2. při nezadání vypsat chybu: "Prosím zadejte cenu"
