### ISSUE TITLE
Instalátor není kompatibilní s nettrine/migrations >= 0.8

### ISSUE THREAD

**Issue by petrparolek** [skaut/SRS#853]

**Comment by jan-stanek** [comment]
Jaký tam je problém? Už delší dobu je tam `"nettrine/migrations": "^0.7"` a žádný problém nikdo nehlásil

**Comment by jan-stanek** [comment]
Vlastně to může být tím, že migrace spouštíme jako součást deploymentu. Ale stejně budu rád za přesnější popis.

**Comment by petrparolek** [comment]
Omlouvám se za překlep, má být 0.8 a ne 0.5

**Comment by jan-stanek** [comment]
zdá se, že po úpravách nebo s novými verzemi se už neprojevuje
