### ISSUE TITLE
Odebrat nullable u value v CustomMultiSelectValue

### ISSUE THREAD

**Issue by jan-stanek** [skaut/SRS#854]
Byla odebrána už dříve, ale zapomnělo se na migraci

**Comment by petrparolek** [comment]
Přidám migraci v PR.

**Comment by jan-stanek** [comment]
Nepřidávej prosím, mám teď otevřenej jinej PR s migrací

**Comment by jan-stanek** [comment]
nullable je tam správně, prázdné pole se ukládá jako null
