### ISSUE TITLE
Chyba: zobrazení profilu na frontpage

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#86]
Po kliknutí na jméno uživatele se nezobrazí jeho profil, ale chyba:
![snimek obrazovky 2016-10-10 v 21 37 31](https://cloud.githubusercontent.com/assets/19816092/19248725/eee08bf6-8f31-11e6-9d12-f692e3b45e8e.png)

**Comment by jan-stanek** [comment]
To bude nejspíš chybějící knihovna, měla se ale stáhnout přes composer.

Můžeš prosím zkusit `composer install --no-dev` a podívat se, jestli se stáhla složka libs/global/pear?

**Comment by DeetsCZ** [comment]
Nic se nestáhlo..

**Comment by jan-stanek** [comment]
To je zvláštní, mě se to stahuje. Není možné, že by byla starší verze souboru composer.json? V requiere by měl být řádek `"pear/numbers_words": "0.18.1"`

**Comment by DeetsCZ** [comment]
Na e-mail jsem ti poslala vše, co composer vypsal..

**Comment by DeetsCZ** [comment]
Děkuji za řešení. Již funguje..
