### ISSUE TITLE
Úprava rolí

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#866]
Při těchto úpravách budeme vycházet ze současných rolí.
U role se bude nastavovat, zda se má zobrazit v přihlášce pro jednotlivce, pro družiny nebo pro jamoddíl.
U role bude možné nastavit další pole:

Věk: budou zde 4 položky
- od: bude se zadávat datum narození do určitého data
- textové pole pro vyplnění chybové hlášky při pokusu vybrat tuto roli u mladší osoby
- do: bude se zadávat datum narození od určitého data
- textové pole pro vyplnění chybové hlášky při pokusu vybrat tuto roli u starší osoby

Pokud se nechá pole volné, potom se bere věkové hranice jako neomezená

**Comment by jan-stanek** [comment]
Bude se zadávat min/max věk, ne min/max datum narození, ok?

**Comment by bojovyletoun** [comment]
Jj

**Comment by bojovyletoun** [comment]
Částečně jsem to tam přidal, ten maximální věk (v tom prvnim+2 commitu je poznámka, jestli  se hodí víc kontrola k začátku nebo konci akce). Ty  editovatelné chybové hlášky jsem ještě nepřidával. Sice  (přihláška nového člověka na akci) se ukazuje hláška přímo u pole Rolí, to chybová hláška přímo u pole role, navíc  (ještě by se tam mohl přidat placeholder  něco jako " a věk pro tuto roli je %d let"), ale to nestačí že ne. Případná chyba by se přidala přímo k chybám formuláře (nette Forms  rozlišuje chyby  u jednotlivých polí, ale jde přidat i hláška k formuláři jako takovému, to je ono, že)
