### ISSUE TITLE
Přidání přehledu družin

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#868]
Stránka bude v nastavení pod položkou Uživatelé (bylo by dobré toto nějak přejmenovat, ale teď mne nenapadá vhodný název, nějaký nápad?).

V přehledu bude výpis družin s položkami:

identifikátor, jméno družiny, datum založení, jamoddíl a tlačítko pro detail
v detailu budou vypsané všechny podrobnosti a výpis všech osob s jejich rolemi

**Comment by jan-stanek** [comment]
Nechceme mít tohle spíš v detailu oddílu? Je k něčemu vidět všechny družiny?

**Comment by DeetsCZ** [comment]
Vlastně si v současném pojetí nejsem jistá, jestli to k něčemu bude. Ověřím u @davidurban…

**Comment by bojovyletoun** [comment]
Mělo by jít o něco téměř něco stejného jako ten přehled jamboddílů? Tedy pokud to ta bude

**Comment by davidurban** [comment]
Bude to stránka podobná nynější registrační stránce. Bude umožňovat výměnu lidí v družině i dospělých, ale neumožní uložení, pokud se změní celkové počty (s příslušnou hláškou).

**Comment by jan-stanek** [comment]
Tady je tím myšlen přehled v administraci, jestli se nepletu

**Comment by davidurban** [comment]
Ať žijou konkrétní popisky issues :(… 

V adminu budeme potřebovat dělat dost podobné věci, nicméně očekávám výpis Skupin (dle nové terminologie) s kontakty na registrujícího vedoucího. Následně výpis všech družin s kontaktem na jejich vedoucího. Ideální bude, když na těchto výpisech bude vždy počet členů, aby se nám to potom dobře kombinovalo. A samozřejmě export do excelu. 

Lepší? :-)

**Comment by jan-stanek** [comment]
Díky za upřesnění, takže ta tabulka družin bude také potřeba, na jamooddíly/skupiny máme #871

**Comment by jan-stanek** [comment]
Tohle je asi hotové, ne?

**Comment by jan-stanek** [comment]
Hotovo
