### ISSUE TITLE
Registrační formulář pro skupiny

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#870]
Formulář se bude do stránky přidávat jako jeden z modulů.
---------------------------------------------------------------------------------------------------
**První krok "Přihlášení":**
Pokud přichází na stránku nepřihlášený uživatel, tak stránka obsahuje pouze tlačítko přihlásit.

---------------------------------------------------------------------------------------------------
**Druhý krok "Družina":**
Na stránce je přepínač rolí tak, aby uživatel stále věděl v jaké roli pracuje. S popisem: "Prosím zkontroluj si, že pracuješ ve správné roli."

Jméno družiny:
- jméno bude povinné, předvyplněné bude "Družina" a její ID (např. Družina 5)
- pokud zadají své jméno, potom se jméno může opakovat

Dále se liší podle role:
1. Vedoucí družiny (admin, nebo zástupce)
- Vidí členy své družiny a může je vybrat
2. Vedoucí oddílu (admin, nebo zástupce)
- Vidí členy oddílu a pokud má oddíl družiny, potom jednotlivé členy seskupené podle družin
3. Vedoucí střediska (admin, nebo zástupce)
- Vidí seznam oddílů, a po vybrání oddílu se teprve načítají osoby viz bod 2

Je zde vypsané varování: "Pokud chceš ty sám jet s družinou, potom se nezapomeň vybrat!"

Vybrané osoby se přidávají na seznam pod formulářem.
U každé osoby se dále vybírá její role.
Pokud osoba, které byla role vybraná nesplňuje podmínky, potom se u osoby zobrazí chybové hlášení a není možné pokračovat. 
Chybová hlášení, která by zde mohla být:
1. Osoba nesplňuje věk: hlášení při překročení minimálního a maximálního věku se nastavuje u každé role. 
2. Počet osob s danou rolí není splněn: v nastavení u družin se bude nastavovat počet osob v dané roli, například pro NSJ bude počet účastníků 4-12, rádce 0-1 a přesně jeden vedoucí nad 18 let
3. Osoba je již zaregistrovaná v jiné družině: u každé role se bude nastavovat, jestli se má zobrazit v družině a zda se může opakovat v jiných družinách. Například v NSJ se účastník ani rádce v družinách opakovat nesmí, ale dospělí vedoucí může být ve více družinách.

Pokud jsou podmínky splněny je možné pokračovat na další krok.

---------------------------------------------------------------------------------------------------
**Třetí krok "Jamoddíl":**
V tomto kroku jsou vypsané všechny vybrané osoby s rolemi a s detaily ze skautIS:
Jméno, příjmení, adresa, kontakt, u osob do 18ti let jsou zde vypsané údaje o rodičích a poté pole s dalšími údaji o osobě ze skautIS. Toto pole by mělo být nazvané zdravotní omezení a mělo by být editovatelné.

Dále zde bude možnost vybrat další osoby do jamoddílu
- ideálně po kliknutí na tlačítko "Přidat osoby do jamoddílu" se zobrazí stejný formulář jako u výběru osob u družiny
- opět se vybírají osoby a k nim se přidává role, pokud bude pro jamoddíl povolená pouze jedna role, potom by se mohla předvybrat (pro NSJ se bude vybírat pouze dospělí doprovod)

Chybová hlášení jsou identická jako v případě družiny:
- u NSJ by mohla nastat situace, že je překročen počet dospělých osob (toto se bude nastavovat v nastavení u jamoddílu), zde to smí být maximálně 2x počet družin
- dále u NSJ nesmí být vybrán dospělý ve více jamoddílech

Dále zde bude možnost přidat další družinu, toto zopakuje krok 2. Tento krok bude možný, pokud již jamoddíl neobsahuje maximální počet dětí. To se bude nastavovat u Jamoddílu. Pro NSJ se jedná o 38-42 účastníků plus rádců. Pokud by se další družina již nevešla, potom se vypíše chybové hlášení "Další družinu není možné zadat, jamoddíl může obsahavat maximálně 38-42 účastníků. Další jamoddíl musí zadat jiná dospělá osoba"

Pokud jsou splněny všechny podmínky, potom je možné pokračovat.

---------------------------------------------------------------------------------------------------
**Čtvrtý krok "Dokončení":**
Zde jsou opět vypsané všechny osoby s detailními informacemi.
Celková cena za jamoddíl: cena se počítá jako počet osob krát cena za roli kterou mají
Dvě zaškrtávána: 
- Souhlasím s podmínkami akce
- Veškeré vyplněné údaje jsou platné

Na stránce jsou dále 3 tlačítka:
Zpět : pro návrat k předchozímu kroku
Uložit : uloží jamoddíl jako "rozpracovaný"
Závazně odeslat přihlášku: 
- pokud vyplňuje osoba pod 18 let, potom se žádost o potvrzení odesílá na email vedoucím družin, kdy jamoddíl musí potvrdit alespoň jeden z nich (jamoodíl je ve stavu "ke schválení")
- pokud vyplňuje dospělá osoba, potom se jamoddíl rovnou potvrdí jako schválený

**Comment by DeetsCZ** [comment]
Po poslední poradě zjednodušujeme toto zadání:

**Přihlášení:**
Pokud přichází na stránku nepřihlášený uživatel, tak stránka obsahuje pouze tlačítko přihlásit.

------------------------------------

**Jamoddíl:**
Na stránce je přepínač rolí tak, aby uživatel stále věděl v jaké roli pracuje. 
S popisem: "Prosím zkontroluj si, že pracuješ ve správné roli."

Na této stránce je zobrazen Jamoddíl s jeho ID (např. Jamoddíl 12).
Uživatel vždy musí pracovat v roli, kde má práva vidět podřízené členy. Z pravidla zadává vedoucí oddílu, jeho zástupce nebo admin oddílu.

Stránka obsahuje dvě tlačítka:
**Zadat družinu do jamoddílu** (tlačítko je aktivní, pokud je celkový počet účastníků + rádců menší než 38, jinak je tlačítko neaktivní)
- maximální počet dětí (účastníci a rádce) v rámci jamoddílu je 42: počet 38 znamená, že je možné ještě přidat družinu s 4mi účastníky
- pokud je tlačítko neaktivní měl by se doplnit text "Není možné přidat další družinu do jamoddílu, protože maximální počet dětí je 42, další jamoddílu musí přidat jiná dospělá osoba"
**Přidat dospělého člena jamoddílu** (tlačítko je aktivní pouze, pokud je počet dospělých menší než (2x počet družin -1), jinak je tlačítko neaktivní)
- pokud je tlačítko neaktivní měl by se doplnit text "Není možné přidat další dospělou osobu, dospělých v rámci jamoddílu může být jen 2x počet družin"


Po kliknutí na přidat dospělého se zobrazí přehled podřízených osob, kde je možné vybrat dospělou osobu a přidat ji do jamoddílu.
Po kliknutí na Přidat družinu se zobrazí formulář pro přidání družiny.


Pod tlačítky je přehled již přidaných družin s i jejich členy a přehled již přidaných dospělých osob
Dále celková cena za jamoddíl: cena se počítá jako počet osob krát cena za roli kterou mají (aktualizuje se po přidání družiny nebo dospělého)

Dvě zaškrtávána:
- Souhlasím s podmínkami akce
- Veškeré vyplněné údaje jsou platné

Na konec je tlačítko: Závazně odeslat přihlášku
-------------------------------------------------------

**Družina**

Na stránce je přepínač rolí tak, aby uživatel stále věděl v jaké roli pracuje. S popisem: "Prosím zkontroluj si, že pracuješ ve správné roli."

Jméno družiny:
- jméno bude povinné, předvyplněné bude "Družina" a její ID (např. Družina 5)
- pokud zadají své jméno, potom se jméno může opakovat

Podle vybrané role se zobrazí seznam podřízených osob a je možné je vybrat.
Vybrané osoby se přidávají na seznam pod formulář.
U každé osoby se dále vybírá její role. V rámci družiny se zde bude vybírat pouze role účastník a rádce.
Pokud osoba, které byla role vybraná nesplňuje podmínky, potom se u osoby zobrazí chybové hlášení a není možné pokračovat.
Chybová hlášení, která by zde mohla být:

Osoba nesplňuje věk: hlášení při překročení minimálního a maximálního věku se nastavuje u každé role.
Počet osob s danou rolí není splněn: počet účastníků je přesně 4-12 a rádce je maximálně jeden
Osoba je již zaregistrovaná v jiné družině.
Pokud jsou podmínky splněny je možné potvrdit družinu a vracíme se na stránku jamoddílu.

**Comment by DeetsCZ** [comment]
Stránka Jamoddílu by mohla vypadat nějak takto:
<img width="512" alt="Snímek obrazovky 2022-10-14 v 13 47 51" src="https://user-images.githubusercontent.com/19816092/195839782-106ee1e0-e89d-44b6-8198-ba8894b5ac8e.png">

**Comment by DeetsCZ** [comment]
Stránka Družina:
<img width="514" alt="Snímek obrazovky 2022-10-14 v 14 27 35" src="https://user-images.githubusercontent.com/19816092/195846888-7668a5a4-3b08-41d9-98b5-5362091a6ef2.png">

**Comment by davidurban** [comment]
Přidávám UX návrh a prosím kluky (@jan-stanek ) i @DeetsCZ o diskusi. Až se tu shodneme, rád bych ještě verifikoval s vedením NSJ:

# Registrace prázdná (po přihlášení)
![Registrace výpravy prázdná](https://user-images.githubusercontent.com/8739891/195893359-dbafe7d4-0fa7-4ae3-8a4c-e2f9b6cfb68d.png)

# Registrace vyplněná 
![Registrace výpravy](https://user-images.githubusercontent.com/8739891/195893419-73dceea1-12de-4414-92c9-09e56b44958f.png)

## Editace družiny
![Editace družiny](https://user-images.githubusercontent.com/8739891/195893452-d8875ec4-c837-44a9-8032-1ab16203e333.png)

**Comment by jan-stanek** [comment]
Díky za návrh, myslím, že to půjde. Jen to nebude dokonale interaktivní formulář v javascriptu.

**Comment by jerrysohn** [comment]
Doplňuji nějaké poznámky - typicky opravy názvosloví a textů:  
* vysvětlivka pod "pracuješ v roli" by spíš měla na konci mít "... z členů tvé jednotky", tedy vyškrtnout slovo "organizační", protože vedoucí oddílu bude vybírat jen ze svého oddílu a ne celého střediska (tedy jen obecně "jednotky")
* informace u částky k platbě - **POZOR: tady je splatnost do 30 kalendářních dní** (chybně v textu máte 14 dní, což je jen pro servistým a ne běžné skupiny účastníků)
* počty pod tabulkami družin - **POZOR: družina může mít 4 až 12 mladších členů** (počítá se do nich běžný člen i osoba označená jako rádce), ale v textu je chybně 4/10 - mělo by být správně 4/12; a rádce se započítává do členů, naopak dospělý se vůbec do počtu členů družiny nepočítá - navrhuji tedy ten text pod tabulkami opravit na "Družina má X z 12 možných účastníků (z toho 0/1 rádců) a 1/1 vedoucí"

**Comment by jerrysohn** [comment]
A pak ještě dávám ke zvážení, zda by nebylo lepší, jen místo odkazu na podmínky nad tech checkbox ještě přímo podmínky vypsat - jen do divu s pevnou výškou, ve kterém bude možné textem posouvat. Protože pokud jsou podmínky jen jako "odkaz" někam jinam, tak je čte ještě méně lidí. Ale kdyby nad tím byl vidět rovnou kus textu, který se dá rovnou posouváním pročíst (a přitom to na stránce rovnou neblokuje několik stran textu), tak je šance, že si to přečtou a nebudou pak tvrdit, že to vlastně neviděli a nevšimli si. Tedy checkbox samozřejmě zachovat, ale text podmínek by tam v HTML mohl být rovnou vidět (v divu s přiměřenou pevnou výškou a posuvníkem na rolování textu jen čistě podmínek).

**Comment by jerrysohn** [comment]
@davidurban jinak mi přijde, že tam v těch tvých návrzích nějak chybí ta stránka, kde jsou u každé osoby vypsané všechny údaje (jak ty načtené ze skautISu - jména, adresy, kontakty na rodiče, tak ty doplňované navíc během přihlášky speciálně pro NSJ). @DeetsCZ to měla v návrhu nazvaném výše "Stránka Družina:". To je věc, kterou má ten vedoucí na konci přeci vidět jako souhrn a spolu s tím potvrdí platnost údajů a celé podmínky. Ale možná to nepotřebuje další překreslení a je to v pohodě, jak to navrhla Péťa.

**Comment by davidurban** [comment]
@jerrysohn souhrn údajů ze SkautISu o lidech jsem záměrně nedělal. Dle mého to nikdo kontrolovat nebude, nemluvě o tom, že to v tomhle kontextu nejde upravovat. Chápu, že technicky to přeneseme do přihlášky, ale vypisovat mi to přijde zbytečné. Pokud nesouhlasíte, prosím napište, jaké položky a pro by se měly zobrazovat. Já za sebe nenašel důvod ani pro jednu. 
I když je tam dáme a vedoucí přijde na chybu, tak moc nevím, co bude dělat. Zruší registraci, půjde upravit SkautIS a pak udělá registraci znovu? Lepší by mi přišlo, kdyby se mu souhrn poslal komplet na mail s tím, že pokud jde něco blbě, má kontaktovat registraci a my si to upravíme u nás…

**Comment by jerrysohn** [comment]
@davidurban mně ten přehled údajů přijde podstatný - odvolávají se na něj od začátku podmínky účasti a registrace, vedoucí, který přihlašuje členy odpovídá za to, že jsou údaje platné. Jsou v tom základní údaje o členech (když bychom ignorovali bydliště - což asi lze, tak je tam například datum narození, který hraje roli pro účast na akci), jsou tam kontakty na rodiče (což je klíčové pro případ problémů - odpovědnost nese vedoucí, ale tady tím vedoucí potvrdí, že tam kontakt je platný) a jsou tam všechny zdravotní a stavovací omezení (část ze skautISu, část jako doplnění vlastních otázek přímo přeci z registrace na NSJ). Takže mi přijde, že tam vypsané spíš být mají (jinak nutíme odpovědnost vedoucímu, ale nedáváme mu údaje ani k náhledu). 
Jinak údaje, co jsou ve skautISu má pak vedoucí samozřejmě zajistit aktualizaci ve skautISu (tam má na to nástroje a širší možnosti) a záleží na něm, jak to bude řešit (v ideálním případě má vše aktuální a jen to potvrdí, pokud nemá, je to na něm, zda potvrdí, nebo nejprve půjde provést do skautISu aktualizaci).
Údaje, které se doplňují až přímo v rámci registrace NSJ, tak ty tam musí mít možnost navíc doplnit v rámci nějakých "vlastních otázek akce" - předpokládám, že nějaké takové mít budete, stejně jako je to u ST.
Proto se s tím od začátku počítalo v podmínkách, proto to Péťa navrhovala v těch jejich náčrtcích a tom, co s klukama probírala, že se má naprogramovat. Aspoň tak jsem to od začátku chápal a přišlo mi to pro bezpečnost provozu akce potřebné.

**Comment by davidurban** [comment]
Přijde mi nesmysl kontrolovat akce ze zdroje, který považujeme za pravdivý. Když na tom trváš, tak to tam dokreslím, ale řekni si, jaké údaje tam chceš. Mně adresa přijde nesmyslná, datum narození hlídá systém a je taky k ničemu. Alergie a jídlo asi může dávat smysl. Kontakt na rodiče bude někdo těžko kontrolovat. Je to výpis pro výpis a abychom se tvářili, že to někdo řeší. 

Tedy – dokreslím, řekni co tam chceš.

**Comment by davidurban** [comment]
<img width="1003" alt="Screenshot 2022-10-18 at 10 58 38" src="https://user-images.githubusercontent.com/8739891/196385607-142fc5ff-350f-499a-b55d-2263a7135cb2.png">

Požadavek vede na grid s účastníky. Dělal bych ho jen v kontextu družiny, jinak bude výpis celého JO neúnosný. 

My nechceme zatím žádná extra pole, potřebujeme pouze údaje o člověku, kontakt na rodiče, zdravotní omezení a jídlo. Pokud něco z toho není ve SkautISu, tak musíme zadávat u nás. Prosím @DeetsCZ o info co je ve skautISu.

**Comment by davidurban** [comment]
Aktualizace

[nsj2023-rs.pdf](https://github.com/skaut/SRS/files/9809661/nsj2023-rs.pdf)

**Comment by jan-stanek** [comment]
Jen připomínám, že to jsou klasický Nette forms, ne že by k tomu nešel nějakej vlastní JavaScript, ale bude s tím spousta práce oproti nějakýmu JS frameworku :-(

**Comment by davidurban** [comment]
@jan-stanek s Nette JS mám pramalé zkušenosti. Co je třeba optimalizovat. aby to bylo pro vás snazší? Nebo si zavoláme?

**Comment by jerrysohn** [comment]
Omlouvám se, že do toho tím požadavkem na zobrazení podrobnějších údajů o osobách vnáším komplikace (ale vnímal jsem to tam jako věc domluvenou od začátku a jako věc, která má zajistit přiměřenou transparentnost v tom, že vedoucí opravdu potvrzuje správnost údajů - mimochodem, máme i oddíly, kde jsou osoby se stejným jménem a bez zobrazení některých dalších údajů prostě nebude poznat, kdo je kdo). Ale pokud řeknete, že to je už časově nestihnutelné (jsem velmi mrzutý z toho, že jsme museli přistoupit na ostré spuštění registrace hned 1.11. a nezískali jsme ani týden navíc), tak to prostě máme zjednodušit i v této věci (ač bych nerad a dávalo by mi smysl, aby tam ty údaje, jak dokreslil Ňuf byly uvedeny).

A teď ještě doplním několik reakcí a podrobností, které snad trochu pomůžou:

@jan-stanek Předpokládal jsem, že na výpis osob pro vybírání osob do přihlašované družiny budeš používat funkci MembershipAll (https://is.skaut.cz/junakwebservice/OrganizationUnit.asmx?op=MembershipAll). To je jednoduše přehled, ve kterém se dá zavolat i varianta s podřízenými jednotkami - tedy když se na to díváš s oddílové úrovně a oddíl používá družiny, ihned se ti v té tabulce vypíše seznam osob a u nich i informace, že jsou z nějaké konkrétní družiny (řídí se příznakem OnlyDirectMember boolean). Což by myslím ulehčovalo programování a zároveň je možné vybírat lidi z celého oddílu bez ohledu na to, zda ve skautISu družiny používají či nikoliv.
Zároveň to jako jeden vstupní parametr má případně hledání podle příjmení. Ale možná bude vhodnější to pak filtrovat až nad celým seznamem už v rámci stránky SRS.
Jinak obecně platí, že nikdy nelze získat více jak 500 záznamů - je to kvůli tomu, aby se právě nedaly filtrovat neomezené počty seznamů členů jednotek. Takže pokud by ses snažil získat seznam členů celého střediska vč. podřízených jednotek, tak u těch několika obrovských středisek (nad 500 osob) by se tam nevrátili všichni (ale v takovém středisku mi přijde, že je to zcela v pořádku a musí to přihlašování dělat oddíloví vedoucí, protože ze střediskové úrovně stejně nebudeš vědět, kdo je kdo v tak obrovském počtu lidí).
Zároveň je v tom přehledu vždy informace o konkrétní jednotce (evidenční číslo jednotky - RegistrationNumber), což je věc, kterou u všech přihlášených osob ukládáme a máme v SRS mít k dispozici (jako to máme u běžných přihlášených lidí v ST apod., tak myslím, že i u přihlášených účastníků v družinách (abychom věděli, odkud jsou - potřebujeme to vědět aspoň na středisko, ale tady je to rovnou v tom seznamu k dispozici klidně až na družinu).

Pokud jde o ty zdravotní údaje, tak máš pravdu, že jsou to tzv. citlivé údaje a ty opravdu vidí jen oddílová úroveň. Takže pokud se bude snažit přihlásit účastníky osoba ze střediskové úrovně, tak žádné zdravotní údaje nezobrazí. Podle mě je to tak správně, protože je to klíčová ochrana osobních údajů. A pokud se rozhodnou opravdu tohle tak dělat, tak buď se má přepnout do oddílové role (a vědomě ji použít) nebo se mu prostě ty údaje ze skautISu nenačtou (i kdyby tam vyplněné u osoby byly). 
Zároveň je to opravdu tak, že nemáme funkci, která by jednoduše uměla vrátit seznam všech citlivých (dalších) údajů pro celý seznam osob - právě proto, že jde o citlivé údaje, musí se zobrazovat až voláním pro konkrétní osobu (je na to WS funkce PersonOtherDetail - https://is.skaut.cz/junakwebservice/OrganizationUnit.asmx?op=PersonOtherDetail) - klíčové mi přijdou údaje: **Allergy (alergie), Drugs (užívané léky), HealthLimitation (zdravotní omezení), BodySkills (plavecké a tělesné dovednosti)**. Bohužel nemáme ve skautISu žádnou kolonku na **stravovací omezení,** což je asi věc, která by se měla objevit jako vlastní otázka v SRS (podobně jako se na ni ptáte u servistýmu.

Nevím, jestli to není komplikace, ale možná by se to dalo udělat tak, že se v těch kartičkách detailních údajů o přihlašovaných osobách výše uvedené údaje (navíc vč. alespoň jednoho kontaktu na rodiče) zobrazí rovnou v textových polích - tedy když to bude ze skautISu, načte se to, pokud to nebude, bude moci vedoucí údaje doplnit a uložit do přihlášky v SRS. (a bude jen na jeho rozhodnutí a odpovědnosti, zda ty údaje aktualizuje, doplní nebo se rozhodne nechat prázdné, pokud mu to tak přijde správné).
Pokud si @jan-stanek dovedeš výše popsané představit jako zvládnutelné, přišlo by mi to nejrozumnější. Jestliže je to úplně mimo, pak se na detailní údaje vykašleme (i když mi to přijde z pohledu na odpovědnost a potvrzovanou správnost údajů právně problematické) a mějme tam jen základní údaje o jméně osobě, datu narození a informaci o jednotce (nemusí být pak asi nutně zobrazeno, ale musí se s tím pracovat a ukládat to).

**Comment by jan-stanek** [comment]
Díky za popis skautIS metod. 

Jestli chceme stihnout alespoň něco, tak bych šel nejjednodušší možnou cestou a pak případně rozšiřoval. Bohužel mám nějaký čas hlavně do neděle, příští týden nic moc a ve čtvrtek odjíždím.

**Comment by davidurban** [comment]
Nový UX po konzultace s @jan-stanek a @DeetsCZ . Dávám na kontrolu a schválení ještě do týmu NSJ. Pokud něco odhalíte, prosím taky o info zde 🙂
[nsj2023-rs.pdf](https://github.com/skaut/SRS/files/9823342/nsj2023-rs.pdf)

**Comment by DeetsCZ** [comment]
Díky moc, že jste to probrali.
Prošla jsem to rychle a zatím mne napadla jedna věc. Je tam poznámka:
“Pokud sám sebe nepřiřadí k družině, je
registrující automaticky doprovodem.”
My jsme se ale při posledním zjednodušení bavili, že on do družiny přidá pouze účastníky a rádce a sám zadavatel bude vždy automaticky přidán jako dospěli vedoucí té družiny.

**Comment by davidurban** [comment]
@DeetsCZ : jj, jen to dle mého platí pouze pokud do družiny nepřiřadí jiného dospělého… S @jan-stanek jsme se bavili tak, že bychom při registraci první družiny registrující osobu rovnou předvybrali. Oni by si to mohli změnit a při odesílání registrace by se udělala validace (aby tam byl, případně se doplnit k družina, kde vedoucí není)… Je to takhle ok? Nebo to nechápu?

Update UX, drobné textace:
[nsj2023-rs.pdf](https://github.com/skaut/SRS/files/9823686/nsj2023-rs.pdf)

**Comment by davidurban** [comment]
Výprava se přejmenuje na skupina.

[nsj2023-rs.pdf](https://github.com/skaut/SRS/files/9830570/nsj2023-rs.pdf)

**Comment by jan-stanek** [comment]
@jerrysohn není ten limit pro MembershipAll 1000, nebo to je jen v testovacím?

**Comment by jerrysohn** [comment]
Myslím, že v ostrém je ten základní limit opravdu 500. Ale asi bych si s tím nedělal hlavu a prostě se na to neohlizel, tak velkých středisek je jen pár a budou se spíš hladit po oddílech.

**Comment by jan-stanek** [comment]
@davidurban nevadilo by, kdyby se v tom názvu skupiny použil místo čísla střediska a pořadového čísla variabilní symbol? Ten máme vygenerovaný jednoznačně a nebylo by pak třeba přejmenovávat všechny družiny

**Comment by jan-stanek** [comment]
@jerrysohn pro hledání kontaktů na rodiče je nejlepší použít `PersonContactAllParent`? Dostávám u velké části osob chybu, že k nim nemám oprávnění, i když jsem v roli vedoucí střediska nebo vedoucí oddílů a jsou z mých podřízených jednotek.

Třeba osoba 143547 a roli mám vedoucí/admin střediska 411.01 (uživatel kraj.vary)

**Comment by davidurban** [comment]
@jan-stanek ano, to je cajk. Jen abychom měli nějaký jednoznačný identifikátor i pro naše účely.

**Comment by jerrysohn** [comment]
@jan-stanek pro získání kontaktů používáš správnou funkci a i s ohledem na oprávnění je správně funkční. Ale problém je v tom, že tato funkce je dostupná jen pro děti (jen osoby do 18 let). Jakmile se jí pokusíš zavolat u dospělého, tak skončí (správně) chybou, protože přehled kontaktů na rodiče je takto dostupný jen u dětí.
A právě to ID_Person=143547 je už 23letá dospělá, proto dostaneš chybu. Když zkusíš např. ID_Person=145388 (je to dítě) dostaneš kontakty na oba rodiče, stejně tak ID_Person=145156 (je to dítě), dostaneš kontakt na jednoho zadaného rodiče a ID_Person=142753 (je to dítě), projde bez chyby, ale kontakty to nevrátí, protože žádný rodič není u dítěte zadaný.
Je tedy potřeba tu funkci volat jen u osob, které jsou mladší 18 let, protože jen pro děti se takto vypisují kontakty na zákonné zástupce.
(a všiml jsem si, že v těch testovacích datech je právě spousta fiktivních osob, které mají sice kategorie benjaminek, vlče, skaut apod., ale dle věku už jsou dávno dospělí, tak proto to možná trochu mate)

**Comment by jan-stanek** [comment]
@jerrysohn díky, ten věk mě napadl až jako poslední a už jsem ho nestihl vyzkoušet. 

Ty chybové hlášky o nedostatečných právech vytváří přímo skautIS nebo to je nějaká univerzální hláška, kterou vytváří skautIS knihovna, když se cokoliv nepovede? Bývá to občas docela matoucí, zvlášť jestli u osoby, které je dneska 17 to projde a zítra až jí bude 18, tak dostanu chybu :(

**Comment by jerrysohn** [comment]
@jan-stanek je to hláška vznikající přímo na vrstvě oprávnění nad databází, kde to odpovídá realitě (tato operace není za určitých podmínek - zde je to právo na osobu + věk osoby - dovolena, a proto je vrácena hláška, že na ten záznam není oprávnění k získání dat)

**Comment by jan-stanek** [comment]
Co jsem stihnul je nasazené na srs-dev.skauting.cz, ještě tam jsou nějaké todos, viz PR: https://github.com/skaut/SRS/pull/889

PR bych ale zamergoval, aby @bojovyletoun měl k dispozici aktuální schéma DB a nebylo pak moc konfliktů.

Dotáhnout to zkusím v neděli / pondělí po návratu. Budu potřebovat ten text podmínek, který se tam má vložit a jak by měl vypadat e-mail, co se bude posílat jako potvrzení (jaké proměnné do něj chceme vkládat).

**Comment by DeetsCZ** [comment]
Jak to procházím, tak mám pár poznámek:
1. Je nějaký důvod, proč má vedoucí, rádce a doprovod cenu podle podakcí? Mohu to změnit a nastavit normálně cenu? Podakce by tady být neměly.
2. Chybí mi tam možnost odstranit zadanou družinu.
3. Bylo by možné, aby se označovali ty duplicitní osoby?

**Comment by davidurban** [comment]
Ahoj, též děkuju všem za práci i testování 😄 ! 

Obecně – prosím kde najdu údaje na testování srs-dev? Jde mi hlavně o admina webu, na ostatní asi půjde použít testovací účty skautISu.

K tomu co psala @DeetsCZ :

1.  Souhlas, stačí nám celková cena za akci
2. To je chyba UX, omlouvám se; prosím přidat do řádku k "Družina má XY účastníků" doprava, použít "btn-outline-danger"
3. Duplicitní osoby bych raději nepovoloval… tedy při zakládání další družiny nedávat na výběr lidi, kteří jsou již registrovaní
4. @DeetsCZ ano, registraci z více středisek nechceme řešit; registrace z oddílů dohromady (v rámci střediska) musí řešit někdo, kdo na to má práva.
5. Souhlas, děkuji; 
6. Děkuji za chycení a prosím o opravu
7.  Děkuji za chycení a prosím o opravu
8. Tam jsem se nedostal 😆 

Mé drobnosti:

- [ ] Když edituju družinu nebo dospěláky mám H1 "Přihláška skupiny". TO je asi fajn, ale v tu chvíli pod tím musí být H2 "Úprava družiny XY", nebo "Úprava dospělých průvodců". A sémanticky dál.
- [ ] Když edituju průvodce a odškrtnu posledního a dám "pokračovat", tak mi tam zůstane. Očekávané chování: nebude tam a vrátím se na editaci skupiny s žádným doprovodem v tabulce
- [ ] Mohly by chyby prosím říkat konkrétněji, co je špatně – třeba místo "Počet doprovodů je příliš vysoký." napsat "Počet doprovodů je příliš vysoký. K nyní registrovaným družinám můžeš mít pouze 1 doprovod."
- [ ] Chybí možnost zrušit registraci a začít znovu (když třeba vyberu špatnou roli); prosím o přidání

@jan-stanek 

Podmínky registrace: https://nsj2023.cz/page/podminky-registrace/default

E-mail: 

> Subject: Registrace na akci NSJ2023! 
> 
> Body:
> 
> Ahoj,
> 
> děkujeme za registraci na NSJ2023. Tento e-mail je potvrzením, že registrace tvé skupiny byla řádně uložena do systému.
> 
> Abychom s vámi mohli počítat je nutné nejpozději do 30 kalendářních dnů, nejpozději však do 15. února 2023 (pokud by nastalo dříve) uhradit XXXYYY Kč účastnického poplatku za celou skupinu na účet: ZZZZZZZ/XXXX s variabilním symbolem: WWWWWWW. S platbou prosím neotálej. 
> 
> Svou skupinu můžeš spravovat po přihlášení na nsj2023.cz. Pokud by se vyskytly jakékoliv potíže, ozvi se nám na registrace@nsj2023.cz.
> 
> Těšíme se! 
> 
> Tým NSJ2023
>

**Comment by davidurban** [comment]
@jan-stanek ad 3) Ano prosím. Ideálně nezobrazovat. 

Díky!

**Comment by DeetsCZ** [comment]
1. upraveno, díky. Tady jsem si všimla, že se cena upravila i u uzavřené přihlášky. Ale to předpokládám, že se upraví po dodělání plateb.
2. Podle dohody by se měla dát odstranit družina i celá přihláška skupiny
3. Ta moje poznámka byla k označení duplicitních osob na posledním kroku přihlášky skupiny. Ta chyba se vypisuje jen na konci a bylo by fajn zvýraznit (třeba červeným textem, které osoby jsem vybrala dvakrát)
4. Můžeme to doplnit vysvětlujícím textem: "Po přidání první družiny není možné měnit roli, pokud jsi udělal chybu, můžeš zrušit přihlášku skupiny a začít znovu"? Dává vám to smysl @davidurban?
5. Jsme si vysvětlili v telefonu, zobrazuje se i pro vyšší věk chybová hláška s nízkým věkem.
6. Ten problem je takto: 1. vyberu pouze 3 členy do družiny, přejdu do kroku 2, kde mohu zadat zdravotní údaje, tam mne zastaví chyba počtu. Když ale dám zpět a zpět (vrátím se tak na stránku skupiny), tak tam mám družinu s 3mi členy.
7. To asi řešit nemusíme, protože se to v reálu nestane. Možná bych jen zvážila, jestli do databáze dávat i členy, které nakonec do družiny nepotvrdím (třeba kvůli věku)

**Comment by bojovyletoun** [comment]
K 5:  když jsem editoval  formátování chybových hlášek  v tomto formuláři přidávání členů do družiny ( Merge request #892 ) ,  v kódu bylo  i pro vysoký věk  hláška pro nízký věk.  Pull request opravuje i tohle, ale všiml jsem si toho dns.

**Comment by jan-stanek** [comment]
@davidurban moc nevím, co tam mám dát jako podmínky registrace přímo do přihlášky, celý obsah té stránky s podmínkami nebo odkaz na PDF?

**Comment by davidurban** [comment]
@DeetsCZ 

4. Domluvili jsme se, že necháme možnost roli změnit a budeme doufat, že to nevybouchne

**Comment by DeetsCZ** [comment]
Registrační formulář je hotový, tedy toto issue uzavřu. Pokud se objeví chyby, tak pro ně otevřu nové issue, protože zde by to bylo nepřehledné.
