### ISSUE TITLE
Přidání přehledu jamoddílů

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#871]
Stránka bude v nastavení pod položkou Uživatelé (bylo by dobré toto nějak přejmenovat, ale teď mne nenapadá vhodný název, nějaký nápad?).
V přehledu bude výpis jamoddílů s položkami:
- identifikátor, datum založení, cena, zaplaceno (pokud "ne", nebo datum zaplacení), počet družin, počet dětí, počet dospělých a tlačítko pro detail
- v detailu budou vypsaní družiny a osoby přidané přímo k jamoddílu

**Comment by bojovyletoun** [comment]
V té administraci to bude vedle tlačítka Uživatelé (http://srs.loc/admin/users/) v sekci uživatelé, že. takže by se to nějak přesunulo na http://srs.loc/admin/users/users a http://srs.loc/admin/users/prehled? Podobně jako sekce Web, Program,Mail
Má tam být stejné GUI jako v těch Uživatelích (že bude stačit zkopírovat šablonu a poupravit sloupce)?
Bude kolem 200 jamodílů?

**Comment by jan-stanek** [comment]
Může to tak být, předpokládám, že ta tabulka bude o dost jednodušší - méně sloupců, nebudou tam hromadné akce apod.

Počet oddílů netuším.

Ve svojí větvi, mám ještě nějaké drobné změny v tabulce oddíl - https://github.com/skaut/SRS/pull/889/files#diff-2f462aff34bcdc1ecdda8e946acd5190079792f1bd6ad34caa8657cf3ded5bfe, možná se bude hodit mít v tabulce toho vedoucího, ale to tam můžeme doplnit později.
