### ISSUE TITLE
CHYBA: Viditelnost dokumentu pro nepřihlášeného

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#874]
V administraci je dokument nastavený jako viditelný pro všechny role, ale pokud přijde osoba na web (Guest), tak se mu zobrazí hlášení "Pro vaši roli nejsou k dispozici žádné dokumenty."

**Comment by DeetsCZ** [comment]
Bylo opraveno

**Comment by jan-stanek** [comment]
Nemyslím, že se okolo toho něco dělalo, ale jestli to funguje :)

**Comment by DeetsCZ** [comment]
@jan-stanek před uzavřením jsem si to vyzkoušela :), je to ok
