### ISSUE TITLE
Zvláštní maily okolo přihlašování na programy

### ISSUE THREAD

**Issue by jan-stanek** [skaut/SRS#884]

**Comment by petrparolek** [comment]
???

**Comment by bojovyletoun** [comment]
To bylo, že se stává, že přijde mail, že dotyčný byl odhlášen z programu a  potom mail, že byl přihlášen na ten program.  Ale už nevím při jaké události nebo co je spouštěč

**Comment by jan-stanek** [comment]
Tohle už asi nezvládneme najít, uvidíme, jestli se objeví znovu
