### ISSUE TITLE
Úprava přihlášeného jamoddílu

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#890]
Vedoucí, který přihlásil jamoddíl ho může po přihlášení měnit do určitého data z nastavení.

Nemůže přidávat ani ubírat osoby. Může pouze měnit jednu osobu za jinou. To platí pro účastníky, rádce i dospělí doprovod. Nemůže měnit sám sebe jako dospělého vedoucího u družin.

**Comment by jan-stanek** [comment]
S Ńufem jsme se domlouvali, že u družin nebude jako dospělý vedoucí vždy ten samý, každá družina by měla mít jiného, ale ten kdo je registruje musí být aspoň v jedné.

Tohle platí ihned po odeslání přihlášky nebo tam budou povolené nějaké další editace třeba před zaplacením?

**Comment by DeetsCZ** [comment]
Podle mne tam musí zůstat ten, kdo je registroval a zbytek se muže měnit. Je to tak @davidurban?

**Comment by davidurban** [comment]
Ano, je to tak. Může měnit všechny lidi (kus za kus) jen registrující musí zůstat. Platí to od okamžiku registrace (abychom to nekomplikovali). Když bude nejhůř, tak mu registraci smažeme.

**Comment by jan-stanek** [comment]
Tohle by mělo být hotové
