### ISSUE TITLE
Nejde přidat dospělé průvodce ze dvou oddílů

### ISSUE THREAD

**Issue by davidurban** [skaut/SRS#897]
Report: 

> před chvílí jsem registroval 2 družiny z našeho střediska, každou z jiného oddílu. Jelikož mám ve skautisu vždy jen oddílovou roli v obou oddílech, musel jsem překlikávat mezi rolemi. Problém nastal v okamžiku registrace dospělých průvodců (dva průvodci, jeden ke každé družině). Bohužel nelze registrovat 2 dospělé průvodce pokud jsou z jiného oddílu a já musím překlikávat mezi oddíly. Musel jsem tedy registrovat pouze jednoho (vůdce střediska) a druhého už mě to zkrátka nepustilo. Vždy se jen vyměnili, takže byl registrovaný pokaždé jen jeden.

**Comment by DeetsCZ** [comment]
Tohle je vlastně v pořádku. 
Aby mohl přihlásit dospělé ze dvou oddílů, tak nemůže mít jen oddílovou roli, ale musí mít střediskovou, aby viděl oba oddíly najednou..

**Comment by DeetsCZ** [comment]
@davidurban  za mne je jediné řešení mít střediskovou roli, co myslíš?

**Comment by davidurban** [comment]
Pokud vidí dva oddíly jako admin, tak má mít možnost přidat dva dospělé, každého z jiného oddílu, ne?

**Comment by DeetsCZ** [comment]
No za mne to takhle není. 
Pokud jsem v roli admina jednoho oddilu tak sestavují z toho oddilu ale v tu stejnou chvíli nevidim ten druhy oddíl. Když se přepnu tak vidím ten druhy oddíl ale už nemohu nahlížet na ten první 🤷‍♀️.. 
Když budu mít střediskovou roli tak vidím vše najednou a jsem v pohodě..
Pokud chci delat něco z více oddilu tak dělám “strediskovou” skupinu a potřebuji středisková práva.. 
Co myslíš?

**Comment by davidurban** [comment]
Hele a co tohle:

> Druhá věc se jedná jedné z vedoucích, která není z našeho oddílu. Ve skautisu mám stejnou roli u obou oddílů (vedoucí/admin). Jenže když v přihlášce naklikám vedoucí z jednoho oddílu a pak chci přidat vedoucí z druhého oddílu smažou se mi ti z toho prvního oddílu. A nepřišla jsem na to, co s tím udělat.

**Comment by DeetsCZ** [comment]
No a není to tím, že v admin roli z druhého oddilu proste nemůže vidět ty z prvniho oddilu?

**Comment by jan-stanek** [comment]
Na začátku se počítalo s tím, že po přidání družiny už roli přepínat nepůjde

**Comment by davidurban** [comment]
@jan-stanek naopak – jsme to přeci měnili s tím, že by to nefungovalo a změny role jsou nutné.

**Comment by davidurban** [comment]
Jakože se nemá stát, že se jim něco smaže – prosím můžete to otestovat? Přidat z jedné role dospělého a pak jiné role jiného dospělého? Za mě je validní use-case, že dospělé přidávám z více oddílů…

**Comment by DeetsCZ** [comment]
Já to včera řešila s Jerrym a tak je to teď, tak je to správně podle původního zadání. To že se smažou účastníci, pokud jsem v roli, kde na ně nemám práva, je za mne teď v pořádku.
To přepínání jsme povolili, aby se jim nezamkla přihláška, pokud si na začátku vyberou špatnou roli.

**Comment by DeetsCZ** [comment]
Budeme řešit s Honzou, jestli by nebylo příliš náročné umožnit kombinovat zadávání z více oddílových rolí. A jestli by to vůbec šlo. Zároveň jsou teď věci, které mají vyšší prioritu k dodělání. Bude tam potřeba řešit víc věcí, například musím u druhého oddílu vidět i sám sebe, abych mohl být vedoucí a pod..
Aktuálně to je za mne v pořádku. Vybírám účastníky, na které mám práva, pokud přepnu roli a na ty účastníky nemám práva, tak se mají smazat. Pokud chci kombinovat přihlášku z více oddílů, tak mám mít střediskovou roli, abych viděla všechny a mohla si vybírat.

**Comment by davidurban** [comment]
Ok… takže workaround je mít střediskovou roli.

**Comment by DeetsCZ** [comment]
@davidurban v tuto chvíli ano a budeme řešit další možnosti, jak to udělat "lépe"
