### ISSUE TITLE
Přejmenovat roli Registrovaný

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#9]
Přejmenovat roli "Registrovaný" na "Nepřihlášený".

**Comment by jan-stanek** [comment]
Ve stávající databázi je nutné provést ještě:

UPDATE `role` SET `name` = 'Nepřihlášený' WHERE `role`.`id` = 2;

**Comment by DeetsCZ** [comment]
Update na databazi jsem udělala a otestovala, uzavírám..
