### ISSUE TITLE
Error 500 při odhlašování účastníka ze semináře nebo změně role.

### ISSUE THREAD

**Issue by marekdedic** [skaut/SRS#911]
Ahoj, když se na webu `https://uls.skaut.cz` pokouším odhlásit účastníka ze semináře nebo někomu změnit roli (různí účastníci), dostávám chybu 500.

**Comment by jan-stanek** [comment]
Ahoj, můžeš se prosím podívat, co je v logu? Nemůže to být třeba jen špatným nastavením SMTP?

**Comment by marekdedic** [comment]
Ahoj, jde logy zobrazit bez FTP přístupu? Ten totiž nemám...

**Comment by DeetsCZ** [comment]
Opraveno, problém byl s e-maily…
