### ISSUE TITLE
Nemožnost změny předčíslí variabilního symbolu

### ISSUE THREAD

**Issue by marekdedic** [skaut/SRS#913]
Ahoj,
na ÚLŠ 2022 jsme před přihlášováním nenastavili předčíslí variabilního symbolu a retroaktivně už nejde změnit - tedy nemůžeme využít plateb přes SRS.

Před přihlašováním jsme předčíslí nevěděli, tedy jsme ho ani nemohli vyplnit předem.

**Comment by DeetsCZ** [comment]
Tohle je problematické, když se účastníci přihlásí, tak se jim rovnou vygenerují údaje pro platbu. Od té chvíle mohou platit, pokud by se VS časem změnil a oni zaplatili s původním tak se platba nespáruje a vyvolá to víc zmatků. 
Pokud by se o něčem takovém uvažovalo, tak by se musel změnit celý systém registrací a plateb. 
Zatím toto uzavírám, protože v současném systému to nedává smysl, ale pokud pokud by se na toto někde znovu narazilo, tak můžeme otevřít širší debatu, jak pracovat s platbami a VS.
