### ISSUE TITLE
Je nějak možné změnit cenu za akci?

### ISSUE THREAD

**Issue by marekdedic** [skaut/SRS#914]
Ahoj,
nenašel jsem nikde, jak retroaktivně změnit cenu akce - při spuštění přihlašování na ÚLŠ 2022 jsme cenu věděli jen přibližně a chtěli jsme ji teď retroaktivně doplnit - přijde mi ale, že to není možné - pokud jsem to jen nenašel, tak issue klidně zavřete (byť i to je nějaká ZV :D).

**Comment by DeetsCZ** [comment]
Viz moje ostatní komentáře
