### ISSUE TITLE
Možnost řešit plaby až dodatečně

### ISSUE THREAD

**Issue by marekdedic** [skaut/SRS#920]
Ahoj,
tohle je vlastně asi nadřazené issue/feature request pro #913, #914 a #915.

Přijde mi, že SRS počítá s tím, že při spuštění přihlašování mám vyřešené účastnické poplatky - a to prostě obecně není pravda. Viz nalinkovaná issues, ale třeba taky to, že automaticky v mailech pro přihlášené je info o platbě, které v takovém případě není správné - na ÚLŠ to vedlo ke zmatení včech přihlášených, že jim to řeklo, že mají zaplatit 0,-. To samé si pamatuji i z jiných přihlašování.

**Comment by DeetsCZ** [comment]
@marekdedic budeš překvapený, ale to teď jsme takový požadavek neměli. 

Aktuální systém s tím nepočítá a musel by se kompletně předělat, nějaké částečné úpravy to nevyřeší. 
Navrhuji k tomu tedy nějakou schůzku (online) během března. Zkusím vymyslet nějaké termíny a kdo všechno by se k tomu mohl vyjádřit a zkusím to sezvat :).
