### ISSUE TITLE
Možnost přihlásit účastníka manuálně

### ISSUE THREAD

**Issue by marekdedic** [skaut/SRS#921]
Ahoj,
chtěl bych manuálně přidat účastníka akce, ale bohužel nemohu - je tam jen tlačítko na přidání lektora a to ho nepropojí s ISem. Nechci ale otevírat celé přihlašování, protože by se to otevřelo všem.

**Comment by DeetsCZ** [comment]
Externě je možné přidat jen lektora, ten se potom nehlásí přes skautis.
Zbytek se musí přihlásit skautis účtem, aby se nacetly údaje. 
Ty nemůžeš ručně někoho přidat ze skautis, protože nemáš práva tu osobu vidět.

Řešení tvého problému je: ať se osoba přihlásí přes skautis a ty mu roli změníš na účastníka. (Potom dořešíme ručně cenu za jidlo).
