### ISSUE TITLE
Smazání dospělého doprovodu nebo družiny

### ISSUE THREAD

**Issue by davidurban** [skaut/SRS#925]
Lidé nám často píší něco v tomhle smyslu:

> Na místo dospělého doprovodu jsem zadal sebe, ale jsem zároveň vedoucí družiny, čímž se účastnický poplatek započítal dvakrát. Jak je možné smazat člověka jako dospělého průvodce?

Mohu prosit o prověření možnosti smazat dospělý doprovod?

**Comment by davidurban** [comment]
Zdá se, že je problém smazat i družinu… :/

**Comment by davidurban** [comment]
Další:

> při placení účastnického poplatku na Jamboree jsem zjistila, že jsem udělala při registraci udělala chybu. Omylem jsem sama sebe přihlásila 2x jako dospělou osobu (jednou jako vedoucí družiny, podruhé jako dospělý průvodce), nějak špatně jsem to při přihlašování pochopila. V přihlášce mi to pak ukazuje, že mám přihlášených 6 osob, ale že mám platit za 7 a nejde mi to změnit.

**Comment by DeetsCZ** [comment]
K opravě jsou tedy dva problémy, oboje u draft přihlášky
1. umožnit osobu z doprovodu odstranit 
2. umožnit odstranit celou družinu

**Comment by davidurban** [comment]
@jan-stanek máme prosím ETA? Blokuje nám to dost přihlášek…

**Comment by DeetsCZ** [comment]
Toto je vyřešené
