### ISSUE TITLE
Nesprávné zorazení částek při ručním párování

### ISSUE THREAD

**Issue by marekdedic** [skaut/SRS#929]
1. Mám účastníka, který zaplatil jinou částku, než je u něj v SRS nastaveno (Např. měl podle SRS platit 500, reálně poslal 200). Dlouhý příběh, ale prostě to tak je
2. Platba se automaticky nespárovala z důvodu nesedící částky - to už je samo o sobě trochu záludný, ale budiž (čekal bych nějaký varování, že se na to mám podívat)
3. Platbu jsem spároval ručně
4. V tabulce účastníků je v kolonce "Zbývá zaplatit" 0. Očekával bych, že tam bude 300, protože účastník měl zaplatit 500 a zaplatil 200, tedy zbývá zaplatit 300...

Pokud ten sloupeček má být pouze indikátor, zda už je zaplaceno, tak tam nemá být částka, ale jen nějaká fajfka/křížek. Pokud tam je částka, čekal bych, že bude odpovídat realitě.

**Comment by jan-stanek** [comment]
To slouží k tomu, když jsou nezaplacené některé podakce, pokud platbu spáruješ ručně bere se to jako, že zaplatil to, co měl.

**Comment by marekdedic** [comment]
No, a to si právě myslím, že je chybné chování.

**Comment by DeetsCZ** [comment]
Ten systém zatím neumí to částečné placení, proto se chodí v tuto chvíli správně.
Pokud se přihláška napáruje, tak se bere jako zaplacená a v přihlášce je 500 kč, proto je i na dokladu 500.

Opět platí moje dřívější poznámka, mohli bychom si udělat schůzku a probrat možnosti, třeba i částečných plateb u osoby.
