### ISSUE TITLE
Chyba: Zobrazení dokumentu

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#93]
Při kliknutí na dokument se zobrazí chyba:
![snimek obrazovky 2016-10-13 v 9 26 11](https://cloud.githubusercontent.com/assets/19816092/19340025/1f286c92-9127-11e6-9ee6-0c7caeada8ed.png)

**Comment by jan-stanek** [comment]
Vypadá to jen na špatné odkazy, stačí nahrát dokumenty znovu.

**Comment by DeetsCZ** [comment]
Vyzkouším...

**Comment by DeetsCZ** [comment]
Chtěla jsem odstranit soubor "RBUDP", ale zobrazuje se varování:
![snimek obrazovky 2016-10-18 v 12 14 40](https://cloud.githubusercontent.com/assets/19816092/19473701/f6f65540-952c-11e6-8cbf-bd94b57d97c8.png)

Nově nahráné dokumenty fungují..

**Comment by jan-stanek** [comment]
Mělo by stačit dokument upravit, nahrát jiný soubor a potom smazat.

**Comment by DeetsCZ** [comment]
Toto zabralo, ale bylo by dobré, aby se v případě smazání původního souboru zobrazovala rozumná chybová stránka, místo varování..

**Comment by jan-stanek** [comment]
Opraveno, lze smazat smazaný soubor - odstraní se jen z db.

**Comment by DeetsCZ** [comment]
Děkuji
