### ISSUE TITLE
Nelze měnit čásky u konkrétních účastníků

### ISSUE THREAD

**Issue by marekdedic** [skaut/SRS#930]
Na ÚLŠ účastníci platili různé částky podle volby jídla. Nepřišel jsem na to, jak částku u konkrétního účastníka změnit - třeba když si svoji volbu ještě změnil. Péťa nám nastavila částky předpokládám nějakým přístupem "zezadu" (Díky!), ale teď by se mi hodilo si to moct ještě upravovat - přežiju to bez toho, ale bylo by to fajn, mít tu možnost.

**Comment by DeetsCZ** [comment]
Vlastně jsem na takovou potřebu nenarazila u jiné akce. 
Myslím, že by bylo řešením na jídlo použít podakce (každý den různá podakce a tak by se každému počítala jiná cena, podle toho, co si vybere). Mimoto variantu upravovat ručně u každého cenu vidím, jako dost problematickou a u velkých akcí se to nebude nikomu chtít dělat.
Opět bych tohle nechala na nějakou větší diskuzi, které by se dala vyvolat k systému plateb (asi na to založím nové issue s nějakým přehledem).
