### ISSUE TITLE
Feature request: Plovoucí hlavička tabulky účastníků

### ISSUE THREAD

**Issue by marekdedic** [skaut/SRS#931]
Když člověk skroluje tabulkou účastníků, je jednoduché se ztratit v tom, který sloupec je co. Pomohlo by mi, kdyby hlavička tabulky byla "Plovoucí" - tedy při skrolování zůstala viditelná, něco jako "Ukotvení řádků" v Excelu/google tabulce...

**Comment by petrparolek** [comment]
já to řešil jinde vlastní šablonou datagridu s opakujícím záhlaví tabulky po např. 30 záznamech. Jiné řešení mě nenapadlo.

**Comment by bojovyletoun** [comment]
Tutoriálů, jak na to, je na internetu je dost, ale nenarazil jsem na žádný (klíčová slova html css table sticky/scrollable ), který by fungoval (rozhodí se buňky, nebo některé ikony "prosvítají" přes záhlaví i když se nastavít pozadí). Návody se liší taky v tom jaký typ display nastavují: block/table/flex.
V zásadě : obalit tabulku do div, nastavit {overflow-y: scroll; height: .... }, dál  thead th  {position:sticky ; top: 0} tfoot {...sticky ; bottom:0}

**Comment by jan-stanek** [comment]
Určitě bych nevymýšlel nějakou modifikaci datagridu, která by se mohla rozbít jeho aktualizací

**Comment by DeetsCZ** [comment]
Pokud @jan-stanek nenapadá nějaká snadná varianta, tak toto zatím uzavřu. Bylo by to hezké, ale pokud nám to aktuálně použitá technologie neumožňuje, tak se s tím v tuto chvíli nemáme zdržovat.
