### ISSUE TITLE
Panel nette

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#94]
Prosím pro instalační balíček skrýt panel nette, není vhodné, aby se zobrazoval pro běžné použití.
Děkuji

**Comment by jan-stanek** [comment]
To je řešené v config/config.neon.

Když se místo `debug: true` nastaví `debug: false`, vypne se panel a použije se jiná konfigurace pro databázi, appID...

**Comment by jan-stanek** [comment]
Nastavil jsem debugování defaultně na false a napsal o tom do instalační příručky.

**Comment by DeetsCZ** [comment]
Děkuji
