### ISSUE TITLE
Nefunguje QR code v Airbank

### ISSUE THREAD

**Issue by kalich5** [skaut/SRS#943]
![image](https://user-images.githubusercontent.com/8988898/211267368-f6eae1f7-4fa7-436f-9ae1-98f29417ba68.png)

Ten QR code nefunguje... píše mi to...

![IMG_5693](https://user-images.githubusercontent.com/8988898/211267413-a5d2c403-6a90-42e7-ba22-c147bcb6eb64.jpg)

**Comment by jan-stanek** [comment]
Co je to za banku? Moneta, RB ani FIO s tím nemají problém, načtu přímo ten ze screenshotu.

**Comment by kalich5** [comment]
AirBank, zkoušel jsem to nekolikrát a nic.

**Comment by jan-stanek** [comment]
Zkusím novější verzi https://github.com/dfridrich/QRPlatba, víc mě nenapadá

**Comment by bojovyletoun** [comment]
Vidím rozdíl jen v částce ( má desetinnou část) a počátku
SPD*1.0
SPD*1.1

9. ledna 2023 8:47:35 UTC, "Jan Staněk" ***@***.***> napsal:

**Comment by kalich5** [comment]
AirBank pořád stejná chyba, FIO v pohodě. Fakt to nechápu...

**Comment by jan-stanek** [comment]
Předpokládám, že jiné kódy v airbank fungují. Nemáš nějakej na ukázku, abych mohl porovnat čím se liší?

**Comment by kalich5** [comment]
Zkusím něco najít, ale jako neměl jsem s tím nikdy žádný problém. Stačí si vzít QR kódy z čehokoliv a to funguje. Tu chybovou hlášku jsem viděl poprvé teď

**Comment by milanskaut** [comment]
Vyzkoušel jsem QR kód z tvého příspěvku & aktuální kód z registrace na reálnou běžící akci a v Air Bank (my air) aplikaci bez jediného problému.
