### ISSUE TITLE
Na webu se nezobrazuje celý harmonogram

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#956]
V administraci je vidět harmonogram celý od 0:00 do 24, ale na webu, kde si účastníci vybírají programy je čas omezen od 6:00 do 22:00.

@jan-stanek asi to bude jen o nějakém nastavení komponenty, mrknul bys na to? Díky

**Comment by jan-stanek** [comment]
Není to tam podle prvního a posledního programu, aby se nezobrazovaly prázdné sloty?

**Comment by DeetsCZ** [comment]
Právě, že tam programy jsou až do 24, při přepnutí do zobrazení seznam jsou programy vidět..

**Comment by jan-stanek** [comment]
Kde to je? Na webu by se to mělo roztahovat automaticky podle programů

**Comment by jan-stanek** [comment]
Už to vidím, asi se to špatně počítá když program končí až v 00:00, může to být ten případ?
