### ISSUE TITLE
Neodchází emaily po přihlášení a odhlášení programu

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#957]
Zjistili jsme na helpdesk.skaut.cz.

Pokud si účastník zapíše nebo odepíše program, tak se neodešle email ikdyž je v nastavení toto aktivní. 
V historii odeslaných emailů s to také nezobrazí.

**Comment by jan-stanek** [comment]
to se má posílat jen v případě, že mu to změní někdo jiný, nemá smysl mu posílat mail, že si sám změnil program, ne?

**Comment by milanskaut** [comment]
Souhlasím, není chyba.
