### ISSUE TITLE
Zadání času začátku semináře

### ISSUE THREAD

**Issue by DeetsCZ** [skaut/SRS#97]
Bylo by dobré, kdyby bylo možné zadat začátek semináře na libovolný čas, nyní je možnost po 15ti minutách. 
Pokud je to možné prosím o přidání kolonky začátek a konec do dialogového okna, které se otevře po zadání semináře do kalendáře.
![snimek obrazovky 2016-10-13 v 9 56 38](https://cloud.githubusercontent.com/assets/19816092/19340894/621d5446-912b-11e6-8b9e-9dc4512568e9.png)

**Comment by jan-stanek** [comment]
Posunout půjde jen začátek, konec se odvozuje od délky bloku, která se počítá jako násobek základní délky bloku.

**Comment by jan-stanek** [comment]
Je možné posouvat jen začátek, konec se odvozuje od délky bloku, který se udává jako násobek základní délky bloku.

**Comment by DeetsCZ** [comment]
Určitě stačí, pokud bude možné zadat pouze začátek a konec se bude upravovat podle zadané délky bloku..

**Comment by jan-stanek** [comment]
Posun času se mi zatím nepodařilo vyřešit, ale narazil jsem na novější verzi kalendáře, která umožňuje přichytávat události k jinak velké mřížce, než se zobrazuje, takže by se daly umístit třeba po 5 minutách, nebylo by to lepší?

**Comment by DeetsCZ** [comment]
Zadání po pěti minutách vypadá dobře a mělo by to být dostatečné..

**Comment by DeetsCZ** [comment]
Bylo by prosím možné kvůli konci semináře upravit formulář pro zadání délky, tak aby bylo možné zadat libovolnou délku? Předpokládám, že semináře budou často trvat i kratší dobu než 60 minut.

**Comment by jan-stanek** [comment]
Taková možnost už tam částečně je - v konfiguraci se nastavuje základní délka bloku, její násobky jsou tady potom na výběr. Nejmenší základní délka je ale 15 minut.

**Comment by jan-stanek** [comment]
Je těch 15 minut dostatečných, nebo mám změnit také třeba na 5?

**Comment by DeetsCZ** [comment]
5 minut už je podle mne málo, ale treba 10 minut by mohlo stačit..
Děkuji

**Comment by jan-stanek** [comment]
Jde jen o tu základní délku v konfiguraci, pokud by to bylo po 10 minutách, tak pak nepůjdou 15minutové bloky apod.

**Comment by jan-stanek** [comment]
Udělal jsem to takhle:
- v konfiguraci se nastaví základní délka (5/10/15/30/45/60/75/90/105/120 minut)
- délka bloku se potom nastavuje jako násobek základní délky a možnosti tam jsou až do 240 minut

Je to takhle dostatečné, nebo mohou být bloky delší než 4 hodiny?

**Comment by DeetsCZ** [comment]
Takto mi to prijde dostatečné, pokud by chtěli udělat delší blok, potom musí použít dva za sebou. Uvidíme, jak dopadne odezva od uživatelů. Děkuji

**Comment by DeetsCZ** [comment]
Děkuji za úpravu
