### ISSUE TITLE
Update Nette na 2.4

### ISSUE THREAD

**Issue by sinacek** [skaut/SRS#99]
Update Nette pomocí composeru na verzi 2.3. (2.4 není kompatibilní s Lebedou před upgradem PHP na verzi 5.6 nebo 7)

Podpora aktuální verze 2.0.18 byla ukončena v lednu 2015.

**Comment by jan-stanek** [comment]
Bude to asi trvat delší dobu, je třeba nahradit hodně zastaralých a nekompatibilních knihoven.

**Comment by jan-stanek** [comment]
updatováno na 2.4

**Comment by sinacek** [comment]
Lebeda už nabízí PHP 7.0 i 7.1, takže by neměl být problém to nasadit i s Nette 2.4.

**Comment by DeetsCZ** [comment]
Aktualizováno..
